'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

export type ManagedDepartment={id:string;name:string;description:string|null;active:boolean;headEmployeeId:string|null;headName:string|null;employeeCount:number};
type Eligibility={departmentId:string;eligible:boolean;employeeCount:number;positionCount:number;hasDepartmentHead:boolean;pendingInvitationCount:number;blockers:string[]};

export default function DepartmentDeletionManager({departments,canManage,busy,onEdit,onArchive,onDeleted}:{departments:ManagedDepartment[];canManage:boolean;busy:boolean;onEdit:(department:ManagedDepartment)=>void;onArchive:(department:ManagedDepartment)=>Promise<void>;onDeleted:()=>Promise<void>}){
 const [eligibility,setEligibility]=useState<Eligibility[]>([]);const [deleting,setDeleting]=useState<ManagedDepartment|null>(null);const [confirmation,setConfirmation]=useState('');const [notice,setNotice]=useState('');const [working,setWorking]=useState(false);
 async function loadEligibility(){const {data,error}=await createClient().rpc('department_deletion_eligibility_v1');if(error)setNotice(error.message);else setEligibility(data??[])}
 useEffect(()=>{void loadEligibility()},[departments]);
 const byDepartment=useMemo(()=>new Map(eligibility.map(item=>[item.departmentId,item])),[eligibility]);
 async function remove(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!deleting||confirmation!==deleting.name)return;const fd=new FormData(e.currentTarget);setWorking(true);const {error}=await createClient().rpc('delete_department_permanently_v1',{p_department_id:deleting.id,p_confirmation_name:confirmation,p_reason:fd.get('reason')||null});setWorking(false);if(error){setNotice(error.message);return}setDeleting(null);setConfirmation('');setNotice('Department permanently deleted.');await Promise.all([loadEligibility(),onDeleted()])}
 return <section className="card"><span className="eyebrow">DEPARTMENTS</span><h2>Organization units</h2>{notice&&<p className="warning">{notice}</p>}{departments.map(department=>{const check=byDepartment.get(department.id),blockers=check?.blockers??['Dependency status is loading'];return <article className="department-card" key={department.id}><span><strong>{department.name}</strong><small>{department.headName?`Head: ${department.headName}`:'No department head'} · {department.employeeCount} employees</small>{check&&!check.eligible&&<small className="department-delete-blocker">Cannot delete: {blockers.join(', ')}.</small>}</span><div className="compact-actions"><span className={`status-pill ${department.active?'healthy':'warning'}`}>{department.active?'ACTIVE':'ARCHIVED'}</span>{canManage&&<><button onClick={()=>onEdit(department)}>Edit</button><button disabled={busy||!department.active||department.employeeCount>0} onClick={()=>void onArchive(department)}>Archive</button><button className="danger-button" disabled={busy||!check?.eligible} title={check?.eligible?'Delete this unused department permanently':`Cannot delete: ${blockers.join(', ')}`} onClick={()=>{setDeleting(department);setConfirmation('');setNotice('')}}>Delete permanently</button></>}</div></article>})}
  {deleting&&<div className="manual-confirmation-backdrop"><aside className="team-invite-drawer destructive-confirmation"><header><div><span className="eyebrow">PERMANENT DELETION</span><h2>Delete department permanently?</h2></div><button onClick={()=>setDeleting(null)}>×</button></header><form className="stack manual-confirmation-list" onSubmit={remove}><p>This action cannot be undone. Archive the department instead if it has been used historically.</p><label>Type <strong>{deleting.name}</strong> to confirm<input autoFocus value={confirmation} onChange={e=>setConfirmation(e.target.value)}/></label><label>Deletion reason (optional)<textarea name="reason" maxLength={500}/></label><button className="danger-button" disabled={working||confirmation!==deleting.name}>{working?'Deleting…':'Delete department permanently'}</button></form></aside></div>}
 </section>
}
