'use client';
import {FormEvent,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {positionsForDepartment,prioritizeManagers,type ManagerOption} from '@/lib/organizational-structure';

export default function EmployeeOrganizationForm({employee,departments,positions,profiles,managers}:{employee:any;departments:any[];positions:any[];profiles:any[];managers:ManagerOption[]}){
 const [departmentId,setDepartmentId]=useState(employee.departmentId??'');const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const available=positionsForDepartment(positions,departmentId);const eligible=prioritizeManagers(managers,departmentId,employee.user_id);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);const {error}=await createClient().rpc('manage_employee_organization',{p_employee_id:employee.user_id,p_department_id:departmentId||null,p_position_id:fd.get('positionId')||null,p_permission_profile_id:fd.get('permissionProfileId'),p_reports_to_employee_id:fd.get('reportsToEmployeeId')||null});setBusy(false);setNotice(error?error.message:'Organization assignment saved.');if(!error)window.location.reload()}
 return <form className="card stack" onSubmit={save}><div><span className="eyebrow">ORGANIZATION ASSIGNMENT</span><h2>Employee structure</h2><p className="muted">Department, position, and reporting lines do not grant access. Permissions come only from the permission profile.</p></div><label>Department<select required value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Select department</option>{departments.filter(d=>d.active).map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></label><label>Position<select name="positionId" required defaultValue={employee.positionId??''} key={departmentId}><option value="">Select position</option>{available.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label>Permission profile<select name="permissionProfileId" required defaultValue={employee.permissionProfileId??''}><option value="">Select permission profile</option>{profiles.filter(p=>p.active).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Reports To<select name="reportsToEmployeeId" defaultValue={employee.reportsToEmployeeId??''}><option value="">No manager</option>{eligible.map(m=><option key={m.id} value={m.id}>{m.name} — {m.position||'No position'} · {m.department||'No department'}</option>)}</select></label><button className="primary" disabled={busy}>{busy?'Saving…':'Save organization assignment'}</button>{notice&&<p className="warning">{notice}</p>}</form>
}
