'use client';
import Link from 'next/link';
import {useCallback,useEffect,useMemo,useState} from 'react';
type Point={index:number;cumulativeR:number};type Trade={id:string;instrument:string;resultR:number;closedAt:string;activationMode:string|null;followedVerdict:boolean};type Evidence={firstEvidenceAt:string|null;decisionCount:number;live:{tradeCount:number;wins:number;losses:number;breakeven:number;winRate:number|null;totalR:number;averageR:number|null;maxDrawdownR:number;adherencePercent:number|null;equityCurve:Point[];recentTrades:Trade[]};backtests:any[]};type Detail={listing:any;release:any;ranking:any;metrics:any;evidence:Evidence;events:any[];installs:any[];recipients:Array<{id:string;name:string}>;allowedTransitions:string[]};
const value=(v:unknown,f='Not enough verified data')=>v==null?f:String(v);const pct=(v:number|null)=>v==null?'Not enough data':`${v}%`;
export default function MarketplaceReleaseDetail({listingId}:{listingId:string}){
 const [detail,setDetail]=useState<Detail|null>(null),[state,setState]=useState('Loading verified release…'),[recipient,setRecipient]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState<string|null>(null);
 const load=useCallback(async()=>{try{const r=await fetch(`/api/hq/marketplace/${listingId}`,{cache:'no-store'}),b=await r.json();if(!r.ok)throw new Error(b.error);setDetail(b);setRecipient(x=>x||b.recipients?.[0]?.id||'');setState('');}catch(e){setState(e instanceof Error?e.message:'Release unavailable.');}},[listingId]);useEffect(()=>{void load();},[load]);
 const install=async()=>{if(!recipient)return;setBusy(true);setMessage(null);try{const r=await fetch(`/api/hq/marketplace/${listingId}/simulate-install`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipientUserId:recipient})}),b=await r.json();if(!r.ok)throw new Error(b.error);setMessage(`Internal license installed safely. Strategy ${b.install?.installedStrategyId??''} remains inactive.`);await load();}catch(e){setMessage(e instanceof Error?e.message:'Installation failed.');}finally{setBusy(false);}};
 const review=async(reviewStatus:string)=>{setBusy(true);setMessage(null);try{const r=await fetch(`/api/hq/marketplace/${listingId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewStatus,note})}),b=await r.json();if(!r.ok)throw new Error(b.error);setMessage(`Review moved to ${reviewStatus.replaceAll('_',' ')}.`);setNote('');await load();}catch(e){setMessage(e instanceof Error?e.message:'Review failed.');}finally{setBusy(false);}};
 if(state)return <div className="stack"><Link href="/hq/marketplace">← Back to Marketplace</Link><section className="card empty-state"><p>{state}</p></section></div>;if(!detail)return null;const {listing,release,metrics,ranking,evidence}=detail,l=evidence.live;
 return <div className="stack marketplace-detail"><Link href="/hq/marketplace">← Back to Marketplace</Link>
 <header className="marketplace-hero"><span className="eyebrow">IMMUTABLE RELEASE · v{release.releaseVersion}</span><h1>{listing.strategyName}</h1><p>{listing.creatorName??'Trade Police'} · {listing.category??'Internal test'} · Private configuration protected</p><div className="marketplace-release-badges"><span className="status-badge">{listing.reviewStatus}</span><span className="status-badge">{release.eligibilityStatus}</span><span className="status-badge">COMMERCE DISABLED</span></div></header>
 <section className="grid grid-3 metric-grid"><Metric label="Performance" v={value(ranking?.performance_score)}/><Metric label="Readiness" v={value(ranking?.marketplace_readiness_score)}/><Metric label="Verified status" v={value(metrics?.metric_status)}/></section>
 <section className="card marketplace-proof-card"><div className="marketplace-proof-heading"><div><span className="eyebrow">EXACT REVISION · VERIFIED LIVE RESULTS</span><h2>Evidence buyers can inspect</h2><p className="muted">Only closed trades linked to this immutable revision count. Private rules, prices and account data stay protected.</p></div><span className="status-badge">{l.tradeCount} VERIFIED TRADES</span></div>
 <div className="marketplace-proof-metrics"><Proof label="Total R" v={`${l.totalR}R`}/><Proof label="Win rate" v={pct(l.winRate)}/><Proof label="Average" v={l.averageR==null?'Not enough data':`${l.averageR}R`}/><Proof label="Max drawdown" v={`${l.maxDrawdownR}R`}/><Proof label="Discipline" v={pct(l.adherencePercent)}/><Proof label="Decisions saved" v={String(evidence.decisionCount)}/></div>
 <div className="marketplace-proof-grid"><div><h3>Verified R curve</h3><Curve points={l.equityCurve}/><p className="muted marketplace-proof-note">Cumulative R—not account balance and not a profit guarantee.</p></div><div><h3>Result distribution</h3><div className="settings-list"><Row label="Wins" v={String(l.wins)}/><Row label="Losses" v={String(l.losses)}/><Row label="Breakeven" v={String(l.breakeven)}/><Row label="Observation began" v={evidence.firstEvidenceAt?new Date(evidence.firstEvidenceAt).toLocaleDateString():'No verified activity yet'}/></div></div></div>
 <h3>Recent verified trades</h3>{l.recentTrades.length?<div className="marketplace-trade-list">{l.recentTrades.map(t=><div className="marketplace-trade-row" key={t.id}><span><strong>{t.instrument}</strong><small>{new Date(t.closedAt).toLocaleString()} · {t.activationMode??'Recorded trade'}</small></span><strong className={t.resultR>=0?'positive':'negative'}>{t.resultR>=0?'+':''}{t.resultR}R</strong><span>{t.followedVerdict?'Rules followed':'Override'}</span></div>)}</div>:<p className="muted">No closed verified trades exist for this revision yet.</p>}</section>
 <section className="card"><span className="eyebrow">HISTORICAL SIMULATION · SEPARATE EVIDENCE</span><h2>Backtest record</h2><p className="muted">Simulation supports review but never counts as verified live performance.</p>{evidence.backtests.length?<div className="marketplace-backtest-list">{evidence.backtests.map(r=><div className="marketplace-backtest-row" key={r.id}><span><strong>{r.instrument} · {r.execution_timeframe}</strong><small>{r.period_start} → {r.period_end}</small></span><span>{r.result?`${value(r.result.total_trades,'0')} trades · ${value(r.result.net_return_percent,'—')}% net · ${value(r.result.max_drawdown_percent,'—')}% DD`:'Completed · result unavailable'}</span></div>)}</div>:<p className="muted">No completed historical simulation exists for this exact revision.</p>}</section>
 <div className="grid grid-2"><section className="card"><span className="eyebrow">QUALIFICATION</span><h2>Threshold snapshot</h2><div className="settings-list"><Row label="Policy observation" v={`${value(metrics?.observation_days,'0')} / ${release.minimumObservationDays} days`}/><Row label="Verified trades" v={String(l.tradeCount)}/><Row label="Discipline" v={pct(l.adherencePercent)}/><Row label="Critical violations" v={value(metrics?.rule_violation_count,'0')}/></div></section>
 <section className="card"><span className="eyebrow">LICENSE TEST</span><h2>{release.sourceType==='INTERNAL_TRADE_POLICE'?'Install without activation':'Protected until approval'}</h2>{release.sourceType==='INTERNAL_TRADE_POLICE'?<><p className="muted">Clones this immutable revision. No charge is created and it is never activated automatically.</p><label className="marketplace-field"><span>Recipient</span><select value={recipient} onChange={e=>setRecipient(e.target.value)}><option value="">Select recipient</option>{detail.recipients.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><button className="button primary" type="button" onClick={install} disabled={busy||!recipient}>{busy?'Working…':'Install internal test license'}</button></>:<p className="muted">Customer-owned strategies remain protected until approval and licensed commerce.</p>}<p className="muted">{detail.installs.length} recorded installation(s)</p></section></div>
 <section className="card"><span className="eyebrow">COMPLIANCE GATE</span><h2>Release review</h2><p className="muted">Approval confirms internal testing only; it does not enable commerce.</p><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Required review note for approval or rejection" rows={3}/><div className="marketplace-review-actions">{detail.allowedTransitions.map(s=><button className="button secondary" type="button" disabled={busy} key={s} onClick={()=>review(s)}>{s.replaceAll('_',' ')}</button>)}</div></section>{message?<p className="status-banner" role="status">{message}</p>:null}
 <section className="card"><span className="eyebrow">APPEND-ONLY AUDIT</span><h2>Release activity</h2><div className="settings-list">{detail.events.length?detail.events.map(e=><div className="event-row" key={e.id}><span><strong>{e.event_type.replaceAll('_',' ')}</strong><small>{e.actor_scope} · {new Date(e.created_at).toLocaleString()}</small></span><span>{e.note||'No note'}</span></div>):<p className="muted">No release events recorded.</p>}</div></section></div>;
}
function Curve({points}:{points:Point[]}){const g=useMemo(()=>{if(points.length<2)return null;const vs=points.map(p=>p.cumulativeR),min=Math.min(...vs),max=Math.max(...vs),range=Math.max(max-min,1);return points.map((p,i)=>`${i/(points.length-1)*100},${92-(p.cumulativeR-min)/range*84}`).join(' ');},[points]);return g?<svg className="marketplace-equity-chart" viewBox="0 0 100 100" preserveAspectRatio="none" role="img" aria-label="Cumulative verified R curve"><line x1="0" y1="92" x2="100" y2="92"/><polyline points={g}/></svg>:<div className="marketplace-equity-empty">The curve appears after the first closed verified trade.</div>}
function Metric({label,v}:{label:string;v:string}){return <div className="card metric"><span>{label}</span><strong>{v}</strong></div>}function Proof({label,v}:{label:string;v:string}){return <div><span>{label}</span><strong>{v}</strong></div>}function Row({label,v}:{label:string;v:string}){return <div className="event-row"><span>{label}</span><strong>{v}</strong></div>}
