'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';

type Detail={listing:any;release:any;ranking:any;metrics:any;events:any[];installs:any[];recipients:Array<{id:string;name:string}>;allowedTransitions:string[]};
const value=(input:unknown,fallback='Not enough verified data')=>input===null||input===undefined?fallback:String(input);

export default function MarketplaceReleaseDetail({listingId}:{listingId:string}){
  const [detail,setDetail]=useState<Detail|null>(null);const [state,setState]=useState('Loading verified release…');
  const [recipient,setRecipient]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [message,setMessage]=useState<string|null>(null);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/hq/marketplace/${listingId}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error);setDetail(body);setRecipient(current=>current||body.recipients?.[0]?.id||'');setState('');}catch(error){setState(error instanceof Error?error.message:'Release unavailable.');}},[listingId]);
  useEffect(()=>{void load();},[load]);
  const install=async()=>{if(!recipient)return;setBusy(true);setMessage(null);try{const response=await fetch(`/api/hq/marketplace/${listingId}/simulate-install`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({recipientUserId:recipient})});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage(`Internal license installed safely. Strategy ${body.install?.installedStrategyId??''} remains inactive.`);await load();}catch(error){setMessage(error instanceof Error?error.message:'Installation failed.');}finally{setBusy(false);}};
  const review=async(reviewStatus:string)=>{setBusy(true);setMessage(null);try{const response=await fetch(`/api/hq/marketplace/${listingId}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({reviewStatus,note})});const body=await response.json();if(!response.ok)throw new Error(body.error);setMessage(`Review moved to ${reviewStatus.replaceAll('_',' ')}.`);setNote('');await load();}catch(error){setMessage(error instanceof Error?error.message:'Review failed.');}finally{setBusy(false);}};
  if(state)return <div className="stack"><Link href="/hq/marketplace">← Back to Marketplace</Link><section className="card empty-state"><p>{state}</p></section></div>;
  if(!detail)return null;const {listing,release,metrics,ranking}=detail;
  return <div className="stack marketplace-detail">
    <Link href="/hq/marketplace">← Back to Marketplace</Link>
    <header className="marketplace-hero"><span className="eyebrow">IMMUTABLE RELEASE · v{release.releaseVersion}</span><h1>{listing.strategyName}</h1><p>{listing.creatorName??'Trade Police'} · {listing.category??'Internal test'} · Private configuration protected</p><div className="marketplace-release-badges"><span className="status-badge">{listing.reviewStatus}</span><span className="status-badge">{release.eligibilityStatus}</span><span className="status-badge">COMMERCE DISABLED</span></div></header>
    <section className="grid grid-3 metric-grid"><div className="card metric"><span>Performance</span><strong>{value(ranking?.performance_score)}</strong></div><div className="card metric"><span>Readiness</span><strong>{value(ranking?.marketplace_readiness_score)}</strong></div><div className="card metric"><span>Verified status</span><strong>{value(metrics?.metric_status)}</strong></div></section>
    <div className="grid grid-2">
      <section className="card"><span className="eyebrow">VERIFIED EVIDENCE</span><h2>Release performance</h2><div className="settings-list"><Row label="Wins" value={value(metrics?.wins)}/><Row label="Losses" value={value(metrics?.losses)}/><Row label="Breakeven" value={value(metrics?.break_even)}/><Row label="Total R" value={value(metrics?.total_r)}/><Row label="Average R" value={value(metrics?.average_r)}/><Row label="Maximum drawdown R" value={value(metrics?.max_drawdown_r)}/><Row label="Strategy adherence" value={metrics?.strategy_adherence_rate==null?'Not enough verified data':`${metrics.strategy_adherence_rate}%`}/></div></section>
      <section className="card"><span className="eyebrow">LICENSE TEST</span><h2>{release.sourceType==='INTERNAL_TRADE_POLICE'?'Install without activation':'Protected until approval'}</h2>{release.sourceType==='INTERNAL_TRADE_POLICE'?<><p className="muted">Clones this immutable revision into the selected account. No charge is created and the strategy is never activated automatically.</p><label className="marketplace-field"><span>Recipient</span><select value={recipient} onChange={event=>setRecipient(event.target.value)}><option value="">Select recipient</option>{detail.recipients.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="button primary" type="button" onClick={install} disabled={busy||!recipient}>{busy?'Working…':'Install internal test license'}</button></>:<p className="muted">Customer-owned strategies cannot be installed during review. Their private rules stay protected until Compliance approval and a future licensed-commerce gate.</p>}<p className="muted">{detail.installs.length} recorded installation(s)</p></section>
    </div>
    <section className="card"><span className="eyebrow">COMPLIANCE GATE</span><h2>Release review</h2><p className="muted">Approval confirms internal testing only. It does not make the strategy public or enable commerce.</p><textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Required review note for approval or rejection" rows={3}/><div className="marketplace-review-actions">{detail.allowedTransitions.map(status=><button className="button secondary" type="button" disabled={busy} key={status} onClick={()=>review(status)}>{status.replaceAll('_',' ')}</button>)}</div></section>
    {message?<p className="status-banner" role="status">{message}</p>:null}
    <section className="card"><span className="eyebrow">APPEND-ONLY AUDIT</span><h2>Release activity</h2><div className="settings-list">{detail.events.length?detail.events.map(event=><div className="event-row" key={event.id}><span><strong>{event.event_type.replaceAll('_',' ')}</strong><small>{event.actor_scope} · {new Date(event.created_at).toLocaleString()}</small></span><span>{event.note||'No note'}</span></div>):<p className="muted">No release events recorded.</p>}</div></section>
  </div>;
}
function Row({label,value}:{label:string;value:string}){return <div className="event-row"><span>{label}</span><strong>{value}</strong></div>}
