'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type Invitation={id:string;name:string;email:string;department:string|null;position:string|null;permissionProfile:string|null;manager:string|null;status:'PENDING'|'ACCEPTED'|'EXPIRED'|'DELIVERY_FAILED'|'REVOKED';createdAt:string;invitedBy:string|null;deliveryProvider:string|null;deliveryConfirmed:boolean;deliveryError:string|null};
export default function PendingInvitations({canManage,refreshKey}:{canManage:boolean;refreshKey:number}){
 const [rows,setRows]=useState<Invitation[]>([]);const [pendingCount,setPendingCount]=useState(0);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function load(){const {data,error}=await createClient().rpc('staff_invitation_workspace_v1');if(error)setNotice(error.message);else{setRows(data?.invitations??[]);setPendingCount(data?.pendingCount??0)}}
 useEffect(()=>{void load()},[refreshKey]);
 async function action(id:string,operation:'resend'|'revoke'){setBusy(true);setNotice('');try{const response=await fetch('/api/hq/staff/invite',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({invitationId:id,action:operation})}),text=await response.text();let result:any={};try{result=text?JSON.parse(text):{}}catch{throw new Error(`Invitation service returned HTTP ${response.status} without a valid response.`)}if(!response.ok)throw new Error(result.error||`Invitation action failed with HTTP ${response.status}.`);setNotice(result.message);await load()}catch(error){setNotice(error instanceof Error?error.message:'Invitation action failed.')}finally{setBusy(false)}}
 return <section className="card pending-invitations"><div className="section-title"><div><span className="eyebrow">PENDING INVITATIONS</span><h2>Employee invitations</h2><p className="muted">Provider acceptance means delivery was requested; it does not confirm that the email reached the recipient.</p></div><span className="status-pill warning">{pendingCount} PENDING</span></div>{notice&&<p className="warning" role="status">{notice}</p>}{rows.length===0?<p className="muted">No pending or recent failed invitations.</p>:<div className="table-wrap"><table className="team-table"><thead><tr><th>Employee</th><th>Department</th><th>Position</th><th>Profile</th><th>Manager</th><th>Status</th><th>Created</th><th>Invited by</th><th>Actions</th></tr></thead><tbody>{rows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small>{row.email}</small></td><td>{row.department||'—'}</td><td>{row.position||'—'}</td><td>{row.permissionProfile||'—'}</td><td>{row.manager||'—'}</td><td><span className={`status-pill ${row.status==='PENDING'?'warning':row.status==='DELIVERY_FAILED'?'danger':row.status==='REVOKED'?'':'healthy'}`}>{row.status.toLowerCase()}</span>{row.deliveryError&&<small>{row.deliveryError}</small>}</td><td>{new Date(row.createdAt).toLocaleString()}</td><td>{row.invitedBy||'—'}</td><td>{canManage&&row.status!=='REVOKED'&&<div className="compact-actions"><button disabled={busy} onClick={()=>void action(row.id,'resend')}>Resend</button><button className="danger-button" disabled={busy} onClick={()=>void action(row.id,'revoke')}>Revoke</button></div>}</td></tr>)}</tbody></table></div>}</section>
}
