'use client';
import {FormEvent,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type Permission={key:string;description:string;sensitive:boolean};
type ManagedProfile={id:string;name:string;description:string|null;roleKey:string;active:boolean;protected:boolean;assignedEmployees:number;permissions:string[]};
type Catalog={profiles:ManagedProfile[];permissions:Permission[]};
const workspaceRoutes=[['SECURITY_ADMIN','Administration'],['HEAD_OF_SALES','Sales'],['COMPLIANCE_OFFICER','Compliance'],['SUPPORT','Support'],['TECHNICIAN','Operations']];

export default function PermissionProfileManager({canManage,onChanged}:{canManage:boolean;onChanged:()=>Promise<void>}){
 const [catalog,setCatalog]=useState<Catalog|null>(null);const [editing,setEditing]=useState<ManagedProfile|null|undefined>(undefined);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 async function load(){setBusy(true);const {data,error}=await createClient().rpc('permission_profile_management_v1');setBusy(false);if(error)setNotice(error.message);else setCatalog(data)}
 useEffect(()=>{void load()},[]);
 async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget),keys=fd.getAll('permissionKeys').map(String);setBusy(true);const {error}=await createClient().rpc('manage_permission_profile_v1',{p_profile_id:editing?.id??null,p_name:fd.get('name'),p_description:fd.get('description'),p_role_key:fd.get('roleKey'),p_active:fd.get('active')==='on',p_permission_keys:keys});setBusy(false);setNotice(error?error.message:editing?'Permission profile updated.':'Permission profile created.');if(!error){setEditing(undefined);await Promise.all([load(),onChanged()])}}
 return <section className="card permission-profile-manager"><div className="section-title"><div><span className="eyebrow">PERMISSION PROFILES</span><h2>Access bundles</h2><p className="muted">Profiles alone grant permissions. Department, position, and reporting lines never change access.</p></div>{canManage&&<button onClick={()=>setEditing(null)}>New profile</button>}</div>
  {notice&&<p className="warning">{notice}</p>}{busy&&!catalog&&<p className="muted">Loading permission profiles…</p>}
  <div className="permission-profile-grid">{catalog?.profiles.map(profile=><article className="permission-profile-card" key={profile.id}><div><strong>{profile.name}</strong><span className={`status-pill ${profile.active?'healthy':'warning'}`}>{profile.active?'ACTIVE':'ARCHIVED'}</span></div><p>{profile.description||'No description'}</p><small>{profile.permissions.length} permissions · {profile.assignedEmployees} active employees</small>{canManage&&!profile.protected&&<button className="secondary-button" onClick={()=>setEditing(profile)}>Edit</button>}</article>)}</div>
  {editing!==undefined&&<div className="manual-confirmation-backdrop"><aside className="team-invite-drawer"><header><div><span className="eyebrow">ACCESS CONTROL</span><h2>{editing?'Edit permission profile':'Create permission profile'}</h2></div><button onClick={()=>setEditing(undefined)}>×</button></header><form className="stack manual-confirmation-list" onSubmit={save}><label>Name<input name="name" required defaultValue={editing?.name??''}/></label><label>Description<textarea name="description" defaultValue={editing?.description??''}/></label><label>Workspace route<select name="roleKey" required defaultValue={editing?.roleKey??'SUPPORT'}>{workspaceRoutes.map(([key,label])=><option value={key} key={key}>{label}</option>)}</select><small>Controls workspace routing only; it does not grant permissions.</small></label><label className="profile-active-toggle"><input name="active" type="checkbox" defaultChecked={editing?.active??true}/> Active</label><fieldset><legend>Permissions</legend><div className="permission-checklist">{catalog?.permissions.map(permission=><label key={permission.key}><input type="checkbox" name="permissionKeys" value={permission.key} defaultChecked={editing?.permissions.includes(permission.key)??false}/><span><strong>{permission.key}</strong><small>{permission.description}{permission.sensitive?' · Sensitive':''}</small></span></label>)}</div></fieldset><button className="primary" disabled={busy}>{busy?'Saving…':'Save permission profile'}</button>{editing&&editing.assignedEmployees>0&&<p className="muted">This profile cannot be archived until its {editing.assignedEmployees} active employee(s) are reassigned.</p>}</form></aside></div>}
 </section>
}
