'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
type Row={customer_id:string;display_name:string;email:string;plan:string;subscription_status:string;created_at:string;last_activity_at?:string;last_contacted_at?:string;next_follow_up_at?:string;analysis_count:number;account_count:number;active_strategy_count:number;lifecycle:string;queue_reason?:string;priority?:number;draft_id?:string;draft_updated_at?:string};
const fmt=(v?:string)=>v?new Date(v).toLocaleDateString():'—';const label=(v:string)=>v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
export default function SalesCRM({data,canManage}:{data:any;query:string;page:number;canManage:boolean}){
 const rows:Row[]=data.queueRows??[],metrics=data.metrics??{},counts=data.queueCounts??{},router=useRouter();const [selected,setSelected]=useState<Row|null>(null),[mode,setMode]=useState<'contact'|'followup'|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected||!mode)return;setBusy(true);setMessage('');const form=new FormData(event.currentTarget),supabase=createClient();
  const result=mode==='contact'?await supabase.rpc('staff_sales_record_contact',{p_customer_id:selected.customer_id,p_contact_type:form.get('method'),p_contacted_at:form.get('contactedAt'),p_summary:form.get('summary'),p_outcome:form.get('outcome'),p_follow_up_at:form.get('followUpAt')||null,p_follow_up_note:form.get('note')||null}):await supabase.rpc('staff_sales_schedule_follow_up',{p_customer_id:selected.customer_id,p_due_at:form.get('dueAt'),p_note:form.get('note'),p_priority:form.get('priority')});
  setBusy(false);if(result.error){setMessage(result.error.message);return}setMode(null);setSelected(null);setMessage(mode==='contact'?'Contact event saved.':'Follow-up scheduled.');router.refresh();
 }
 const kpis=[['Total customers',metrics.total,'All accessible customer profiles'],['Never contacted',metrics.neverContacted,'No persisted contact event'],['Follow-up due',metrics.followUpDue,'Due now or overdue'],['Contacted this week',metrics.contactedThisWeek,'Persisted contacts this week'],['Active customers',metrics.activeCustomers,'Platform activity in 30 days'],['Private Beta',metrics.privateBeta,'Verified beta designation']];
 return <div className="stack sales-v2"><section className="hq-section-heading sales-v2-header"><div><span className="eyebrow">SALES</span><h1>Turn customer activity into adoption, retention, and long-term value.</h1></div><div className="button-row"><Link className="button-link primary" href="/hq/sales/drafts/new">New email draft</Link><Link className="button-link secondary" href="/hq/sales/drafts">View drafts</Link><a className="button-link secondary" href="/api/hq/customers/export">Export customers</a></div></section>
 <section className="sales-kpis">{kpis.map(([name,value,help])=><article className="card" key={String(name)}><span>{name}</span><strong>{Number(value??0).toLocaleString()}</strong><small>{help}</small></article>)}</section>
 {message&&<p className={message.includes('saved')||message.includes('scheduled')?'success':'error'}>{message}</p>}
 <nav className="sales-subnav" aria-label="Sales workspace"><Link className="active" href="/hq/sales">Overview</Link><Link href="/hq/sales/queue">Action Queue</Link><Link href="/hq/customers">Customers</Link><Link href="/hq/sales/drafts">Drafts</Link></nav>
 <section className="card sales-queue-card"><div className="section-title"><div><span className="eyebrow">PRIORITY WORK</span><h2>Sales Action Queue</h2><p className="muted">Summary counts cover all customers permitted to this Sales workspace.</p><div className="sales-count-pills"><span>Overdue <strong>{counts.overdue??0}</strong></span><span>Due today <strong>{counts.dueToday??0}</strong></span><span>Never contacted <strong>{counts.neverContacted??0}</strong></span></div></div><div className="sales-queue-total"><strong>{Number(counts.actionable??0).toLocaleString()}</strong><span>actionable</span></div></div>
 <div className="sales-table sales-preview-table"><div className="sales-table-head"><span>Customer</span><span>Sales need</span><span>Lifecycle</span><span>Follow-up</span><span>Actions</span></div>{rows.map(row=><article className="sales-table-row" key={row.customer_id}><div className="sales-customer"><i>{row.display_name.split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase()}</i><span><strong>{row.display_name}</strong><a href={`mailto:${row.email}`}>{row.email}</a></span></div><div><strong>{row.queue_reason}</strong><small>{row.analysis_count} analyses · {row.account_count} {row.account_count===1?'account':'accounts'}</small></div><div><span className="status-pill">{label(row.lifecycle)} · derived</span></div><div><span>{row.next_follow_up_at?fmt(row.next_follow_up_at):'None scheduled'}</span></div><div className="sales-preview-actions"><Link className="button-link primary" href={`/hq/sales/drafts/new?customer=${row.customer_id}`}>Draft email</Link><div className="sales-preview-desktop-actions">{canManage&&<><button onClick={()=>{setSelected(row);setMode('contact')}}>Contact</button><button onClick={()=>{setSelected(row);setMode('followup')}}>Schedule</button></>}<Link className="button-link secondary" href={`/hq/customers/${row.customer_id}`}>Profile</Link></div><details className="sales-preview-more"><summary>More</summary><div>{canManage&&<><button onClick={()=>{setSelected(row);setMode('contact')}}>Mark contacted</button><button onClick={()=>{setSelected(row);setMode('followup')}}>Schedule</button></>}<Link className="button-link secondary" href={`/hq/customers/${row.customer_id}`}>Profile</Link></div></details></div></article>)}</div>
 {!rows.length?<div className="empty-state"><strong>No Sales actions are currently due.</strong></div>:<div className="sales-preview-footer">{Number(counts.actionable??0)>5&&<span>Showing the 5 highest-priority actions.</span>}<Link className="button-link secondary" href="/hq/sales/queue">View all {Number(counts.actionable??0).toLocaleString()} actions</Link></div>}</section>
 <section className="sales-v2-split"><article className="card"><div className="section-title"><div><span className="eyebrow">EMAIL DRAFTS</span><h2>Continue writing</h2></div><Link href="/hq/sales/drafts">View all</Link></div><div className="sales-mini-list">{(data.recentDrafts??[]).map((d:any)=><Link href={`/hq/sales/drafts/${d.id}`} key={d.id}><strong>{d.subject||'Untitled draft'}</strong><span>{d.display_name} · {label(d.status)}</span><small>Updated {fmt(d.updated_at)}</small></Link>)}{!data.recentDrafts?.length&&<p className="muted">No saved drafts yet.</p>}</div></article><article className="card"><span className="eyebrow">RECENT CONTACT ACTIVITY</span><h2>Customer conversations</h2><div className="sales-mini-list">{(data.recentContacts??[]).map((c:any)=><Link href={`/hq/customers/${c.customer_id}`} key={c.id}><strong>{c.display_name}</strong><span>{label(c.contact_type)} · {label(c.outcome)}</span><small>{fmt(c.contacted_at)}</small></Link>)}{!data.recentContacts?.length&&<p className="muted">No persisted contact events yet.</p>}</div></article></section>
 <section className="card"><span className="eyebrow">CUSTOMER PIPELINE</span><h2>System-derived lifecycle</h2><p className="muted">New, Onboarding, Activated, Engaged, At risk, Dormant and Retained are derived from product activity across all permitted customers. They are not editable Sales claims.</p><div className="sales-segments">{['NEW','ONBOARDING','ACTIVATED','ENGAGED','AT_RISK','DORMANT','RETAINED'].map(stage=><span key={stage}>{label(stage)} <strong>{Number(counts.lifecycle?.[stage]??0).toLocaleString()}</strong></span>)}</div></section>
 {mode&&selected&&<div className="modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget){setMode(null);setSelected(null)}}}><form className="card modal-card sales-modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{mode==='contact'?'CONTACT EVENT':'FOLLOW-UP'}</span><h2>{selected.display_name}</h2></div><button type="button" onClick={()=>{setMode(null);setSelected(null)}} aria-label="Close">×</button></div>{mode==='contact'?<><label>Method<select name="method" defaultValue="EMAIL"><option>EMAIL</option><option>CALL</option><option>WHATSAPP</option><option>MEETING</option><option>OTHER</option></select></label><label>Contact date and time<input name="contactedAt" type="datetime-local" required defaultValue={new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16)}/></label><label>Summary<textarea name="summary" required maxLength={1000}/></label><label>Outcome<select name="outcome"><option>NO_RESPONSE</option><option>INTERESTED</option><option>NEEDS_HELP</option><option>FOLLOW_UP_REQUIRED</option><option>NOT_INTERESTED</option><option>RESOLVED</option></select></label><label>Optional follow-up<input name="followUpAt" type="datetime-local"/></label><label>Optional note<textarea name="note" maxLength={500}/></label></>:<><label>Due date and time<input name="dueAt" type="datetime-local" required/></label><label>Priority<select name="priority"><option>NORMAL</option><option>HIGH</option></select></label><label>Note<textarea name="note" required maxLength={500}/></label></>}<button className="primary" disabled={busy}>{busy?'Saving…':'Save'}</button></form></div>}
 </div>
}
