'use client';
import {useMemo,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
const filters=['ALL','FREE','BETA','PRO','PREMIUM','NEVER_PAID','ACTIVE','PAST_DUE'] as const;
export default function SalesCRM({rows}:{rows:any[]}){
 const [filter,setFilter]=useState<(typeof filters)[number]>('ALL');const [query,setQuery]=useState('');const [message,setMessage]=useState('');
 const filtered=useMemo(()=>rows.filter(r=>{const text=`${r.display_name} ${r.email} ${r.plan} ${r.subscription_status}`.toLowerCase();if(!text.includes(query.toLowerCase()))return false;switch(filter){case'FREE':return r.plan==='FREE';case'BETA':return r.is_beta_tester;case'PRO':return r.plan==='PRO';case'PREMIUM':return r.plan==='PREMIUM';case'NEVER_PAID':return Number(r.subscription_price_usd||0)===0&&r.plan==='FREE';case'ACTIVE':return r.subscription_status==='ACTIVE';case'PAST_DUE':return ['PAST_DUE','PAYMENT_FAILED','EXPIRED'].includes(r.subscription_status);default:return true}}),[rows,filter,query]);
 const counts={ALL:rows.length,FREE:rows.filter(r=>r.plan==='FREE').length,BETA:rows.filter(r=>r.is_beta_tester).length,PRO:rows.filter(r=>r.plan==='PRO').length,PREMIUM:rows.filter(r=>r.plan==='PREMIUM').length,NEVER_PAID:rows.filter(r=>Number(r.subscription_price_usd||0)===0&&r.plan==='FREE').length,ACTIVE:rows.filter(r=>r.subscription_status==='ACTIVE').length,PAST_DUE:rows.filter(r=>['PAST_DUE','PAYMENT_FAILED','EXPIRED'].includes(r.subscription_status)).length};
 async function contacted(id:string){const {error}=await createClient().rpc('staff_mark_customer_contacted',{p_customer_id:id});setMessage(error?.message||'Customer marked as contacted.');}
 return <div className="stack"><section className="card hq-hero-card"><div><span className="eyebrow">SALES CRM</span><h1>Who should Sales help today?</h1><p>Every registered customer, beta tester and subscriber in one searchable workspace.</p></div><div className="hq-mission"><small>MISSION</small><strong>Convert free usage into long-term customer value.</strong></div></section>
 <div className="sales-crm-filters">{filters.map(f=><button key={f} className={`card sales-filter-card ${filter===f?'selected':''}`} onClick={()=>setFilter(f)}><span>{f.replace('_',' ')}</span><strong>{counts[f]}</strong></button>)}</div>
 <section className="card"><div className="section-title"><div><span className="eyebrow">CUSTOMERS</span><h2>{filter.replace('_',' ')}</h2><p className="muted">Email, follow up and understand each customer's subscription context.</p></div><input className="crm-search" placeholder="Search name, email, plan or status" value={query} onChange={e=>setQuery(e.target.value)}/></div>{message&&<p className="success">{message}</p>}
 <div className="sales-record-list">{filtered.map(r=><article className="sales-record" key={r.customer_id}><div className="sales-record-main"><div className="sales-record-title"><strong>{r.display_name}</strong>{r.is_beta_tester&&<span className="status-pill healthy">BETA ✓</span>}</div><a href={`mailto:${r.email}`}>{r.email}</a><small>Joined {new Date(r.created_at).toLocaleDateString()} · {r.analysis_count} analyses</small></div><div className="sales-record-context"><strong>{r.plan}{r.plan==='PRO'?' · $10/mo':r.plan==='PREMIUM'?' · $20/mo':''}</strong><span>{r.subscription_status}</span><small>{r.renewal_at?`Renews ${new Date(r.renewal_at).toLocaleDateString()}`:r.last_contacted_at?`Last contacted ${new Date(r.last_contacted_at).toLocaleDateString()}`:'Never contacted'}</small></div><div className="staff-actions sales-record-actions"><a className="button-link primary" href={`mailto:${r.email}?subject=Trade Police account follow-up`}>Email</a><button onClick={()=>void contacted(r.customer_id)}>Mark contacted</button><Link className="button-link secondary" href={`/hq/customers/${r.customer_id}`}>Profile</Link></div></article>)}</div>{!filtered.length&&<div className="empty-state"><strong>No customers match this view.</strong></div>}</section></div>
}
