'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Staff={user_id:string;email:string|null;display_name:string|null;role:string;display_title:string|null;is_active:boolean;mfa_required:boolean;last_active_at:string|null;created_at:string;invitation_status?:string|null};
type Permission={permission_key:string;description:string;sensitive:boolean;granted:boolean;source:string};

export default function StaffDirectory({initialStaff}:{initialStaff:Staff[]}){
 const [staff,setStaff]=useState(initialStaff); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<Staff|null>(null); const [permissions,setPermissions]=useState<Permission[]>([]); const [loadingPermissions,setLoadingPermissions]=useState(false);
 async function reload(){const {data,error}=await createClient().rpc('owner_staff_directory');if(error)setMessage('Staff directory could not be refreshed.');else setStaff(data??[])}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const fd=new FormData(form);setBusy(true);setMessage('');
   const response=await fetch('/api/hq/staff/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:fd.get('email'),displayName:fd.get('displayName'),role:fd.get('role'),title:fd.get('title')})});
   const result=await response.json().catch(()=>({error:'Invitation failed.'}));setBusy(false);
   if(!response.ok){setMessage(result.error||'Invitation failed.');return;}form.reset();setMessage(result.message||'Invitation sent.');await reload();
 }
 async function toggle(row:Staff){setBusy(true);const {error}=await createClient().rpc('owner_set_staff_active',{p_user_id:row.user_id,p_active:!row.is_active});setBusy(false);setMessage(error?'Staff status could not be changed.':row.is_active?'Staff access suspended.':'Staff access restored.');if(!error)await reload()}
 async function openPermissions(row:Staff){setSelected(row);setLoadingPermissions(true);setMessage('');const {data,error}=await createClient().rpc('owner_staff_permission_matrix',{p_user_id:row.user_id});setLoadingPermissions(false);if(error){setMessage('Permissions could not be loaded.');setPermissions([]);return;}setPermissions(data??[])}
 async function setPermission(permission:Permission,granted:boolean){if(!selected)return;setBusy(true);const {error}=await createClient().rpc('owner_set_staff_permission',{p_user_id:selected.user_id,p_permission:permission.permission_key,p_granted:granted});setBusy(false);if(error){setMessage('Permission could not be updated.');return;}setPermissions(current=>current.map(row=>row.permission_key===permission.permission_key?{...row,granted,source:'CUSTOM'}:row));setMessage('Permission updated and audited.')}
 return <div className="stack">
  <form className="card hq-form-card" onSubmit={invite}><div className="section-title"><div><span className="eyebrow">TEAM ACCESS</span><h2>Invite an employee</h2><p className="muted">Create HQ access directly. Employees never need to register as customers.</p></div><span className="status-pill healthy">Owner controlled</span></div>
   <div className="grid grid-2"><label>Employee name<input name="displayName" required placeholder="David Charles"/></label><label>Email<input name="email" type="email" required placeholder="david@company.com"/></label><label>Starting role<select name="role" required defaultValue="HEAD_OF_SALES"><option value="HEAD_OF_SALES">Head of Sales</option><option value="COMPLIANCE_OFFICER">Compliance Officer</option><option value="SUPPORT">Support</option><option value="TECHNICIAN">Technician</option><option value="SECURITY_ADMIN">Security Admin</option></select></label><label>Display title<input name="title" placeholder="Sales Manager"/></label></div>
   <button className="primary" disabled={busy}>{busy?'Sending invitation…':'Send employee invitation'}</button>{message&&<p className="warning">{message}</p>}
  </form>

  <section className="card"><div className="section-title"><div><span className="eyebrow">TEAM DIRECTORY</span><h2>People and access</h2></div><span className="muted">Individual identities · no shared accounts</span></div>{staff.length===0&&<p className="muted">No employees have been added yet.</p>}{staff.map(row=><div className="staff-row" key={row.user_id}><div><strong>{row.display_name||row.email||'Staff member'}</strong><small>{row.email} · {row.display_title||row.role.replaceAll('_',' ')}</small></div><div><span className={`status-pill ${row.invitation_status==='INVITED'?'warning':row.is_active?'healthy':'warning'}`}>{row.invitation_status==='INVITED'?'INVITED':row.is_active?'ACTIVE':'SUSPENDED'}</span><small>{row.invitation_status==='INVITED'?'Waiting for employee to accept':row.mfa_required?'MFA required':'MFA optional'} · {row.last_active_at?`Last active ${new Date(row.last_active_at).toLocaleString()}`:'No HQ activity yet'}</small></div><div className="staff-actions"><button className="secondary-button" onClick={()=>void openPermissions(row)} disabled={busy}>Permissions</button>{row.role!=='OWNER'&&<button className={row.is_active?'danger-button':'secondary-button'} onClick={()=>void toggle(row)} disabled={busy}>{row.is_active?'Suspend':'Restore'}</button>}</div></div>)}</section>

  {selected&&<section className="card permission-panel"><div className="section-title"><div><span className="eyebrow">INDIVIDUAL ACCESS</span><h2>{selected.display_name||selected.email}</h2><p className="muted">Role defaults are a starting point. The Owner can tailor each employee’s access.</p></div><button className="secondary-button" onClick={()=>{setSelected(null);setPermissions([])}}>Close</button></div>{loadingPermissions?<p className="muted">Loading permissions…</p>:<div className="permission-grid">{permissions.map(permission=><label className={`permission-item ${permission.sensitive?'sensitive':''}`} key={permission.permission_key}><input type="checkbox" checked={permission.granted} onChange={event=>void setPermission(permission,event.target.checked)} disabled={busy||selected.role==='OWNER'}/><span><strong>{permission.permission_key}</strong><small>{permission.description}</small><em>{permission.sensitive?'Sensitive permission':permission.source==='CUSTOM'?'Custom override':'Role default'}</em></span></label>)}</div>}</section>}
 </div>
}
