'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

type Staff={user_id:string;email:string|null;display_name:string|null;role:string;display_title:string|null;is_active:boolean;mfa_required:boolean;last_active_at:string|null;created_at:string};
type Permission={permission_key:string;description:string;sensitive:boolean;granted:boolean;source:string};

export default function StaffDirectory({initialStaff}:{initialStaff:Staff[]}){
 const [staff,setStaff]=useState(initialStaff); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [selected,setSelected]=useState<Staff|null>(null); const [permissions,setPermissions]=useState<Permission[]>([]); const [loadingPermissions,setLoadingPermissions]=useState(false);
 async function reload(){const {data,error}=await createClient().rpc('owner_staff_directory');if(error)setMessage('Staff directory could not be refreshed.');else setStaff(data??[])}
 async function assign(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=e.currentTarget;const fd=new FormData(f);setBusy(true);setMessage('');const {error}=await createClient().rpc('owner_assign_staff_by_email',{p_email:String(fd.get('email')||''),p_role:String(fd.get('role')||''),p_title:String(fd.get('title')||'')});setBusy(false);if(error){setMessage(error.message.includes('must create')?'That person must create a Trade Police account first.':'Staff access could not be assigned.');return;}f.reset();setMessage('Staff access assigned.');await reload()}
 async function toggle(row:Staff){setBusy(true);const {error}=await createClient().rpc('owner_set_staff_active',{p_user_id:row.user_id,p_active:!row.is_active});setBusy(false);setMessage(error?'Staff status could not be changed.':row.is_active?'Staff access suspended.':'Staff access restored.');if(!error)await reload()}
 async function openPermissions(row:Staff){setSelected(row);setLoadingPermissions(true);setMessage('');const {data,error}=await createClient().rpc('owner_staff_permission_matrix',{p_user_id:row.user_id});setLoadingPermissions(false);if(error){setMessage('Permissions could not be loaded. Run migration 012.');setPermissions([]);return;}setPermissions(data??[])}
 async function setPermission(permission:Permission,granted:boolean){if(!selected)return;setBusy(true);const {error}=await createClient().rpc('owner_set_staff_permission',{p_user_id:selected.user_id,p_permission:permission.permission_key,p_granted:granted});setBusy(false);if(error){setMessage('Permission could not be updated.');return;}setPermissions(current=>current.map(row=>row.permission_key===permission.permission_key?{...row,granted,source:'CUSTOM'}:row));setMessage('Permission updated and audited.')}
 return <div className="stack">
  <form className="card hq-form-card" onSubmit={assign}><div className="section-title"><div><span className="eyebrow">TEAM ACCESS</span><h2>Add a staff member</h2></div><span className="status-pill">Individual login required</span></div><p className="muted">The person creates a normal account first. You assign their company role and then tailor individual permissions.</p><div className="grid grid-3"><label>Email<input name="email" type="email" required placeholder="sales@company.com"/></label><label>Starting role<select name="role" required defaultValue="HEAD_OF_SALES"><option>HEAD_OF_SALES</option><option>COMPLIANCE_OFFICER</option><option>SUPPORT</option><option>TECHNICIAN</option><option>SECURITY_ADMIN</option></select></label><label>Display title<input name="title" placeholder="Head of Sales"/></label></div><button className="primary" disabled={busy}>{busy?'Assigning…':'Assign staff access'}</button>{message&&<p className="warning">{message}</p>}</form>

  <section className="card"><div className="section-title"><div><span className="eyebrow">TEAM DIRECTORY</span><h2>Staff members</h2></div><span className="muted">No shared accounts</span></div>{staff.map(row=><div className="staff-row" key={row.user_id}><div><strong>{row.display_name||row.email||'Staff member'}</strong><small>{row.email} · {row.display_title||row.role.replaceAll('_',' ')}</small></div><div><span className={`status-pill ${row.is_active?'healthy':'warning'}`}>{row.is_active?'ACTIVE':'SUSPENDED'}</span><small>{row.mfa_required?'MFA required':'MFA optional'} · {row.last_active_at?`Last active ${new Date(row.last_active_at).toLocaleString()}`:'No staff activity yet'}</small></div><div className="staff-actions"><button className="secondary-button" onClick={()=>void openPermissions(row)} disabled={busy}>Permissions</button>{row.role!=='OWNER'&&<button className={row.is_active?'danger-button':'secondary-button'} onClick={()=>void toggle(row)} disabled={busy}>{row.is_active?'Suspend':'Restore'}</button>}</div></div>)}</section>

  {selected&&<section className="card permission-panel"><div className="section-title"><div><span className="eyebrow">INDIVIDUAL ACCESS</span><h2>{selected.display_name||selected.email}</h2><p className="muted">Role defaults are a starting point. Every permission below can be granted or removed by the Owner.</p></div><button className="secondary-button" onClick={()=>{setSelected(null);setPermissions([])}}>Close</button></div>{loadingPermissions?<p className="muted">Loading permissions…</p>:<div className="permission-grid">{permissions.map(permission=><label className={`permission-item ${permission.sensitive?'sensitive':''}`} key={permission.permission_key}><input type="checkbox" checked={permission.granted} onChange={event=>void setPermission(permission,event.target.checked)} disabled={busy||selected.role==='OWNER'}/><span><strong>{permission.permission_key}</strong><small>{permission.description}</small><em>{permission.sensitive?'Sensitive permission':permission.source==='CUSTOM'?'Custom override':'Role default'}</em></span></label>)}</div>}</section>}
 </div>
}
