'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {DiagnosticStrategy,STRATEGY_UUID,strategyOptionLabel} from '@/lib/strategy-diagnostic-selector';

export default function StrategyCompatibilityInspector({initialStrategyId=''}:{initialStrategyId?:string}){
  const router=useRouter();
  const [query,setQuery]=useState('');const [options,setOptions]=useState<DiagnosticStrategy[]>([]);const [selected,setSelected]=useState<DiagnosticStrategy|null>(null);
  const [optionsState,setOptionsState]=useState<'loading'|'ready'|'empty'|'error'|'denied'>('loading');const [total,setTotal]=useState(0);
  const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);const [advancedId,setAdvancedId]=useState('');const [advancedError,setAdvancedError]=useState('');
  useEffect(()=>{const controller=new AbortController(),timer=setTimeout(async()=>{setOptionsState('loading');try{const search=new URLSearchParams();if(query.trim())search.set('q',query.trim());if(initialStrategyId&&!query.trim()&&!selected)search.set('strategyId',initialStrategyId);const response=await fetch(`/api/admin/diagnostics/strategies?${search}`,{cache:'no-store',signal:controller.signal});const body=await response.json();if(!response.ok){setOptionsState(response.status===403?'denied':'error');return}const items:DiagnosticStrategy[]=body.items??[];setOptions(items);setTotal(Number(body.total??items.length));if(initialStrategyId&&!selected){const match=items.find(item=>item.id===initialStrategyId);if(match)setSelected(match);else if(search.has('strategyId'))setError('The selected strategy no longer exists or is not available to you.')}else if(!query&&items.length===1&&Number(body.total)===1&&!selected)setSelected(items[0]);setOptionsState(items.length?'ready':'empty')}catch(value){if((value as Error).name!=='AbortError')setOptionsState('error')}},300);return()=>{clearTimeout(timer);controller.abort()}},[query,initialStrategyId,selected]);
  async function inspectId(strategyId:string){setLoading(true);setError('');setData(null);try{const response=await fetch(`/api/admin/diagnostics/strategies/${encodeURIComponent(strategyId)}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(response.status===403?'You do not have permission to inspect this strategy.':response.status===404?'The selected strategy no longer exists.':'The diagnostic could not be completed.');setData(body.diagnostic);router.replace(`/hq/system/strategy-compatibility?strategyId=${encodeURIComponent(strategyId)}`,{scroll:false})}catch(value){setError(value instanceof Error?value.message:'The diagnostic could not be completed.')}finally{setLoading(false)}}
  function inspectSelected(event:FormEvent){event.preventDefault();if(selected)void inspectId(selected.id)}
  function inspectAdvanced(event:FormEvent){event.preventDefault();const id=advancedId.trim();if(!STRATEGY_UUID.test(id)){setAdvancedError('Enter a valid strategy UUID.');return}setAdvancedError('');void inspectId(id)}
  const list=(value:unknown)=>Array.isArray(value)&&value.length?value.map(String).join(', '):'None';
  return <section className="card strategy-inspector"><div className="section-title"><div><span className="eyebrow">STRATEGY DIAGNOSTICS</span><h2>Strategy Compatibility Inspector</h2><p className="muted">Search for an accessible strategy. Authorization is checked again when the diagnostic runs.</p></div></div>
    <form className="stack" onSubmit={inspectSelected}><label htmlFor="strategy-search"><strong>Strategy</strong></label><input id="strategy-search" role="combobox" aria-controls="strategy-options" aria-expanded={optionsState==='ready'} autoComplete="off" placeholder="Search by strategy, customer, or instrument" value={query} onChange={event=>{setQuery(event.target.value);setSelected(null);setData(null)}}/>
      {optionsState==='loading'&&<p className="muted" aria-live="polite">Loading strategies…</p>}{optionsState==='empty'&&<p className="muted">No accessible strategies found.</p>}{optionsState==='error'&&<p className="warning">Strategies could not be loaded. Please try again.</p>}{optionsState==='denied'&&<p className="warning">You do not have permission to load strategies.</p>}
      {optionsState==='ready'&&<div id="strategy-options" className="strategy-selector-options" role="listbox" aria-label={`${total} accessible strategies`}>{options.map(item=><button type="button" role="option" aria-selected={selected?.id===item.id} className={selected?.id===item.id?'selected':undefined} key={item.id} onClick={()=>{setSelected(item);setQuery(item.name)}}>{strategyOptionLabel(item)}</button>)}</div>}
      {selected&&<p className="success">Selected: <strong>{strategyOptionLabel(selected)}</strong></p>}<button type="submit" disabled={!selected||loading}>{loading?'Inspecting…':'Inspect strategy'}</button>
    </form>
    <details className="strategy-inspector-advanced"><summary>Advanced · Inspect by UUID</summary><form className="button-row" onSubmit={inspectAdvanced}><input aria-label="Strategy UUID" placeholder="Strategy UUID" value={advancedId} onChange={event=>setAdvancedId(event.target.value)}/><button type="submit" disabled={loading}>Inspect UUID</button></form>{advancedError&&<p className="warning">{advancedError}</p>}</details>
    {error&&<p className="warning" role="alert">{error}</p>}{data&&<div className="stack"><div><span className="eyebrow">DIAGNOSTIC RESULT</span><h2>{data.strategyName}</h2><span className="status-pill">{data.compatibilityStatus}</span></div><div className="grid grid-3"><Metric label="Strategy" value={data.strategyName}/><Metric label="Schema version" value={String(data.schemaVersion)}/><Metric label="Confidence threshold" value={`${data.confidenceThreshold}%`}/><Metric label="Methodology" value={list(data.primaryMethodologyIds)}/><Metric label="Mandatory evidence" value={list(data.mandatoryEvidenceIds)}/><Metric label="Optional evidence" value={list(data.optionalEvidenceIds)}/><Metric label="Normalized evidence" value={list(data.normalizedEvidenceIds)}/><Metric label="Supported rules" value={list(data.supportedEvidenceIds)}/><Metric label="Unsupported rules" value={list(data.unsupportedEvidenceIds)}/><Metric label="Missing configuration" value={list(data.incompleteFields)}/><Metric label="Timeframes" value={`${data.timeframePolicy?.trend}/${data.timeframePolicy?.confirmation}/${data.timeframePolicy?.entry}`}/><Metric label="Strict alignment" value={data.timeframePolicy?.requireAlignment?'Enabled':'Disabled'}/></div></div>}
  </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="card metric"><span className="muted">{label}</span><strong>{value}</strong></div>}
