'use client';
import {FormEvent,useState} from 'react';

export default function StrategyCompatibilityInspector(){
  const [strategyId,setStrategyId]=useState('');const [data,setData]=useState<any>(null);const [error,setError]=useState('');const [loading,setLoading]=useState(false);
  async function inspect(event:FormEvent){event.preventDefault();setLoading(true);setError('');setData(null);try{const response=await fetch(`/api/admin/diagnostics/strategies/${encodeURIComponent(strategyId.trim())}`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(body.error||'Diagnostic unavailable.');setData(body.diagnostic)}catch(value){setError(value instanceof Error?value.message:'Diagnostic unavailable.')}finally{setLoading(false)}}
  const list=(value:unknown)=>Array.isArray(value)&&value.length?value.map(String).join(', '):'None';
  return <section className="card"><div className="section-title"><div><span className="eyebrow">STRATEGY DIAGNOSTICS</span><h2>Strategy Compatibility Inspector</h2><p className="muted">Inspect a strategy by UUID. Access is limited to its owner or staff with System Health permission.</p></div></div><form className="button-row" onSubmit={inspect}><input aria-label="Strategy ID" placeholder="Strategy UUID" value={strategyId} onChange={event=>setStrategyId(event.target.value)} required/><button type="submit" disabled={loading}>{loading?'Inspecting…':'Inspect strategy'}</button></form>{error&&<p className="warning">{error}</p>}{data&&<div className="stack"><span className="status-pill">{data.compatibilityStatus}</span><div className="grid grid-3"><Metric label="Strategy" value={`${data.strategyName} · ${data.strategyId}`}/><Metric label="Schema version" value={String(data.schemaVersion)}/><Metric label="Confidence threshold" value={`${data.confidenceThreshold}%`}/><Metric label="Methodology" value={list(data.primaryMethodologyIds)}/><Metric label="Mandatory evidence" value={list(data.mandatoryEvidenceIds)}/><Metric label="Optional evidence" value={list(data.optionalEvidenceIds)}/><Metric label="Normalized evidence" value={list(data.normalizedEvidenceIds)}/><Metric label="Supported rules" value={list(data.supportedEvidenceIds)}/><Metric label="Unsupported rules" value={list(data.unsupportedEvidenceIds)}/><Metric label="Missing configuration" value={list(data.incompleteFields)}/><Metric label="Timeframes" value={`${data.timeframePolicy?.trend}/${data.timeframePolicy?.confirmation}/${data.timeframePolicy?.entry}`}/><Metric label="Strict alignment" value={data.timeframePolicy?.requireAlignment?'Enabled':'Disabled'}/></div></div>}</section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="card metric"><span className="muted">{label}</span><strong>{value}</strong></div>}
