'use client';
import {FormEvent,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import type {HQStrategySummary} from '@/lib/hq/strategy-summary';
import {STRATEGY_UUID,strategyOptionLabel} from '@/lib/strategy-diagnostic-selector';

type Filters={q:string;customer:string;instrument:string;methodology:string;status:string;engineVersion:string;health:string;timeframe:string};
const emptyFilters:Filters={q:'',customer:'',instrument:'',methodology:'',status:'',engineVersion:'',health:'',timeframe:''};
const detail=(summary:HQStrategySummary)=>[['Customer',summary.customer.name??'Unknown customer'],['State',summary.state],['Engine',summary.engineVersion?`v${summary.engineVersion}`:'Not recorded'],['Revision',summary.revision??'Not recorded'],['Instruments',summary.instruments.join(', ')||'None'],['Category',summary.category??'Not classified'],['Methodologies',summary.methodologies.join(', ')||'Not classified'],['Timeframe roles',Object.entries(summary.timeframeRoles).filter(([,value])=>value).map(([role,value])=>`${role}: ${value}`).join(' · ')||'Not recorded'],['Rules',`${summary.rules.total} total · ${summary.rules.required} required · ${summary.rules.optional} optional`],['Capabilities',`${summary.rules.automatic} automatic · ${summary.rules.manual} manual · ${summary.rules.external} external`],['Health',summary.health.state],['Users',String(summary.usage.users)],['Analyses',String(summary.usage.analyses)],['Decisions',String(summary.usage.decisions)],['Trades taken',String(summary.usage.tradesTaken)],['Last used',summary.usage.lastUsedAt?new Date(summary.usage.lastUsedAt).toLocaleString():'Not yet used']];

export default function StrategyCompatibilityInspector({initialStrategyId=''}:{initialStrategyId?:string}){
  const router=useRouter();const [filters,setFilters]=useState<Filters>(emptyFilters),[items,setItems]=useState<HQStrategySummary[]>([]),[selected,setSelected]=useState<HQStrategySummary|null>(null),[state,setState]=useState<'loading'|'ready'|'empty'|'error'|'denied'>('loading'),[error,setError]=useState(''),[advancedId,setAdvancedId]=useState('');
  useEffect(()=>{const controller=new AbortController();void (async()=>{setState('loading');try{const params=new URLSearchParams();Object.entries(filters).forEach(([key,value])=>value&&params.set(key,value));if(initialStrategyId&&!selected&&!filters.q)params.set('strategyId',initialStrategyId);const response=await fetch(`/api/admin/diagnostics/strategies?${params}`,{cache:'no-store',signal:controller.signal});const body=await response.json();if(!response.ok){setState(response.status===403?'denied':'error');return;}const next=body.items??[];setItems(next);setState(next.length?'ready':'empty');if(initialStrategyId&&!selected){const match=next.find((item:HQStrategySummary)=>item.id===initialStrategyId);if(match)setSelected(match);}}catch(value){if((value as Error).name!=='AbortError')setState('error');}})();return()=>controller.abort();},[filters,initialStrategyId,selected]);
  function choose(item:HQStrategySummary){setSelected(item);setError('');router.replace(`/hq/system/strategy-compatibility?strategyId=${encodeURIComponent(item.id)}`,{scroll:false});}
  function inspectAdvanced(event:FormEvent){event.preventDefault();const id=advancedId.trim();if(!STRATEGY_UUID.test(id)){setError('Enter a valid strategy UUID.');return;}const item=items.find(candidate=>candidate.id===id);if(item)choose(item);else {setFilters({...emptyFilters,q:id});setError('');}}
  return <section className="card strategy-inspector"><div className="section-title"><div><span className="eyebrow">HQ STRATEGY ACCOUNTABILITY</span><h2>Strategy directory</h2><p className="muted">Operational summaries only. Private rule recipes, thresholds, notes and Copilot content are never displayed.</p></div></div>
    <div className="strategy-directory-filters"><input aria-label="Search strategy directory" placeholder="Search customer or strategy name" value={filters.q} onChange={event=>setFilters({...filters,q:event.target.value})}/><input aria-label="Customer filter" placeholder="Customer" value={filters.customer} onChange={event=>setFilters({...filters,customer:event.target.value})}/><input aria-label="Instrument filter" placeholder="Instrument" value={filters.instrument} onChange={event=>setFilters({...filters,instrument:event.target.value.toUpperCase()})}/><input aria-label="Methodology or category filter" placeholder="Methodology / category" value={filters.methodology} onChange={event=>setFilters({...filters,methodology:event.target.value})}/><select aria-label="Active status filter" value={filters.status} onChange={event=>setFilters({...filters,status:event.target.value})}><option value="">Any state</option><option>ACTIVE</option><option>INACTIVE</option><option>ARCHIVED</option></select><select aria-label="Engine version filter" value={filters.engineVersion} onChange={event=>setFilters({...filters,engineVersion:event.target.value})}><option value="">Any engine</option><option value="1">Engine v1</option><option value="2">Engine v2</option></select><select aria-label="Health filter" value={filters.health} onChange={event=>setFilters({...filters,health:event.target.value})}><option value="">Any health</option><option>HEALTHY</option><option>NEEDS_CONFIGURATION</option><option>ARCHIVED</option></select><input aria-label="Timeframe filter" placeholder="Timeframe" value={filters.timeframe} onChange={event=>setFilters({...filters,timeframe:event.target.value.toUpperCase()})}/></div>
    {state==='loading'&&<p className="muted" aria-live="polite">Loading strategy directory…</p>}{state==='empty'&&<p className="muted">No strategies match these filters.</p>}{state==='error'&&<p className="warning">The strategy directory could not be loaded. Please retry.</p>}{state==='denied'&&<p className="warning">You do not have permission to inspect strategies.</p>}
    {state==='ready'&&<div className="strategy-selector-options strategy-directory-list" role="listbox" aria-label="Strategy directory">{items.map(item=><button type="button" role="option" aria-selected={selected?.id===item.id} className={selected?.id===item.id?'selected':undefined} key={item.id} onClick={()=>choose(item)}><strong>{strategyOptionLabel(item)}</strong><small>{item.usage.analyses} analyses · {item.usage.decisions} decisions · {item.usage.tradesTaken} trades · {item.health.state}</small></button>)}</div>}
    <details className="strategy-inspector-advanced"><summary>Advanced · open by UUID</summary><form className="button-row" onSubmit={inspectAdvanced}><input aria-label="Strategy UUID" placeholder="Strategy UUID" value={advancedId} onChange={event=>setAdvancedId(event.target.value)}/><button type="submit">Open UUID</button></form></details>
    {error&&<p className="warning" role="alert">{error}</p>}
    {selected&&<div className="stack strategy-accountability-detail"><div><span className="eyebrow">SELECTED STRATEGY</span><h2>{selected.name}</h2><p className="muted">Customer → Strategies → {selected.name}</p></div><nav className="sales-subnav" aria-label="Strategy inspector sections"><a href="#strategy-overview">Overview</a><a href="#strategy-usage">Usage</a><a href="#strategy-health">Health</a><a href="#strategy-governance">Governance</a></nav><div className="grid grid-3">{detail(selected).map(([label,value])=><Metric key={label} label={label} value={value}/>)}</div><section id="strategy-governance" className="card"><h3>Governance boundary</h3><p className="muted">This HQ view intentionally excludes exact rules, values, logic trees, proprietary entry/exit formulas, private notes and Copilot conversations.</p></section></div>}
  </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="card metric"><span className="muted">{label}</span><strong>{value}</strong></div>}
