'use client';
import {useEffect,useState} from 'react';import Link from 'next/link';import {createClient} from '@/lib/supabase/client';
const human=(v:string)=>v.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()),date=(v?:string)=>v?new Date(v).toLocaleString():'Not recorded';
export default function SystemOperations({overview,incidents}:{overview:any;incidents:any[]}){const [health,setHealth]=useState<any>(null),[loading,setLoading]=useState(false),[rows,setRows]=useState(incidents),[message,setMessage]=useState('');async function refresh(){setLoading(true);const response=await fetch('/api/hq/health',{cache:'no-store'}),data=await response.json();setLoading(false);if(response.ok){setHealth(data);setMessage('')}else setMessage('Health data unavailable. Retry status refresh.')}useEffect(()=>{void refresh()},[]);async function action(id:number,status:string){const note=status==='RESOLVED'?prompt('Resolution summary')||'':null;if(status==='RESOLVED'&&!note)return;const {error}=await createClient().rpc('staff_incident_action',{p_incident_id:id,p_status:status,p_note:note});if(error){setMessage(error.message);return}setRows(x=>status==='RESOLVED'?x.filter(i=>i.id!==id):x.map(i=>i.id===id?{...i,status}:i));setMessage(`Incident ${human(status).toLowerCase()}.`)}
 const services=health?.services??{},monitored=Object.values(services) as any[],unavailable=monitored.filter(x=>x.status==='unavailable').length,degraded=monitored.filter(x=>x.status==='degraded').length,critical=Number(overview.criticalIncidents??0),major=Number(overview.majorIncidents??0),overall=critical||major?'Incident active':unavailable||degraded?'Degraded':health?(monitored.some(x=>x.status==='not_monitored')?'Partially monitored':'Healthy'):'Unknown';const actionable=rows.length+unavailable+degraded+(overview.failures?.length??0);
 return <div className="stack operations-v2"><header className="hq-section-heading"><div><span className="eyebrow">OPERATIONS</span><h1>Monitor platform health, customer activity, and operational exceptions.</h1></div><button onClick={refresh} disabled={loading}>{loading?'Refreshing…':'Refresh status'}</button></header><nav className="sales-subnav"><Link className="active" href="/hq/system">Overview</Link><Link href="/hq/system/queue">Action Queue</Link></nav>
 <section className="card operations-status"><div><span>Overall status</span><strong>{overall}</strong><small>Last health check: {date(health?.checkedAt)}</small></div>{[['Open incidents',overview.openIncidents],['Services degraded',unavailable+degraded],['Failed actions today',overview.failedActionsToday],['Customers needing attention',overview.customersNeedingAttention]].map(([k,v])=><div key={String(k)}><span>{k}</span><strong>{String(v??0)}</strong></div>)}</section>{message&&<p className="success">{message}</p>}
 <section className="card operations-queue"><div className="section-title"><div><span className="eyebrow">ACTION FIRST</span><h2>Operations Action Queue</h2><p className="muted">{actionable} actionable · {critical} critical · {degraded} degraded</p></div><Link href="/hq/system/queue">View full operations queue</Link></div>{rows.length?rows.slice(0,8).map(i=><article className="operations-row" key={i.id}><span className={`status-pill ${i.severity==='CRITICAL'?'warning':''}`}>{i.severity}</span><div><strong>{i.message||i.public_code}</strong><small>{i.category||'Internal Application'} · {i.provider||i.endpoint||'Internal'} · Last detected {date(i.last_detected_at||i.created_at)} · {i.occurrence_count||1} occurrence(s)</small></div><div className="button-row"><button onClick={()=>action(i.id,'INVESTIGATING')}>Investigate</button><button onClick={()=>action(i.id,'MONITORING')}>Monitor</button><button onClick={()=>action(i.id,'RESOLVED')}>Resolve</button></div></article>):<div className="empty-state"><strong>No operational actions are currently due.</strong></div>}</section>
 <section className="card"><div className="section-title"><div><span className="eyebrow">LIVE SERVICES</span><h2>Service health</h2></div></div><div className="service-health-list">{Object.entries(services).map(([name,s]:any)=><div key={name}><span className={`status-dot ${s.status==='operational'?'healthy':''}`}/><strong>{human(name)}</strong><span>{human(s.status)}</span><small>{s.latencyMs!=null?`${s.latencyMs} ms · `:''}{s.message}</small></div>)}</div>{!health&&<p className="muted">Service health has not been checked yet.</p>}</section>
 <section className="grid grid-4 operations-metrics">{[['Analyses today',overview.analysesToday],['Authorizations today',overview.authorizationsToday],['Blocked today',overview.blockedToday],['Active monitored trades',overview.activeTrades],['Strategies created',overview.strategiesCreatedToday]].map(([k,v])=><div className="card" key={String(k)}><span>{k}</span><strong>{String(v??0)}</strong></div>)}</section>
 <section className="grid grid-2"><section className="card"><h2>Customers Needing Operational Attention</h2>{(overview.customers??[]).length?(overview.customers??[]).map((c:any)=><div className="event-row" key={c.id}><div><strong>{c.display_name||c.email}</strong><small>{c.issue} · Last activity {date(c.last_activity_at)}</small></div><Link href={`/hq/customers/${c.id}`}>Open customer</Link></div>):<p className="muted">No customers currently require operational attention.</p>}</section><section className="card"><h2>Failures and Exceptions</h2>{(overview.failures??[]).length?(overview.failures??[]).map((f:any)=><div className="event-row" key={f.failure_type}><div><strong>{human(f.failure_type)}</strong><small>{f.affected_users} affected customers · Last seen {date(f.last_seen)}</small></div><strong>{f.count}</strong></div>):<p className="muted">No repeated failures detected.</p>}</section></section>
 <section className="grid grid-3"><Ranking title="Most analyzed instruments" rows={overview.topInstruments??[]}/><Ranking title="Most active customers" rows={overview.topCustomers??[]} customer/><Ranking title="Feature usage · 30 days" rows={overview.featureUsage??[]}/></section></div>}
function Ranking({title,rows,customer=false}:{title:string;rows:any[];customer?:boolean}){return <section className="card"><h2>{title}</h2>{rows.length?rows.map((r:any)=><div className="event-row" key={r.id||r.name}><div><strong>{customer?r.display_name||r.email:human(r.name||'Unknown')}</strong>{customer&&<small>{r.email}</small>}</div><span>{r.count}</span></div>):<p className="muted">No activity recorded.</p>}</section>}
