'use client';
import Link from 'next/link';
import {FormEvent,useEffect,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type Person={user_id:string;email:string;display_name:string|null;display_title:string|null;role:string;department:string|null;is_active:boolean;mfa_required:boolean;last_active_at:string|null;invitation_status:string};
type Invite={id:string;user_id:string;name:string;email:string;role:string;title:string|null;department:string|null;sent:string;expires:string;status:string};
type Workspace={summary:Record<string,number>;invitations:Invite[];staff:Person[];total:number;page:number;pageSize:number;departments:string[];roles:{role:string;users:number;permissions:number}[];permissionMatrix:{key:string;description:string;roles:string[]}[];activity:{who:string;action:string;target:string;result:string;created_at:string}[];organization:{id:string;name:string;status:string}|null};
const roleLabel=(value:string)=>({OWNER:'Owner',SECURITY_ADMIN:'Admin',TECHNICIAN:'Operations',COMPLIANCE_OFFICER:'Compliance',HEAD_OF_SALES:'Sales',SUPPORT:'Support'}[value]??value.replaceAll('_',' '));
const roles=['OWNER','SECURITY_ADMIN','TECHNICIAN','COMPLIANCE_OFFICER','HEAD_OF_SALES','SUPPORT'];

export default function TeamWorkspace({initialData,initialError,canManage}:{initialData:Workspace|null;initialError:string|null;canManage:boolean}){
 const [data,setData]=useState(initialData);const [error,setError]=useState(initialError);const [drawer,setDrawer]=useState(false);const [busy,setBusy]=useState(false);const [notice,setNotice]=useState('');
 const [query,setQuery]=useState('');const [role,setRole]=useState('ALL');const [department,setDepartment]=useState('ALL');const [status,setStatus]=useState('ALL');const [page,setPage]=useState(1);
 useEffect(()=>{if(!drawer)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setDrawer(false)};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key)},[drawer]);
 async function load(nextPage=page){setBusy(true);setError(null);const {data:result,error:rpcError}=await createClient().rpc('staff_team_workspace_v2',{p_query:query,p_page:nextPage,p_page_size:25,p_role:role,p_department:department,p_status:status});setBusy(false);if(rpcError)setError('Team workspace data could not be loaded.');else{setData(result);setPage(nextPage)}}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice('');const fd=new FormData(e.currentTarget);const response=await fetch('/api/hq/staff/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(fd))});const result=await response.json();setBusy(false);if(!response.ok){setNotice(result.error||'Invitation failed.');return}setDrawer(false);setNotice(result.message);await load(1)}
 async function invitationAction(row:Invite,action:'resend'|'cancel'){setBusy(true);const response=await fetch('/api/hq/staff/invite',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({invitationId:row.id,action})});const result=await response.json();setBusy(false);setNotice(response.ok?result.message:result.error);if(response.ok)await load()}
 async function toggle(row:Person){setBusy(true);const {error:e}=await createClient().rpc('owner_set_staff_active',{p_user_id:row.user_id,p_active:!row.is_active});setBusy(false);setNotice(e?e.message:row.is_active?'Employee disabled.':'Employee enabled.');if(!e)await load()}
 if(error&&!data)return <section className="card empty-state"><strong>Team workspace could not be loaded.</strong><span>{error}</span><button onClick={()=>void load(1)}>Retry</button></section>;
 const summary=data?.summary??{};const totalPages=Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??25)));
 return <div className="stack team-workspace">
  <header className="card directory-page-header"><div><span className="eyebrow">PEOPLE, ROLES & ACCESS</span><h1>Team workspace</h1><p className="muted">Manage Trade Police employees, access, and security. Customer identities are excluded.</p></div><div className="team-header-actions">{canManage&&<button className="primary" onClick={()=>setDrawer(true)}>Invite employee</button>}<a className="button-link secondary" href="#roles">Manage roles</a><a className="button-link secondary" href="#audit">Audit log</a></div></header>
  {notice&&<div className="warning">{notice}</div>}
  <section className="team-summary-grid">{[['Employees','employees'],['Pending invitations','pendingInvitations'],['Active this week','activeThisWeek'],['Owners/Admins','ownersAdmins'],['Custom roles','customRoles'],['Disabled accounts','disabledAccounts']].map(([label,key])=><div className="card team-kpi" key={key}><span>{label}</span><strong>{summary[key]??0}</strong></div>)}</section>
  <section className="card"><div className="section-title"><div><span className="eyebrow">INVITATIONS</span><h2>Pending invitations</h2></div></div>{!data?.invitations.length?<p className="muted">No pending invitations.</p>:<div className="table-wrap"><table className="team-table"><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Sent</th><th>Expires</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data.invitations.map(row=><tr key={row.id}><td>{row.name}</td><td>{row.email}</td><td>{roleLabel(row.role)}</td><td>{new Date(row.sent).toLocaleDateString()}</td><td>{new Date(row.expires).toLocaleDateString()}</td><td><span className="status-pill warning">{row.status}</span></td><td><div className="compact-actions">{canManage&&<><button onClick={()=>void invitationAction(row,'resend')} disabled={busy}>Resend</button><button onClick={()=>void invitationAction(row,'cancel')} disabled={busy}>Cancel</button></>}<button onClick={()=>void navigator.clipboard.writeText(`${location.origin}/hq/login?email=${encodeURIComponent(row.email)}`)}>Copy invitation</button></div></td></tr>)}</tbody></table></div>}</section>
  <section className="card team-directory"><div className="section-title"><div><span className="eyebrow">TEAM DIRECTORY</span><h2>Employees</h2></div><span className="muted">{data?.total??0} permitted records</span></div><form className="directory-filter-row" onSubmit={e=>{e.preventDefault();void load(1)}}><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, title"/></label><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option value="ALL">All roles</option>{roles.map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select></label><label>Department<select value={department} onChange={e=>setDepartment(e.target.value)}><option value="ALL">All departments</option>{data?.departments.map(d=><option key={d}>{d}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option><option value="INVITED">Invited</option></select></label><button disabled={busy}>Apply</button></form>
   {!data?.staff.length?<p className="muted">No employees yet.</p>:<><div className="table-wrap team-desktop-directory"><table className="team-table"><thead><tr><th>Employee</th><th>Title</th><th>Role</th><th>Department</th><th>Status</th><th>Last active</th><th>2FA</th><th>Actions</th></tr></thead><tbody>{data.staff.map(row=><tr key={row.user_id}><td><strong>{row.display_name||row.email}</strong><small>{row.email}</small></td><td>{row.display_title||'—'}</td><td>{roleLabel(row.role)}</td><td>{row.department||'—'}</td><td><span className={`status-pill ${row.is_active?'healthy':'warning'}`}>{row.is_active?'ACTIVE':'DISABLED'}</span></td><td>{row.last_active_at?new Date(row.last_active_at).toLocaleString():'No activity yet'}</td><td>{row.mfa_required?'Required':'Optional'}</td><td><div className="compact-actions"><Link href={`/hq/team/${row.user_id}`}>Open profile</Link>{canManage&&row.role!=='OWNER'&&<button onClick={()=>void toggle(row)} disabled={busy}>{row.is_active?'Disable':'Enable'}</button>}</div></td></tr>)}</tbody></table></div><div className="team-mobile-directory">{data.staff.map(row=><article className="directory-mobile-card" key={row.user_id}><div className="directory-mobile-head"><strong>{row.display_name||row.email}</strong><span className={`status-pill ${row.is_active?'healthy':'warning'}`}>{row.is_active?'ACTIVE':'DISABLED'}</span></div><small>{row.email}</small><dl><div><dt>Title</dt><dd>{row.display_title||'—'}</dd></div><div><dt>Role</dt><dd>{roleLabel(row.role)}</dd></div><div><dt>Department</dt><dd>{row.department||'—'}</dd></div><div><dt>2FA</dt><dd>{row.mfa_required?'Required':'Optional'}</dd></div></dl><Link className="button-link secondary" href={`/hq/team/${row.user_id}`}>Open profile</Link></article>)}</div></>}
   <div className="directory-pagination"><button disabled={page<=1||busy} onClick={()=>void load(page-1)}>Previous</button><span>Page {page} of {totalPages}</span><button disabled={page>=totalPages||busy} onClick={()=>void load(page+1)}>Next</button></div>
  </section>
  <section id="roles" className="card"><div className="section-title"><div><span className="eyebrow">ROLES & PERMISSIONS</span><h2>Access model</h2></div><span className="muted">Read-only role defaults</span></div><div className="team-role-grid">{data?.roles.map(r=><article key={r.role}><strong>{roleLabel(r.role)}</strong><span>{r.users} users</span><small>{r.permissions} permissions</small></article>)}</div><div className="table-wrap"><table className="team-table permission-matrix"><thead><tr><th>Permission</th>{roles.map(r=><th key={r}>{roleLabel(r)}</th>)}</tr></thead><tbody>{data?.permissionMatrix.map(p=><tr key={p.key}><td><strong>{p.key}</strong><small>{p.description}</small></td>{roles.map(r=><td key={r}>{p.roles.includes(r)?'✓':'—'}</td>)}</tr>)}</tbody></table></div></section>
  <div className="grid grid-2"><section className="card"><span className="eyebrow">RECENT STAFF ACTIVITY</span><h2>Access changes</h2>{!data?.activity.length?<p className="muted">No recent staff activity.</p>:data.activity.slice(0,8).map((a,i)=><div className="event-row" key={i}><span><strong>{a.action.replaceAll('_',' ')}</strong><small>{a.who} · {a.target}</small></span><time>{new Date(a.created_at).toLocaleString()}</time></div>)}</section><section id="audit" className="card"><span className="eyebrow">ACCESS AUDIT</span><h2>Security evidence</h2>{!data?.activity.length?<p className="muted">No access audit events.</p>:data.activity.map((a,i)=><div className="event-row" key={i}><span>{a.who}<small>{a.action.replaceAll('_',' ')} · {a.target}</small></span><strong>{a.result}</strong></div>)}</section></div>
  <section className="card"><span className="eyebrow">ORGANIZATION SETTINGS</span><h2>{data?.organization?.name||'Organization not configured'}</h2>{data?.organization&&<div className="settings-list"><div className="event-row"><span>Status</span><strong>{data.organization.status}</strong></div></div>}<p className="muted">Only persisted organization settings are shown.</p></section>
  {drawer&&<div className="sales-drawer-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setDrawer(false)}}><aside className="team-invite-drawer" role="dialog" aria-modal="true" aria-label="Invite employee"><div className="section-title"><div><span className="eyebrow">TEAM ACCESS</span><h2>Invite employee</h2></div><button onClick={()=>setDrawer(false)}>Close</button></div><form className="stack" onSubmit={invite}><label>Name<input name="displayName" required/></label><label>Email<input name="email" type="email" required/></label><label>Starting role<select name="role" required defaultValue="HEAD_OF_SALES">{roles.filter(r=>r!=='OWNER').map(r=><option key={r} value={r}>{roleLabel(r)}</option>)}</select></label><label>Display title<input name="title" required/></label><label>Department (optional)<input name="department"/></label><label>Manager (optional)<select name="managerUserId" defaultValue=""><option value="">No manager assigned</option>{data?.staff.filter(s=>s.is_active).map(s=><option key={s.user_id} value={s.user_id}>{s.display_name||s.email}</option>)}</select></label><div className="compact-actions"><button className="primary" disabled={busy}>{busy?'Sending…':'Send invitation'}</button><button type="button" onClick={()=>setDrawer(false)}>Cancel</button></div></form></aside></div>}
 </div>
}
