'use client';
import Link from 'next/link';
import {FormEvent,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {buildOrgForest,positionsForDepartment,prioritizeManagers,type ManagerOption,type OrgNode} from '@/lib/organizational-structure';

type Department={id:string;name:string;description:string|null;active:boolean;headEmployeeId:string|null;headName:string|null;employeeCount:number};
type Position={id:string;title:string;departmentId:string;description:string|null;managementLevel:number;active:boolean};
type Profile={id:string;name:string;description:string|null;roleKey:string;active:boolean};
type Person={user_id:string;email:string;display_name:string|null;is_active:boolean;department_id:string|null;department:string|null;position_id:string|null;position:string|null;permission_profile_id:string|null;permission_profile:string|null;reports_to_employee_id:string|null;manager_name:string|null;direct_reports_count:number};
type Activity={who:string;action:string;target:string;result:string;created_at:string};
type Workspace={summary:Record<string,number>;staff:Person[];total:number;page:number;pageSize:number;departments:Department[];positions:Position[];permissionProfiles:Profile[];managers:ManagerOption[];orgChart:Array<{id:string;name:string;position:string|null;department:string|null;reportsTo:string|null;directReports:number}>;activity:Activity[]};

export default function TeamWorkspace({initialData,initialError,canManage}:{initialData:Workspace|null;initialError:string|null;canManage:boolean}){
 const [data,setData]=useState(initialData);const [error,setError]=useState(initialError);const [notice,setNotice]=useState('');const [busy,setBusy]=useState(false);const [drawer,setDrawer]=useState<'EMPLOYEE'|'DEPARTMENT'|'POSITION'|null>(null);const [editingDepartment,setEditingDepartment]=useState<Department|null>(null);
 const [query,setQuery]=useState('');const [department,setDepartment]=useState('ALL');const [position,setPosition]=useState('ALL');const [manager,setManager]=useState('ALL');const [status,setStatus]=useState('ALL');const [page,setPage]=useState(1);const [formDepartment,setFormDepartment]=useState('');
 async function load(nextPage=page){setBusy(true);const {data:result,error:e}=await createClient().rpc('staff_team_workspace_v3',{p_query:query,p_page:nextPage,p_page_size:25,p_department_id:department,p_position_id:position,p_manager_id:manager,p_status:status});setBusy(false);if(e)setError(e.message);else{setData(result);setPage(nextPage);setError(null)}}
 async function invite(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const response=await fetch('/api/hq/staff/invite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))});const result=await response.json();setBusy(false);setNotice(response.ok?result.message:result.error);if(response.ok){setDrawer(null);await load(1)}}
 async function saveDepartment(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);const {error:e2}=await createClient().rpc('manage_department_v1',{p_department_id:editingDepartment?.id??null,p_name:fd.get('name'),p_description:fd.get('description'),p_head_employee_id:fd.get('headEmployeeId')||null,p_active:true});setBusy(false);setNotice(e2?e2.message:editingDepartment?'Department updated.':'Department created.');if(!e2){setDrawer(null);setEditingDepartment(null);await load(1)}}
 async function archiveDepartment(item:Department){if(item.employeeCount>0){setNotice('Only an unused department can be archived.');return}setBusy(true);const {error:e}=await createClient().rpc('manage_department_v1',{p_department_id:item.id,p_name:item.name,p_description:item.description,p_head_employee_id:null,p_active:false});setBusy(false);setNotice(e?e.message:'Department archived.');if(!e)await load()}
 async function savePosition(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);const {error:e2}=await createClient().rpc('manage_position_v1',{p_position_id:null,p_department_id:fd.get('departmentId'),p_title:fd.get('title'),p_description:fd.get('description'),p_management_level:Number(fd.get('managementLevel')),p_active:true});setBusy(false);setNotice(e2?e2.message:'Position created.');if(!e2){setDrawer(null);await load(1)}}
 async function toggle(row:Person){let replacement:string|null=null;if(row.is_active&&row.direct_reports_count>0){replacement=window.prompt(`Reassign ${row.direct_reports_count} direct report(s) to active employee ID:`);if(!replacement){setNotice('Reassignment is required before this manager can be disabled.');return}}setBusy(true);const {error:e}=await createClient().rpc('set_staff_active_v3',{p_employee_id:row.user_id,p_active:!row.is_active,p_reassign_reports_to:replacement});setBusy(false);setNotice(e?e.message:row.is_active?'Employee disabled.':'Employee enabled.');if(!e)await load()}
 const availablePositions=positionsForDepartment(data?.positions??[],formDepartment);const managerOptions=prioritizeManagers(data?.managers??[],formDepartment);const forest=useMemo(()=>buildOrgForest(data?.orgChart??[]),[data?.orgChart]);const totalPages=Math.max(1,Math.ceil((data?.total??0)/(data?.pageSize??25)));
 if(error&&!data)return <section className="card empty-state"><strong>Team workspace could not be loaded.</strong><span>{error}</span><button onClick={()=>void load(1)}>Retry</button></section>;
 return <div className="stack team-workspace"><header className="card directory-page-header"><div><span className="eyebrow">ORGANIZATION & ACCESS</span><h1>Team workspace</h1><p className="muted">Departments, positions, reporting lines, and permission profiles remain independent.</p></div>{canManage&&<div className="team-header-actions"><button className="primary" onClick={()=>setDrawer('EMPLOYEE')}>Invite employee</button><button onClick={()=>{setEditingDepartment(null);setDrawer('DEPARTMENT')}}>New department</button><button onClick={()=>setDrawer('POSITION')}>New position</button></div>}</header>
 {notice&&<p className="warning">{notice}</p>}<section className="team-summary-grid">{[['Employees','employees'],['Active','activeEmployees'],['Departments','departments'],['Managers','managers'],['Disabled','disabledAccounts']].map(([label,key])=><div className="card team-kpi" key={key}><span>{label}</span><strong>{data?.summary[key]??0}</strong></div>)}</section>
 <section className="card team-directory"><div className="section-title"><div><span className="eyebrow">TEAM DIRECTORY</span><h2>Employees</h2></div><span className="muted">{data?.total??0} records</span></div><form className="directory-filter-row" onSubmit={e=>{e.preventDefault();void load(1)}}><label>Search<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Name, email, position"/></label><label>Department<select value={department} onChange={e=>{setDepartment(e.target.value);setPosition('ALL')}}><option value="ALL">All departments</option>{data?.departments.filter(d=>d.active).map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Position<select value={position} onChange={e=>setPosition(e.target.value)}><option value="ALL">All positions</option>{data?.positions.filter(p=>p.active&&(department==='ALL'||p.departmentId===department)).map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Manager<select value={manager} onChange={e=>setManager(e.target.value)}><option value="ALL">All managers</option><option value="NONE">No manager</option>{data?.managers.map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>Status<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="DISABLED">Disabled</option><option value="INVITED">Invited</option></select></label><button disabled={busy}>Apply</button></form>
 <div className="table-wrap"><table className="team-table"><thead><tr><th>Employee</th><th>Department</th><th>Position</th><th>Permission profile</th><th>Reports To</th><th>Direct Reports</th><th>Status</th><th>Actions</th></tr></thead><tbody>{data?.staff.map(row=><tr key={row.user_id}><td><strong>{row.display_name||row.email}</strong><small>{row.email}</small></td><td>{row.department||'—'}</td><td>{row.position||'—'}</td><td>{row.permission_profile||'—'}</td><td>{row.manager_name||'—'}</td><td>{row.direct_reports_count}</td><td><span className={`status-pill ${row.is_active?'healthy':'warning'}`}>{row.is_active?'ACTIVE':'DISABLED'}</span></td><td><div className="compact-actions"><Link href={`/hq/team/${row.user_id}`}>Open profile</Link>{canManage&&<button disabled={busy} onClick={()=>void toggle(row)}>{row.is_active?'Disable':'Enable'}</button>}</div></td></tr>)}</tbody></table></div><div className="directory-pagination"><button disabled={page<=1||busy} onClick={()=>void load(page-1)}>Previous</button><span>Page {page} of {totalPages}</span><button disabled={page>=totalPages||busy} onClick={()=>void load(page+1)}>Next</button></div></section>
 <div className="grid grid-2"><section className="card"><span className="eyebrow">DEPARTMENTS</span><h2>Organization units</h2>{data?.departments.map(d=><div className="event-row" key={d.id}><span><strong>{d.name}</strong><small>{d.headName?`Head: ${d.headName}`:'No department head'} · {d.employeeCount} employees</small></span><div className="compact-actions"><span className={`status-pill ${d.active?'healthy':'warning'}`}>{d.active?'ACTIVE':'ARCHIVED'}</span>{canManage&&d.active&&<><button onClick={()=>{setEditingDepartment(d);setDrawer('DEPARTMENT')}}>Edit</button><button disabled={d.employeeCount>0} onClick={()=>void archiveDepartment(d)}>Archive</button></>}</div></div>)}</section><section className="card"><span className="eyebrow">ORGANIZATION CHART</span><h2>Reporting hierarchy</h2><div className="org-chart">{forest.map(node=><OrgBranch node={node} key={node.id}/>)}</div></section></div>
 <section className="card"><span className="eyebrow">AUDIT LOG</span><h2>Organization changes</h2>{data?.activity.map((a,i)=><div className="event-row" key={i}><span><strong>{a.action.replaceAll('_',' ')}</strong><small>{a.who} · {a.target}</small></span><time>{new Date(a.created_at).toLocaleString()}</time></div>)}</section>
 {drawer&&<div className="manual-confirmation-backdrop"><aside className="team-invite-drawer"><header><div><span className="eyebrow">ORGANIZATION</span><h2>{drawer==='EMPLOYEE'?'Invite employee':drawer==='DEPARTMENT'?(editingDepartment?'Edit department':'Create department'):'Create position'}</h2></div><button onClick={()=>{setDrawer(null);setEditingDepartment(null)}}>×</button></header>{drawer==='EMPLOYEE'?<form className="stack manual-confirmation-list" onSubmit={invite}><label>Name<input name="displayName" required/></label><label>Email<input name="email" type="email" required/></label><label>Department<select name="departmentId" required value={formDepartment} onChange={e=>setFormDepartment(e.target.value)}><option value="">Select department</option>{data?.departments.filter(d=>d.active).map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Position<select name="positionId" required disabled={!formDepartment}><option value="">Select position</option>{availablePositions.map(p=><option value={p.id} key={p.id}>{p.title}</option>)}</select></label><label>Permission profile<select name="permissionProfileId" required><option value="">Select permission profile</option>{data?.permissionProfiles.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><label>Reports To<select name="reportsToEmployeeId"><option value="">No manager</option>{managerOptions.map(m=><option value={m.id} key={m.id}>{m.name} — {m.position||'No position'} · {m.department||'No department'}</option>)}</select></label><button className="primary" disabled={busy}>Send invitation</button></form>:drawer==='DEPARTMENT'?<form className="stack manual-confirmation-list" onSubmit={saveDepartment}><label>Name<input name="name" required defaultValue={editingDepartment?.name}/></label><label>Description<textarea name="description" defaultValue={editingDepartment?.description??''}/></label><label>Department head<select name="headEmployeeId" defaultValue={editingDepartment?.headEmployeeId??''}><option value="">Unassigned</option>{data?.managers.map(m=><option value={m.id} key={m.id}>{m.name} — {m.position||'No position'}</option>)}</select></label><button className="primary" disabled={busy}>{editingDepartment?'Save department':'Create department'}</button></form>:<form className="stack manual-confirmation-list" onSubmit={savePosition}><label>Department<select name="departmentId" required><option value="">Select department</option>{data?.departments.filter(d=>d.active).map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><label>Title<input name="title" required/></label><label>Description<textarea name="description"/></label><label>Management level<input name="managementLevel" type="number" min="0" max="20" defaultValue="0" required/></label><button className="primary" disabled={busy}>Create position</button></form>}</aside></div>}
 </div>
}
function OrgBranch({node}:{node:OrgNode}){return <div className="org-branch"><div><strong>{node.name}</strong><small>{node.position||'No position'}{node.department?` · ${node.department}`:''}</small></div>{node.children.length>0&&<div>{node.children.map(child=><OrgBranch node={child} key={child.id}/>)}</div>}</div>}
