import type { ConfidenceAssessment } from '../confidence/confidence-types.ts';
import type { EvidenceGraph } from '../evidence-graph/evidence-graph-types.ts';
import { EvidenceGraphValidator } from '../evidence-graph/evidence-graph-validator.ts';
import type { ReadinessAssessment } from '../readiness/readiness-types.ts';
import { stableFingerprint } from '../serialization/stable-fingerprint.ts';
import type { StrategyContext } from '../strategy-composition/composition-types.ts';
import type { CompiledStrategyDefinition } from '../strategy-definitions/strategy-definition-types.ts';
import { DecisionPolicyValidator } from './decision-policy-validator.ts';
import type { DecisionAssessment, DecisionCriterionId, DecisionCriterionResult, DecisionOutcome, DecisionPolicy, DecisionSeverity, DecisionStatus } from './decision-types.ts';

export const DECISION_ENGINE_VERSION = '1.0.0' as const;
const names: Record<DecisionCriterionId, string> = { 'upstream-validity': 'Upstream validity', 'readiness-status': 'Readiness status', 'confidence-threshold': 'Confidence threshold', 'coverage-threshold': 'Coverage threshold', 'failed-required-rules': 'Failed required rules', 'unavailable-required-rules': 'Unavailable required rules', 'rule-errors': 'Rule errors', 'partial-confidence': 'Partial confidence', warnings: 'Warning policy', 'maximum-warnings': 'Maximum warnings', 'minimum-matched-rules': 'Minimum matched rules' };
const unique = <T>(values: readonly T[]): T[] => [...new Set(values)];
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
export function createDecisionAssessmentId(d: CompiledStrategyDefinition, s: StrategyContext, g: EvidenceGraph, c: ConfidenceAssessment, r: ReadinessAssessment, p: DecisionPolicy): string { return `decision:${stableFingerprint({ compiledStrategyId: d.compiledStrategyId, strategyContextId: s.contextId, evidenceGraphId: g.graphId, confidenceAssessmentId: c.assessmentId, readinessAssessmentId: r.assessmentId, policyFingerprint: stableFingerprint(p), requestedAt: s.executionTimestamp, engineVersion: DECISION_ENGINE_VERSION })}`; }

export class DecisionEngine {
  assess(d: CompiledStrategyDefinition, s: StrategyContext, g: EvidenceGraph, c: ConfidenceAssessment, r: ReadinessAssessment, p: DecisionPolicy): DecisionAssessment {
    const bad = this.inputError(d, s, g, c, r, p); if (bad) return this.error(d, s, g, c, r, p, bad);
    const failedReq = r.failedRequiredRuleIds, unavailableReq = r.unavailableRequiredRuleIds, errorIds = r.errorRuleIds;
    const failedOptionalCount = s.ruleResults.filter((result) => d.ruleRequirements?.[result.ruleId] !== 'REQUIRED' && result.status === 'FAILED').length;
    const warningCount = r.warningCriterionIds.length + r.warnings.length + failedOptionalCount;
    const evidence = (ids: string[]) => unique(c.contributions.filter((x) => ids.includes(x.ruleId)).flatMap((x) => x.evidenceNodeIds));
    const readinessEvidence = (ids: string[]) => unique(r.criteria.filter((x) => ids.includes(x.criterionId)).flatMap((x) => x.relatedEvidenceNodeIds));
    const criterion = (id: DecisionCriterionId, order: number, status: DecisionCriterionResult['status'], severity: DecisionSeverity, actualValue: DecisionCriterionResult['actualValue'], expectedValue: DecisionCriterionResult['expectedValue'], comparisonOperator: DecisionCriterionResult['comparisonOperator'], explanation: string, rules: string[] = [], readinessIds: string[] = []): DecisionCriterionResult => ({ criterionId: id, name: names[id], order, status, severity, actualValue, expectedValue, comparisonOperator, passed: status === 'PASSED', explanation, relatedRuleIds: rules, relatedReadinessCriterionIds: readinessIds, relatedEvidenceNodeIds: unique([...evidence(rules), ...readinessEvidence(readinessIds)]), warnings: [] });
    const evaluate = (id: DecisionCriterionId, order: number): DecisionCriterionResult => {
      if (id === 'upstream-validity') return criterion(id, order, 'PASSED', 'BLOCKING', true, true, 'VALID', 'All mandatory upstream validation passed.');
      if (id === 'readiness-status') { const pass = p.requiredReadinessStatuses.includes(r.status); const severity: DecisionSeverity = r.status === 'READY' ? (pass ? 'INFO' : 'BLOCKING') : 'WARNING'; return criterion(id, order, pass ? 'PASSED' : 'FAILED', severity, r.status, p.requiredReadinessStatuses, 'IN', `Readiness status ${r.status} is authoritative.`, [], r.failedCriterionIds); }
      if (id === 'confidence-threshold') return p.minimumConfidencePercent === undefined ? criterion(id, order, 'NOT_EVALUATED', 'INFO', c.confidencePercent, null, '>=', 'No threshold configured.') : c.confidencePercent === null ? criterion(id, order, 'NOT_EVALUATED', 'WARNING', null, p.minimumConfidencePercent, '>=', 'Confidence unavailable.') : criterion(id, order, c.confidencePercent >= p.minimumConfidencePercent ? 'PASSED' : 'FAILED', 'WARNING', c.confidencePercent, p.minimumConfidencePercent, '>=', 'Confidence threshold comparison.');
      if (id === 'coverage-threshold') return p.minimumCoveragePercent === undefined ? criterion(id, order, 'NOT_EVALUATED', 'INFO', c.configuredCoveragePercent, null, '>=', 'No threshold configured.') : c.configuredCoveragePercent === null ? criterion(id, order, 'NOT_EVALUATED', 'WARNING', null, p.minimumCoveragePercent, '>=', 'Coverage unavailable.') : criterion(id, order, c.configuredCoveragePercent >= p.minimumCoveragePercent ? 'PASSED' : 'FAILED', 'WARNING', c.configuredCoveragePercent, p.minimumCoveragePercent, '>=', 'Coverage threshold comparison.');
      if (id === 'failed-required-rules') return criterion(id, order, failedReq.length ? 'FAILED' : 'PASSED', p.blockOnFailedRequiredRules ? 'BLOCKING' : 'WARNING', failedReq.length, 0, 'NONE', 'Failed required rules follow policy.', failedReq);
      if (id === 'unavailable-required-rules') return criterion(id, order, unavailableReq.length ? 'FAILED' : 'PASSED', p.blockOnUnavailableRequiredRules ? 'BLOCKING' : 'WARNING', unavailableReq.length, 0, 'NONE', 'Unavailable required rules follow policy.', unavailableReq);
      if (id === 'rule-errors') return criterion(id, order, errorIds.length ? 'FAILED' : 'PASSED', p.blockOnRuleErrors ? 'BLOCKING' : 'WARNING', errorIds.length, 0, 'NONE', 'Rule errors follow policy.', errorIds);
      if (id === 'partial-confidence') { const pass = c.status !== 'PARTIAL' || p.allowPartialConfidence; return criterion(id, order, pass ? 'PASSED' : 'FAILED', 'WARNING', c.status, p.allowPartialConfidence, 'ALLOWED', 'Partial-confidence policy.'); }
      if (id === 'warnings') { const pass = p.allowWarnings || warningCount === 0; return criterion(id, order, pass ? 'PASSED' : 'FAILED', 'WARNING', warningCount, p.allowWarnings, 'ALLOWED', 'Material-warning policy.'); }
      if (id === 'maximum-warnings') return p.maximumWarningCount === undefined ? criterion(id, order, 'NOT_EVALUATED', 'INFO', warningCount, null, '<=', 'No maximum configured.') : criterion(id, order, warningCount <= p.maximumWarningCount ? 'PASSED' : 'FAILED', 'WARNING', warningCount, p.maximumWarningCount, '<=', 'Warning maximum comparison.');
      return p.minimumMatchedRuleCount === undefined ? criterion(id, order, 'NOT_EVALUATED', 'INFO', r.matchedRuleCount, null, '>=', 'No minimum configured.') : criterion(id, order, r.matchedRuleCount >= p.minimumMatchedRuleCount ? 'PASSED' : 'FAILED', 'WARNING', r.matchedRuleCount, p.minimumMatchedRuleCount, '>=', 'Matched-rule minimum comparison.');
    };
    const criteria = p.criteriaOrder.map(evaluate), failed = criteria.filter((x) => x.status === 'FAILED'), blocking = failed.filter((x) => x.severity === 'BLOCKING'), warning = failed.filter((x) => x.severity === 'WARNING');
    let status: DecisionStatus, outcome: DecisionOutcome;
    if (r.status === 'ERROR' || (c.status === 'ERROR' && p.requireConfidenceAssessmentValid)) { status = 'ERROR'; outcome = 'ERROR'; }
    else if (r.status === 'UNAVAILABLE' || c.status === 'UNAVAILABLE' || c.confidencePercent === null || c.configuredCoveragePercent === null) { status = 'UNAVAILABLE'; outcome = 'UNAVAILABLE'; }
    else if (r.status === 'BLOCKED' || blocking.length) { status = 'BLOCKED'; outcome = 'BLOCKED'; }
    else if (r.status === 'WAIT' || (p.requiredReadinessStatuses.includes('WAIT') && warningCount > 0)) { status = 'DEFERRED'; outcome = 'DEFER'; }
    else if (failed.length) { status = 'DECIDED'; outcome = 'NO_ACTION'; }
    else { status = 'DECIDED'; outcome = 'ACTIONABLE'; }
    return deepFreeze({ assessmentId: createDecisionAssessmentId(d, s, g, c, r, p), version: '1.0.0', engineVersion: DECISION_ENGINE_VERSION, policyId: p.id, policyVersion: p.version, strategyId: d.id, strategyVersion: d.version, compiledStrategyId: d.compiledStrategyId, marketContextId: g.marketContextId, strategyContextId: s.contextId, evidenceGraphId: g.graphId, confidenceAssessmentId: c.assessmentId, readinessAssessmentId: r.assessmentId, generatedAt: s.executionTimestamp, status, outcome, actionable: outcome === 'ACTIONABLE', criteria, failedCriterionIds: failed.map((x) => x.criterionId), blockingCriterionIds: blocking.map((x) => x.criterionId), warningCriterionIds: warning.map((x) => x.criterionId), failedRequiredRuleIds: [...failedReq], unavailableRequiredRuleIds: [...unavailableReq], errorRuleIds: [...errorIds], matchedRuleCount: r.matchedRuleCount, confidencePercent: c.confidencePercent, coveragePercent: c.configuredCoveragePercent, summary: { totalCriteria: criteria.length, passedCriteria: criteria.filter((x) => x.status === 'PASSED').length, failedCriteria: failed.length, notEvaluatedCriteria: criteria.filter((x) => x.status === 'NOT_EVALUATED').length, errorCriteria: 0, blockingFailures: blocking.length, warningFailures: warning.length, meaning: 'ACTIONABILITY_NOT_DIRECTION_OR_EXECUTION' }, warnings: unique([...r.warnings, ...c.warnings]) });
  }
  private inputError(d: CompiledStrategyDefinition, s: StrategyContext, g: EvidenceGraph, c: ConfidenceAssessment, r: ReadinessAssessment, p: DecisionPolicy): string | null { const validation = new DecisionPolicyValidator().validate(p); if (!validation.valid) return `Invalid decision policy: ${validation.issues.map((x) => x.message).join(' ')}`; if (d.id !== s.strategyId || d.version !== s.strategyVersion || g.strategyId !== d.id || g.strategyContextId !== s.contextId || g.marketContextId !== s.marketContextId || c.strategyId !== d.id || c.compiledStrategyId !== d.compiledStrategyId || c.strategyContextId !== s.contextId || c.evidenceGraphId !== g.graphId || r.strategyId !== d.id || r.compiledStrategyId !== d.compiledStrategyId || r.strategyContextId !== s.contextId || r.evidenceGraphId !== g.graphId || r.confidenceAssessmentId !== c.assessmentId || r.sourceMarketContextId !== g.marketContextId || c.generatedAt !== s.executionTimestamp || r.generatedAt !== s.executionTimestamp) return 'Source identity mismatch.'; if (p.requireEvidenceGraphValid && !new EvidenceGraphValidator().validate(g).valid) return 'Invalid EvidenceGraph.'; if (p.requireConfidenceAssessmentValid && c.status === 'ERROR') return 'ConfidenceAssessment is invalid.'; if (p.requireReadinessAssessmentValid && r.status === 'ERROR') return 'ReadinessAssessment is invalid.'; return null; }
  private error(d: CompiledStrategyDefinition, s: StrategyContext, g: EvidenceGraph, c: ConfidenceAssessment, r: ReadinessAssessment, p: DecisionPolicy, warning: string): DecisionAssessment { return deepFreeze({ assessmentId: createDecisionAssessmentId(d, s, g, c, r, p), version: '1.0.0', engineVersion: DECISION_ENGINE_VERSION, policyId: p.id, policyVersion: p.version, strategyId: d.id, strategyVersion: d.version, compiledStrategyId: d.compiledStrategyId, marketContextId: g.marketContextId, strategyContextId: s.contextId, evidenceGraphId: g.graphId, confidenceAssessmentId: c.assessmentId, readinessAssessmentId: r.assessmentId, generatedAt: s.executionTimestamp, status: 'ERROR', outcome: 'ERROR', actionable: false, criteria: [], failedCriterionIds: [], blockingCriterionIds: [], warningCriterionIds: [], failedRequiredRuleIds: [], unavailableRequiredRuleIds: [], errorRuleIds: [], matchedRuleCount: 0, confidencePercent: null, coveragePercent: null, summary: { totalCriteria: 0, passedCriteria: 0, failedCriteria: 0, notEvaluatedCriteria: 0, errorCriteria: 1, blockingFailures: 0, warningFailures: 0, meaning: 'ACTIONABILITY_NOT_DIRECTION_OR_EXECUTION' }, warnings: [warning] }); }
}
