import Link from 'next/link';
import {notFound} from 'next/navigation';
import EmployeeOrganizationForm from '@/components/hq/EmployeeOrganizationForm';
import {getHQContext,HQShell} from '@/lib/hq-page';

export default async function Page({params}:{params:Promise<{id:string}>}){
 const {id}=await params;const {supabase,role,displayName,permissions}=await getHQContext('staff.view');
 const [{data,error},{data:workspace}]=await Promise.all([supabase.rpc('staff_employee_profile_v3',{p_user_id:id}),supabase.rpc('staff_team_workspace_v3',{p_query:'',p_page:1,p_page_size:100,p_department_id:'ALL',p_position_id:'ALL',p_manager_id:'ALL',p_status:'ALL'})]);
 if(error)throw new Error(error.message);if(!data)notFound();const x=data as any,identity=x.identity;
 return <HQShell displayName={displayName} role={role} permissions={permissions}><div className="stack employee-profile"><header className="card directory-page-header"><div><span className="eyebrow">EMPLOYEE PROFILE</span><h1>{identity.name||identity.email}</h1><p className="muted">{identity.position||'No position'} · {identity.department||'No department assigned'}</p></div><Link className="button-link secondary" href="/hq/team">Back to team</Link></header><div className="grid grid-2"><Card title="Identity"><Row label="Email" value={identity.email}/><Row label="Department" value={identity.department||'—'}/><Row label="Position" value={identity.position||'—'}/><Row label="Permission profile" value={identity.permissionProfile||'—'}/><Row label="Reports To" value={identity.manager||'—'}/><Row label="Direct Reports" value={String(identity.directReports)}/><Row label="Status" value={identity.active?'Active':'Disabled'}/></Card>{permissions.includes('staff.manage')&&<EmployeeOrganizationForm employee={identity} departments={workspace?.departments??[]} positions={workspace?.positions??[]} profiles={workspace?.permissionProfiles??[]} managers={workspace?.managers??[]}/>}</div><Card title="Permissions"><p className="muted">Permissions are derived exclusively from the assigned permission profile and explicit individual overrides.</p><div className="permission-grid">{x.permissions.map((p:any)=><div className="permission-item" key={p.key}><span><strong>{p.key}</strong><small>{p.description}</small><em>{p.granted?`Granted · ${p.source}`:'Not granted'}</em></span></div>)}</div></Card><Card title="Recent activity & audit history">{x.activity.length?x.activity.slice(0,30).map((a:any,i:number)=><div className="event-row" key={i}><span>{a.action.replaceAll('_',' ')}<small>{a.resource}</small></span><time>{new Date(a.created_at).toLocaleString()}</time></div>):<p className="muted">No recent activity.</p>}</Card></div></HQShell>
}
function Card({title,children}:{title:string;children:React.ReactNode}){return <section className="card"><h2>{title}</h2>{children}</section>}
function Row({label,value}:{label:string;value:string}){return <div className="event-row"><span>{label}</span><strong>{value}</strong></div>}
