import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {buildDecisionExplanation,DECISION_INTEGRITY_STATEMENT,UNKNOWN_NEXT_TRIGGER} from '../lib/intelligence/decision-explanation.ts';
import type {ConditionEvidence,TradingDnaEvidenceReport} from '../lib/trading-dna/runtime.ts';
import type {TradeAuthorizationEligibility} from '../lib/trade-authorization.ts';
import type {ChartAnalysis,StrategyProfile,TradeResult} from '../types/trade.ts';
import {DEFAULT_STRATEGY_PROFILE} from '../types/trade.ts';
import type {DecisionNarrative} from '../types/intelligence.ts';

const now=new Date('2026-08-02T12:00:00.000Z');
const condition=(overrides:Partial<ConditionEvidence>={}):ConditionEvidence=>({id:'rule-1',ruleId:'structure.bos',label:'Market structure shift',status:'PASS',required:true,evaluationType:'AUTOMATIC',operator:'CONFIRMED',actual:true,expected:[true],reason:'A confirmed market-structure shift is present.',groupPath:['root'],...overrides});
const report=(conditions:ConditionEvidence[]):TradingDnaEvidenceReport=>({status:conditions.some(item=>item.status==='FAIL')?'FAIL':conditions.some(item=>item.status==='PENDING')?'PENDING':'PASS',summary:'Deterministic rule result.',conditions,groups:[],counts:{passed:conditions.filter(item=>item.status==='PASS').length,failed:conditions.filter(item=>item.status==='FAIL').length,pending:conditions.filter(item=>item.status==='PENDING').length},generatedAt:now.toISOString()});
const analysis=(status:ChartAnalysis['status']='VALID_ANALYSIS'):ChartAnalysis=>({status,analysisStatus:status,instrument:'XAUUSD',timeframe:'M30',strategyId:'strategy-1',provider:'Twelve Data',calculatedAt:now.toISOString(),latestCandleTimestamp:'2026-08-02T11:59:00.000Z',detectedTimeframes:['M30'],h4Bias:'BULLISH',h1Bias:'BULLISH',suggestedDirection:'BUY',setupType:'Configured setup',liveAnalysisConfidence:90,strategyConfidenceThreshold:80,evidence:{h4TrendAligned:{value:true,confidence:100,reason:'Confirmed.'},h1TrendAligned:{value:true,confidence:100,reason:'Confirmed.'},structurePattern:{value:true,confidence:100,reason:'Confirmed.'},liquiditySweep:{value:true,confidence:100,reason:'Confirmed.'},chochConfirmed:{value:true,confidence:100,reason:'Confirmed.'},bosConfirmed:{value:true,confidence:100,reason:'Confirmed.'},orderBlock:{value:false,confidence:0,reason:'Not present.'},fairValueGap:{value:false,confidence:0,reason:'Not present.'},retestConfirmed:{value:false,confidence:0,reason:'Not present.'}},candidates:[{id:'candidate',direction:'BUY',entryLow:null,entryHigh:null,stopLoss:null,takeProfit:null,rr:null,status:'READY',rationale:'Existing deterministic candidate.'}],warnings:[],summary:'Existing deterministic analysis.'});
const result=(verdict:TradeResult['verdict']):TradeResult=>({score:90,grade:'A',verdict,rr:3,riskAmount:50,stopDistance:10,vetoes:[],observations:[],scoreItems:[]});
const strategy:StrategyProfile={...DEFAULT_STRATEGY_PROFILE,id:'strategy-1',name:'Core trading rules'};
const narrative=(action?:string):DecisionNarrative=>({version:'1',recommendation:'WAIT',engineVerdict:'WAIT',source:'DETERMINISTIC',headline:'Immutable narrative',explanation:'Immutable explanation',reasons:[],missingEvidence:[],nextActions:action?[{id:'action-1',type:'WAIT_FOR_EVIDENCE',priority:1,label:action,rationale:'Existing deterministic metadata.',blocking:true,relatedEvidenceIds:['rule-1']}]:[],strategyContext:{complete:true,missingFields:[],strategyId:'strategy-1',strategyName:'Core trading rules',engineVersion:2,confidenceThreshold:80,fiveLayerModel:[],mandatoryRuleCount:1,optionalRuleCount:0,automaticRuleCount:1,manualRuleCount:0,permittedSessions:[],allowedSetups:null,riskPolicy:{maxRiskPercentage:.5,minimumRiskReward:3}},readiness:{currentScore:90,requiredScore:80,label:'Evidence readiness',isProbability:false},disciplineMessage:'Existing deterministic discipline.',generatedAt:now.toISOString(),fallbackUsed:false});
const build=(options:{status?:ChartAnalysis['status'];verdict?:TradeResult['verdict'];conditions?:ConditionEvidence[];narrative?:DecisionNarrative;warnings?:string[]})=>{const market=analysis(options.status);market.warnings=options.warnings??[];return buildDecisionExplanation({analysis:market,result:options.verdict?result(options.verdict):null,narrative:options.narrative,evidenceReport:report(options.conditions??[condition()]),strategy,now})};

test('READY states that all required rules are confirmed and leads to final risk check',()=>{const state=build({verdict:'AUTHORIZED'});assert.equal(state.verdict,'READY');assert.equal(state.headline,'Your required trading rules are confirmed.');assert.equal(state.confirmedRequiredCount,state.totalRequiredCount);assert.match(state.nextAction,/final risk check/)});
test('WAIT exposes the first missing required rule and deterministic trigger',()=>{const state=build({verdict:'WAIT',conditions:[condition({status:'PENDING',actual:null,reason:'Market structure shift is not confirmed.'})],narrative:narrative('Wait for a confirmed market-structure shift.')});assert.equal(state.verdict,'WAIT');assert.equal(state.primaryReason,'Primary reason: Market structure shift is not confirmed.');assert.equal(state.nextAction,'Wait for a confirmed market-structure shift.')});
test('BLOCKED exposes the first violated required rule',()=>{const state=build({verdict:'REJECTED',conditions:[condition({status:'FAIL',actual:false,reason:'Current time is outside your permitted New York session.'})]});assert.equal(state.verdict,'BLOCKED');assert.match(state.primaryReason,/outside your permitted New York session/)});
test('NO_SETUP explains that the saved setup is absent',()=>{const state=build({status:'NO_RELEVANT_EVIDENCE'});assert.equal(state.verdict,'NO_SETUP');assert.match(state.explanation,/does not match the setup saved/)});
test('market closed and unavailable data never expose readiness as a verdict-like score',()=>{const closed=build({warnings:['Market closed.']});const unavailable=build({status:'DATA_UNAVAILABLE'});assert.equal(closed.verdict,'MARKET_CLOSED');assert.equal(unavailable.verdict,'DATA_UNAVAILABLE');assert.doesNotMatch(`${closed.headline}${closed.explanation}${unavailable.headline}${unavailable.explanation}`,/%|confidence/i)});
test('incomplete strategies direct customers to their trading rules',()=>{const state=build({status:'STRATEGY_INCOMPLETE',conditions:[condition({status:'PENDING',evaluationType:'EXTERNAL',reason:'A required rule could not be verified.'})]});assert.equal(state.verdict,'STRATEGY_INCOMPLETE');assert.match(state.nextAction,/Review the highlighted rules/)});
test('required rules remain ahead of helpful confirmations',()=>{const state=build({conditions:[condition({id:'optional',required:false}),condition({id:'required',status:'PENDING'})]});assert.equal(state.items[0].id,'required');assert.equal(state.items[1].id,'optional')});
test('helpful confirmations cannot override a missing required rule',()=>{const state=build({verdict:'WAIT',conditions:[condition({id:'optional',required:false,status:'PASS'}),condition({id:'required',status:'PENDING',reason:'Required retest is missing.'})]});assert.equal(state.verdict,'WAIT');assert.match(state.primaryReason,/Required retest is missing/)});
test('primary reason follows runtime rule order and then stable output',()=>{const state=build({verdict:'WAIT',conditions:[condition({id:'first',status:'PENDING',reason:'First saved rule is missing.'}),condition({id:'second',status:'PENDING',reason:'Second saved rule is missing.'})]});assert.match(state.primaryReason,/First saved rule/)});
test('next trigger is only copied from deterministic metadata',()=>{const exact='Return during your allowed trading session.';assert.equal(build({verdict:'WAIT',conditions:[condition({status:'PENDING'})],narrative:narrative(exact)}).nextAction,exact)});
test('missing trigger metadata uses the explicit non-invention fallback',()=>{assert.equal(build({verdict:'WAIT',conditions:[condition({status:'PENDING'})]}).nextAction,UNKNOWN_NEXT_TRIGGER)});
test('readiness is represented as a required-rule count',()=>{const state=build({verdict:'WAIT',conditions:[condition(),condition({id:'missing',status:'PENDING'})]});assert.equal(`${state.confirmedRequiredCount} of ${state.totalRequiredCount} required rules`,'1 of 2 required rules')});
test('mandatory missing evidence can force WAIT even when the engine verdict is otherwise READY',()=>{const eligibility:TradeAuthorizationEligibility={allowed:false,eligible:false,state:'WAIT',reasonCode:'MISSING_MANDATORY_CONFIRMATIONS',message:'Mandatory confirmations are still missing before this decision can be authorized.',createActiveTrade:false,missingMandatoryConfirmations:[{label:'Liquidity sweep',reason:'Liquidity sweep is required and still missing.'}]};const state=buildDecisionExplanation({analysis:analysis('VALID_ANALYSIS'),result:result('AUTHORIZED'),narrative:{...narrative('Wait for the required liquidity sweep.'),missingEvidence:[{id:'evidence:liquiditySweep',evidenceKey:'liquiditySweep',ruleKey:'liquiditySweep',label:'Liquidity sweep',layer:5,timeframe:'M15',evaluationMode:'AUTOMATIC',mandatory:true,detected:false,confidence:null,reason:'Liquidity sweep is required and still missing.',canUserConfirm:false}]},evidenceReport:report([condition({status:'PASS',reason:'Market structure is confirmed.'})]),strategy,authorizationEligibility:eligibility,now});assert.equal(state.verdict,'WAIT');assert.match(state.primaryReason,/Liquidity sweep/);assert.equal(`${state.confirmedRequiredCount} of ${state.totalRequiredCount} required rules`,'1 of 2 required rules');});
test('pre-final candidate cannot be READY while canonical setup evidence is pending',()=>{const pending=report([condition({status:'PASS'}),condition({id:'order-block',ruleId:'smart-money.order-block',label:'Order Block',status:'PENDING',reason:'Order Block evidence is pending.'})]);pending.status='PENDING';const state=buildDecisionExplanation({analysis:analysis('VALID_ANALYSIS'),result:null,evidenceReport:pending,strategy,now});assert.equal(state.verdict,'WAIT');assert.equal(state.totalRequiredCount,2);assert.equal(state.confirmedRequiredCount,1);assert.match(state.primaryReason,/Order Block/);});
test('complete required setup is READY before final risk even if the market candidate is WAIT',()=>{const market=analysis('VALID_ANALYSIS');market.candidates[0].status='WAIT';const optional=condition({id:'displacement',ruleId:'displacement',label:'Displacement',required:false,status:'PENDING',actual:null,reason:'Optional displacement is pending.'});const evidence=report([condition({id:'required-1'}),condition({id:'required-2'}),condition({id:'required-3'}),optional]);evidence.status='PENDING';const state=buildDecisionExplanation({analysis:market,result:null,evidenceReport:evidence,strategy,now});assert.equal(state.confirmedRequiredCount,3);assert.equal(state.totalRequiredCount,3);assert.equal(state.verdict,'READY');assert.doesNotMatch(state.primaryReason,/incomplete/i);});
test('optional missing evidence does not override an otherwise ready authorization state',()=>{const eligibility:TradeAuthorizationEligibility={allowed:true,eligible:true,state:'READY',reasonCode:'READY',message:'The decision is ready for authorization.',createActiveTrade:true,missingMandatoryConfirmations:[]};const state=buildDecisionExplanation({analysis:analysis('VALID_ANALYSIS'),result:result('AUTHORIZED'),narrative:{...narrative('Proceed to final risk check.'),missingEvidence:[{id:'evidence:optional',evidenceKey:'fairValueGap',ruleKey:'fairValueGap',label:'Fair value gap',layer:5,timeframe:'M15',evaluationMode:'AUTOMATIC',mandatory:false,detected:false,confidence:null,reason:'This is helpful context, not a required rule.',canUserConfirm:false}]},evidenceReport:report([condition({status:'PASS',reason:'The required market structure rule is confirmed.'})]),strategy,authorizationEligibility:eligibility,now});assert.equal(state.verdict,'READY');assert.match(state.primaryReason,/Every required rule/);});
test('optional pending evidence does not prevent READY when required conditions are confirmed',()=>{const optional=condition({id:'optional',required:false,status:'PENDING',actual:null,reason:'Optional fair value gap is pending.'});const evidence=report([condition(),optional]);evidence.status='PENDING';const state=buildDecisionExplanation({analysis:analysis('VALID_ANALYSIS'),result:result('AUTHORIZED'),evidenceReport:evidence,strategy,now});assert.equal(state.verdict,'READY');});
test('optional displacement never becomes the primary reason for a final risk block',()=>{const optional=condition({id:'displacement',ruleId:'displacement',label:'Displacement',required:false,status:'PENDING',actual:null,reason:'Displacement has not supplied evidence yet.'});const state=buildDecisionExplanation({analysis:analysis('VALID_ANALYSIS'),result:{...result('REJECTED'),vetoes:['Risk exceeds 1%.']},evidenceReport:report([condition(),optional]),strategy,now});assert.equal(state.verdict,'BLOCKED');assert.equal(state.primaryReason,'Primary reason: Risk exceeds 1%.');});
test('AI prose cannot change verdict or add evidence to the explanation model',()=>{const ai={...narrative('Wait for existing evidence.'),source:'AI_ENHANCED' as const,educationalExplanation:'General process reflection.',headline:'READY',missingEvidence:[{id:'invented',evidenceKey:'bosConfirmed' as const,ruleKey:'invented',label:'Invented evidence',evaluationMode:'AUTOMATIC' as const,mandatory:true,detected:false,confidence:null,reason:'Invented.',canUserConfirm:false}]};const state=build({verdict:'REJECTED',conditions:[condition({status:'FAIL'})],narrative:ai});assert.equal(state.verdict,'BLOCKED');assert.equal(state.items.length,1);assert.doesNotMatch(JSON.stringify(state.items),/Invented evidence/)});
test('decision integrity and provenance remain explicit',()=>{const state=build({verdict:'AUTHORIZED'});assert.equal(state.integrityStatement,DECISION_INTEGRITY_STATEMENT);assert.equal(state.dataStatus.provider,'Twelve Data');assert.equal(state.dataStatus.lastVerifiedCandleAt,'2026-08-02T11:59:00.000Z')});

test('customer surfaces provide report, provenance, accessibility, mobile and failure safeguards',()=>{const hero=fs.readFileSync('components/decision/DecisionHero.tsx','utf8'),reportView=fs.readFileSync('components/decision/DecisionReport.tsx','utf8'),market=fs.readFileSync('components/LiveMarketPanel.tsx','utf8'),validator=fs.readFileSync('components/TradeValidator.tsx','utf8'),styles=fs.readFileSync('app/trade-police.css','utf8');assert.match(hero,/aria-live="polite"/);assert.match(hero,/required rules confirmed/);assert.match(reportView,/Readiness is not a probability of profit|does not predict profits/);assert.match(reportView,/Plain-language explanation/);assert.match(reportView,/does not use the chart image/);assert.match(reportView,/stateIcon/);assert.match(market,/No decision was produced/);assert.match(market,/do not consume monthly usage/);assert.match(validator,/reasoningCloseRef\.current\?\.focus/);assert.match(validator,/event\.key==='Escape'/);assert.match(styles,/@media\(max-width:430px\)/);assert.match(styles,/\.reasoning-modal\{width:100vw/);assert.match(styles,/@media\(prefers-reduced-motion:reduce\)/)});

test('AI timeout and unsafe output retain the deterministic fallback contract',()=>{const source=fs.readFileSync('lib/server/decision-narrative-ai.ts','utf8');assert.match(source,/controller\.abort/);assert.match(source,/return deterministicFallback\(narrative\)/);assert.match(source,/\.\.\.narrative/);assert.match(source,/source: 'DETERMINISTIC'/)});
