import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {buildDecisionTimeline,sortDecisionTimelineEvents} from '../lib/intelligence/decision-timeline.ts';import type {DecisionTimelineEvent} from '../types/decision-timeline.ts';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8'),time='2026-08-02T12:00:00.000Z';
const evidence=(overrides:Record<string,unknown>={})=>({id:'rule-1',ruleId:'trend',title:'Trend alignment',description:'Trend alignment matched.',state:'CONFIRMED' as const,detectedAt:time,evidenceIds:['e-1'],deterministic:true as const,...overrides});

test('timeline includes only deterministic evidence with recorded timestamps',()=>{const timeline=buildDecisionTimeline({evidence:[evidence(),evidence({id:'missing-time',detectedAt:undefined})],verdict:'READY',verdictTimestamp:time});assert.equal(timeline.events.filter(event=>event.type==='RULE_CONFIRMED').length,1);assert.ok(timeline.events.every(event=>event.deterministic));});
test('missing and invalid timestamps never create events',()=>{const timeline=buildDecisionTimeline({evidence:[evidence({detectedAt:undefined}),evidence({id:'bad',detectedAt:'not-a-date'})],verdict:'WAIT'});assert.deepEqual(timeline.events,[]);});
test('AI prose cannot create timeline events because it is outside the input model',()=>{const source=read('lib/intelligence/decision-timeline.ts');assert.doesNotMatch(source,/educationalExplanation|coachingMessage|learningTip|OPENAI|\bAI\b/);assert.doesNotMatch(source,/DecisionNarrative/);});
test('event ordering is chronological and deterministic',()=>{const timeline=buildDecisionTimeline({marketCalculationCompletedAt:'2026-08-02T11:59:00.000Z',evidence:[evidence()],verdict:'READY',verdictTimestamp:'2026-08-02T12:01:00.000Z'});assert.deepEqual(timeline.events.map(event=>event.type),['MARKET_DATA_VERIFIED','RULE_CONFIRMED','VERDICT_PRODUCED']);assert.deepEqual(timeline.events,buildDecisionTimeline({marketCalculationCompletedAt:'2026-08-02T11:59:00.000Z',evidence:[evidence()],verdict:'READY',verdictTimestamp:'2026-08-02T12:01:00.000Z'}).events);});
test('same-timestamp tie breaker follows the required event precedence then stable id',()=>{const types=['REPORT_SAVED','VERDICT_PRODUCED','FINAL_RISK_CHECK_COMPLETED','SETUP_DETECTED','RULE_VIOLATED','RULE_BECAME_MISSING','RULE_CONFIRMED','MARKET_DATA_VERIFIED'] as const;const rows=types.map((type,index)=>({id:`event-${index}`,type,timestamp:time,title:type,description:type,state:'INFORMATIONAL',evidenceIds:[],deterministic:true} satisfies DecisionTimelineEvent));assert.deepEqual(sortDecisionTimelineEvents(rows).map(row=>row.type),[...types].reverse());});
test('current and historical reports render the shared timeline below their summaries',()=>{for(const file of ['components/decision/DecisionReport.tsx','components/decision/HistoricalDecisionReport.tsx']){const source=read(file);assert.match(source,/buildDecisionTimeline/);assert.match(source,/decision-report-summary[\s\S]*<DecisionTimeline timeline=/)}});
test('historical timeline uses snapshot fields only and never invokes live systems',()=>{const source=read('components/decision/HistoricalDecisionReport.tsx');for(const forbidden of ['fetch(','market-data','market-analysis','decision-engine','trading-dna','DecisionNarrative'])assert.doesNotMatch(source,new RegExp(forbidden.replace(/[()]/g,'\\$&')));assert.match(source,/snapshot\.marketData\.calculationCompletedAt/);assert.match(source,/snapshot\.createdAt/);});
test('schema 1.0.0 stays supported and timeline does not alter snapshot or fingerprint code',()=>{assert.match(read('types/historical-decision.ts'),/HISTORICAL_DECISION_SCHEMA_VERSION = '1\.0\.0'/);assert.match(read('lib/historical-decisions/version-registry.ts'),/HISTORICAL_DECISION_SCHEMA_VERSION/);for(const source of [read('types/historical-decision.ts'),read('lib/historical-decisions/build.ts'),read('lib/historical-decisions/fingerprint.ts')])assert.doesNotMatch(source,/DecisionTimeline/);});
test('unknown schemas still fail safely',()=>{const source=read('lib/historical-decisions/schema.ts');assert.match(source,/UNSUPPORTED_VERSION/);assert.match(source,/isSupportedHistoricalReportVersion/);});
test('sparse timelines are identified without inventing intermediate events',()=>{const timeline=buildDecisionTimeline({evidence:[],verdict:'WAIT',verdictTimestamp:time});assert.equal(timeline.events.length,1);assert.equal(timeline.events[0]?.type,'VERDICT_PRODUCED');assert.equal(timeline.detailedTimingAvailable,false);assert.match(read('components/decision/DecisionTimeline.tsx'),/Detailed event timing was not available for this analysis/);});
test('timeline disclosure, semantic states and accessible time markup are visible',()=>{const source=read('components/decision/DecisionTimeline.tsx');assert.match(source,/only recorded deterministic timestamps/);assert.match(source,/Missing events are not reconstructed/);assert.match(source,/<ol>/);assert.match(source,/<time dateTime=/);assert.match(source,/State:/);assert.match(source,/Confirmed|Missing|Blocked|Recorded/);});
test('mobile timeline is vertical, wrapping and overflow safe',()=>{const css=read('app/trade-police.css');assert.match(css,/@media\(max-width:430px\)/);assert.match(css,/\.timeline-event\{grid-template-columns:26px minmax\(0,1fr\)/);assert.match(css,/overflow-wrap:anywhere/);assert.doesNotMatch(css,/\.decision-timeline[^}]*overflow-x/);});
test('timeline adds no network or animation libraries',()=>{const transformation=read('lib/intelligence/decision-timeline.ts'),view=read('components/decision/DecisionTimeline.tsx');for(const source of [transformation,view]){assert.doesNotMatch(source,/fetch\(|axios|framer-motion|chart\.js|recharts/)}assert.match(read('app/trade-police.css'),/@media\(prefers-reduced-motion:reduce\)/);});
