import assert from 'node:assert/strict';
import test from 'node:test';
import { AnalysisContextBuilder } from '../lib/market-intelligence/analysis/analysis-context-builder.ts';
import { simpleAtr } from '../lib/market-intelligence/analysis-utils/index.ts';
import type { DetectorResult, MarketDataSnapshot, NormalizedCandle } from '../lib/market-intelligence/contracts.ts';
import { DisplacementDetector } from '../lib/market-intelligence/detectors/displacement/displacement-detector.ts';
import { calculateLegacyDisplacement } from '../lib/market-intelligence/detectors/displacement/displacement-utils.ts';
import { createDetectorRegistry } from '../lib/market-intelligence/registry/bootstrap.ts';
import { DetectorRegistry } from '../lib/market-intelligence/registry/detector-registry.ts';
import { DetectorRunner } from '../lib/market-intelligence/runner/detector-runner.ts';
import { ShadowValidator } from '../lib/market-intelligence/shadow-validation/shadow-validator.ts';

const base = Date.parse('2026-07-01T00:00:00.000Z');
const candle = (index: number, open = 100, high = 105, low = 95, close = 100): NormalizedCandle => ({ openedAt: new Date(base + index * 3_600_000).toISOString(), closedAt: new Date(base + (index + 1) * 3_600_000).toISOString(), open, high, low, close, volume: 100, complete: true });
const history = (last = candle(14, 100, 112, 99, 111)) => [...Array.from({ length: 14 }, (_, index) => candle(index)), last];
const snapshot = (candles: NormalizedCandle[], timeframe = 'H1'): MarketDataSnapshot => { const requestedAt = new Date(base + Math.max(1, candles.length) * 3_600_000).toISOString(); return { id: `displacement-${timeframe}`, snapshotVersion: '1.0.0', provider: 'fixture', providerVersion: '1', providerSymbol: 'XAU/USD', instrument: 'XAUUSD', timeframe, requestedAt, receivedAt: requestedAt, dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, freshness: { state: 'FRESH', dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, ageMs: 0, maximumAgeMs: 60_000 }, candles, validationWarnings: [] }; };
const atr = (value: number) => ({ value, period: 14, smoothingMethod: 'SIMPLE' as const, candleCount: 15, trueRangeCount: 14, sourceStartTime: new Date(base).toISOString(), sourceEndTime: new Date(base + 14 * 3_600_000).toISOString(), sufficientData: true });

test('ATR-dominant and range-dominant displacement preserve strict max-threshold formula', () => {
  const atrDominant = calculateLegacyDisplacement('H1', history(candle(14, 100, 114, 99, 113)), atr(10)); assert.equal(atrDominant?.atrThreshold, 11); assert.equal(atrDominant?.bodyRatioThreshold, 9.75); assert.equal(atrDominant?.classification, 'DISPLACEMENT');
  const rangeDominant = calculateLegacyDisplacement('H1', history(candle(14, 100, 120, 99, 118)), atr(5)); assert.equal(rangeDominant?.bodyRatioThreshold, 13.65); assert.equal(rangeDominant?.classification, 'DISPLACEMENT');
});

test('failure of either required threshold produces NOT_DISPLACEMENT', () => {
  const belowAtr = calculateLegacyDisplacement('H1', history(candle(14, 100, 110, 99, 109)), atr(10)); assert.equal(belowAtr?.bodyAboveRangeThreshold, true); assert.equal(belowAtr?.bodyAboveAtrThreshold, false); assert.equal(belowAtr?.displacementDetected, false);
  const belowRange = calculateLegacyDisplacement('H1', history(candle(14, 100, 120, 99, 112)), atr(5)); assert.equal(belowRange?.bodyAboveAtrThreshold, true); assert.equal(belowRange?.bodyAboveRangeThreshold, false); assert.equal(belowRange?.displacementDetected, false);
});

test('equality with ATR, range, or effective threshold never qualifies', () => {
  const equalAtr = calculateLegacyDisplacement('H1', history(candle(14, 100, 112, 99, 111)), atr(10)); assert.equal(equalAtr?.bodySize, equalAtr?.atrThreshold); assert.equal(equalAtr?.displacementDetected, false);
  const range = 20, body = range * 0.65, equalRange = calculateLegacyDisplacement('H1', history(candle(14, 100, 120, 100, 100 + body)), atr(1)); assert.equal(equalRange?.bodySize, equalRange?.bodyRatioThreshold); assert.equal(equalRange?.displacementDetected, false);
  assert.equal(equalAtr?.bodySize, equalAtr?.effectiveThreshold);
});

test('bullish and bearish bodies classify identically by magnitude', () => { const bullish = calculateLegacyDisplacement('H1', history(candle(14, 100, 114, 99, 113)), atr(5)), bearish = calculateLegacyDisplacement('H1', history(candle(14, 113, 114, 99, 100)), atr(5)); assert.equal(bullish?.classification, 'DISPLACEMENT'); assert.equal(bearish?.classification, 'DISPLACEMENT'); assert.equal(bullish?.bodySize, bearish?.bodySize); });

test('doji and zero-range candles preserve Number.EPSILON classification behavior', () => { const result = calculateLegacyDisplacement('H1', history(candle(14, 100, 100, 100, 100)), atr(0)); assert.equal(result?.fullRange, Number.EPSILON); assert.equal(result?.bodyRatioThreshold, Number.EPSILON * 0.65); assert.equal(result?.bodyToRangeRatio, 0); assert.equal(result?.classification, 'NOT_DISPLACEMENT'); assert.doesNotMatch(JSON.stringify(result), /Infinity|NaN/); });

test('detector reuses exact SIMPLE ATR(14), last 15 candles, and 14 true ranges', async () => { const values = [candle(0, 1, 2, 0, 1), ...history()].slice(-15); const expected = simpleAtr(values, 14), result = await new DisplacementDetector().execute(snapshot(values)); assert.equal(result.status, 'DETECTED'); assert.equal(result.payload?.atr, expected.value); assert.equal(result.payload?.atrPeriod, 14); assert.equal(result.payload?.atrSmoothingMethod, 'SIMPLE'); assert.equal(result.payload?.candleCount, 15); assert.equal(result.payload?.trueRangeCount, 14); assert.equal(result.payload?.sourceStartTime, values[0].openedAt); });

test('completion, exact minimum history, and insufficient history have explicit semantics', async () => { const values = history(); assert.equal((await new DisplacementDetector().execute(snapshot(values))).status, 'DETECTED'); assert.equal((await new DisplacementDetector().execute(snapshot(values.slice(1)))).status, 'INSUFFICIENT_DATA'); const incomplete = { ...candle(15, 100, 150, 90, 140), complete: false, closedAt: new Date(base + 17 * 3_600_000).toISOString() }; const result = await new DisplacementDetector().execute(snapshot([...values, incomplete])); assert.equal(result.payload?.eventCandleTime, values.at(-1)!.openedAt); });

test('malformed OHLC, impossible geometry, timestamp, and ordering return ERROR', async () => { const fixtures: Array<[NormalizedCandle[], string]> = []; const nan = history(); nan[0] = { ...nan[0], high: Number.NaN }; fixtures.push([nan, 'INVALID_OHLC']); const geometry = history(); geometry[0] = { ...geometry[0], high: 90 }; fixtures.push([geometry, 'IMPOSSIBLE_CANDLE_GEOMETRY']); const timestamp = history(); timestamp[0] = { ...timestamp[0], closedAt: 'bad' }; fixtures.push([timestamp, 'INVALID_TIMESTAMP']); const duplicate = history(); duplicate[1] = { ...duplicate[1], openedAt: duplicate[0].openedAt }; fixtures.push([duplicate, 'INVALID_CANDLE_ORDER']); for (const [values, code] of fixtures) { const result = await new DisplacementDetector().execute(snapshot(values)); assert.equal(result.status, 'ERROR'); assert.equal(result.errorCode, code); } });

test('metadata, runner, context, shadow parity, serialization, and immutability integrate', async () => { const detector = new DisplacementDetector(); assert.deepEqual({ id: detector.id, version: detector.version, displayName: detector.displayName, deterministic: detector.deterministic, supportsReplay: detector.metadata.supportsReplay, experimental: detector.metadata.experimental, enabledByDefault: detector.metadata.enabledByDefault }, { id: 'displacement', version: '1.0.0', displayName: 'Displacement Detector', deterministic: true, supportsReplay: true, experimental: true, enabledByDefault: true }); assert.ok(createDetectorRegistry().exists('displacement')); const source = snapshot(history()), before = JSON.stringify(source), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze(), { createRunId: () => 'displacement-run' }).execute(source, ['displacement']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary), beforeContext = JSON.stringify(context), comparison = new ShadowValidator().validate(source, context).comparisons.find((item) => item.detectorId === 'displacement'); assert.equal(comparison?.status, 'MATCH'); assert.equal(comparison?.exactMatch, true); assert.equal(JSON.stringify(source), before); assert.equal(JSON.stringify(context), beforeContext); assert.deepEqual(JSON.parse(JSON.stringify(context)), context); assert.doesNotMatch(JSON.stringify(summary.detectorResults[0]), /BUY|SELL|strategy|risk|readiness|entry|stopLoss|takeProfit|target|decision/i); });

test('wrong inclusive operator and multipliers produce shadow mismatches', async () => { const source = snapshot(history()), detector = new DisplacementDetector(), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze()).execute(source, ['displacement']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary); const patches: Array<Record<string, string | number | boolean>> = [{ classification: 'DISPLACEMENT', displacementDetected: true }, { atrThresholdMultiplier: 1.2, atrThreshold: 999 }, { bodyRatioThresholdMultiplier: 0.7, bodyRatioThreshold: 999 }]; for (const payloadPatch of patches) { const wrong = context.detectorResults.map((result): DetectorResult => ({ ...result, payload: { ...(result.payload as object), ...payloadPatch } })); assert.equal(new ShadowValidator().validate(source, { ...context, detectorResults: wrong }).comparisons.find((item) => item.detectorId === 'displacement')?.status, 'MISMATCH'); } });
