import assert from 'node:assert/strict';
import test from 'node:test';
import { HistoricalAcquisitionError, planAcquisitionChunks, ReplicationDatasetAcquisitionService, TwelveDataHistoricalAcquirer, type HistoricalAcquisitionRequest } from '../lib/market-intelligence-lab/historical-acquisition/index.ts';
import { HistoricalDatasetManager, InMemoryHistoricalDatasetRepository } from '../lib/market-intelligence-lab/historical-datasets/index.ts';
import { XAUUSD_REPLICATION_PROGRAM_HASH, XAUUSD_REPLICATION_PROGRAM_V1 } from '../lib/market-intelligence-lab/replication/index.ts';

const request = (overrides: Partial<HistoricalAcquisitionRequest> = {}): HistoricalAcquisitionRequest => ({ instrument: 'XAUUSD', timeframe: 'M15', startAt: '2024-01-01T00:00:00.000Z', endAt: '2024-03-01T00:00:00.000Z', acquiredAt: '2026-07-22T00:00:00.000Z', provider: 'Twelve Data', timezone: 'UTC', ...overrides });
const row = (datetime: string, close = 2000) => ({ datetime, open: String(close - 1), high: String(close + 1), low: String(close - 2), close: String(close), volume: '10' });

test('replication program is frozen, preregistered, calibration-locked, and content-addressed', () => { assert.equal(XAUUSD_REPLICATION_PROGRAM_V1.programId, 'TP-REP-XAUUSD-2026-01'); assert.deepEqual(XAUUSD_REPLICATION_PROGRAM_V1.timeframes, ['M5', 'M15', 'H1']); assert.equal(XAUUSD_REPLICATION_PROGRAM_V1.calibrationLocked, true); assert.ok(Object.isFrozen(XAUUSD_REPLICATION_PROGRAM_V1) && XAUUSD_REPLICATION_PROGRAM_HASH.length >= 16); });
test('chunk planner stays below provider point limits and covers the range contiguously', () => { const chunks = planAcquisitionChunks(request()); assert.equal(chunks.length, 2); assert.equal(chunks[0]?.startAt, '2024-01-01T00:00:00.000Z'); assert.equal(chunks[0]?.endAt, chunks[1]?.startAt); assert.equal(chunks.at(-1)?.endAt, '2024-03-01T00:00:00.000Z'); assert.ok(Object.isFrozen(chunks)); });
test('M5 M15 and H1 use independent deterministic chunk plans', () => { const counts = (['M5', 'M15', 'H1'] as const).map((timeframe) => planAcquisitionChunks(request({ timeframe })).length); assert.ok(counts[0] > counts[1] && counts[1] > counts[2]); assert.deepEqual(planAcquisitionChunks(request()), planAcquisitionChunks(request())); });
test('acquirer requests explicit UTC bounded ranges without outputsize and deduplicates boundaries', async () => { const urls: URL[] = [], values = [[row('2024-01-01 00:00:00'), row('2024-02-16 21:00:00')], [row('2024-02-16 21:00:00'), row('2024-02-16 21:15:00')]]; const fetcher = async (url: URL) => { urls.push(new URL(url)); return { ok: true, status: 200, json: async () => ({ meta: { symbol: 'XAU/USD', interval: '15min' }, values: values[urls.length - 1] }) }; }; const result = await new TwelveDataHistoricalAcquirer('secret-not-observed', fetcher).acquire(request()); assert.equal(result.candles.length, 3); assert.equal(new Set(result.candles.map((candle) => candle.openedAt)).size, 3); assert.equal(result.provenance.chunkCount, 2); assert.equal(result.provenance.timezone, 'UTC'); for (const url of urls) { assert.equal(url.searchParams.get('timezone'), 'UTC'); assert.ok(url.searchParams.has('start_date') && url.searchParams.has('end_date')); assert.equal(url.searchParams.has('outputsize'), false); } assert.doesNotMatch(JSON.stringify(result), /secret-not-observed/); });
test('acquirer rejects provider gaps, invalid OHLC, excessive payloads, and conflicting duplicates', async () => { const noData = new TwelveDataHistoricalAcquirer('x', async () => ({ ok: false, status: 400, json: async () => ({ status: 'error', code: 400, message: 'No data is available' }) })); await assert.rejects(() => noData.acquire(request({ endAt: '2024-01-02T00:00:00.000Z' })), (error: unknown) => error instanceof HistoricalAcquisitionError && error.code === 'NO_DATA'); const invalid = new TwelveDataHistoricalAcquirer('x', async () => ({ ok: true, status: 200, json: async () => ({ values: [{ ...row('2024-01-01 00:00:00'), high: 'bad' }] }) })); await assert.rejects(() => invalid.acquire(request({ endAt: '2024-01-02T00:00:00.000Z' })), /invalid OHLC/); });
test('acquisition service validates, certifies, and binds source provenance to an immutable artifact', async () => { const base = Date.parse('2024-01-01T00:00:00Z'), candles = [0, 1, 2].map((index) => ({ openedAt: new Date(base + index * 900_000).toISOString(), closedAt: new Date(base + (index + 1) * 900_000).toISOString(), open: 1999 + index, high: 2002 + index, low: 1998 + index, close: 2000 + index, volume: 10, complete: true })); const acquisitionRequest = request({ endAt: candles.at(-1)!.closedAt }), provenance = { provider: 'Twelve Data' as const, providerSymbol: 'XAU/USD' as const, timezone: 'UTC' as const, timestampConvention: 'BAR_OPEN_UTC' as const, requestedStartAt: acquisitionRequest.startAt, requestedEndAt: acquisitionRequest.endAt, acquiredAt: acquisitionRequest.acquiredAt, chunkCount: 1, requestFingerprint: 'request-fingerprint', maximumPointsPerRequest: 5000 as const }; const service = new ReplicationDatasetAcquisitionService({ acquire: async () => ({ request: acquisitionRequest, candles, chunks: [], provenance, warnings: [] }) }, new HistoricalDatasetManager(new InMemoryHistoricalDatasetRepository(() => acquisitionRequest.acquiredAt))); const artifact = await service.acquireAndCertify(acquisitionRequest, '1.0.0', 'researcher'); assert.equal(artifact.dataset.status, 'CERTIFIED'); assert.equal(artifact.acquisition.requestFingerprint, 'request-fingerprint'); assert.equal(artifact.programId, 'TP-REP-XAUUSD-2026-01'); assert.ok(artifact.certificationHash.length >= 16 && Object.isFrozen(artifact)); });
test('acquisition code is research-only and has no production route, strategy, detector, or calibration coupling', async () => { const fs = await import('node:fs/promises'); for (const file of ['chunk-planner.ts', 'twelve-data-historical-acquirer.ts']) { const source = await fs.readFile(new URL(`../lib/market-intelligence-lab/historical-acquisition/${file}`, import.meta.url), 'utf8'); for (const forbidden of ['buildLiveAnalysis', 'DecisionEngine', 'DetectorRunner', 'ReadinessPolicy', 'Supabase', 'app/api']) assert.doesNotMatch(source, new RegExp(forbidden, 'i')); } });
