import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const migration=read('supabase/migrations/042_historical_decision_reports.sql'),saveRoute=read('app/api/decisions/save-report/route.ts'),validateRoute=read('app/api/validate/route.ts'),marketRoute=read('app/api/market/analyze/route.ts'),history=read('app/history/page.tsx'),historicalRoute=read('app/history/[reportId]/page.tsx'),report=read('components/decision/HistoricalDecisionReport.tsx'),validator=read('components/TradeValidator.tsx'),fingerprint=read('lib/historical-decisions/fingerprint.ts'),schema=read('lib/historical-decisions/schema.ts'),types=read('types/historical-decision.ts'),styles=read('app/trade-police.css');

test('migration makes deterministic reports and AI prose separate, immutable, owner-read-only records',()=>{for(const value of ['decision_reports','decision_report_ai_explanations','decision_report_sources','enable row level security','decision reports select own','decision report ai select own','authoritative boolean not null default false','reject_historical_report_mutation','grant execute on function public.save_decision_report','to service_role'])assert.match(migration,new RegExp(value));assert.match(migration,/revoke all on public\.decision_reports from anon, authenticated/);assert.doesNotMatch(migration,/grant (insert|update|delete|all) on public\.decision_reports to authenticated/i);});
test('market evidence and short-lived sources are server owned',()=>{assert.match(migration,/revoke insert,delete,update on public\.market_scans from authenticated/);assert.match(migration,/server_created boolean not null default false/);assert.match(marketRoute,/createAdminClient\(\).*server_created:true/);assert.match(validateRoute,/scan\.server_created/);assert.match(validateRoute,/expires_at|decision_report_sources/);});
test('save input is references only and cannot carry verdict or evidence',()=>{assert.match(saveRoute,/sourceDecisionId/);assert.match(saveRoute,/idempotencyKey/);assert.doesNotMatch(saveRoute,/z\.object\([^)]*verdict/s);assert.doesNotMatch(saveRoute,/evidence\s*:/);assert.match(validateRoute,/buildHistoricalDecisionSnapshot/);assert.match(validateRoute,/historicalDecisionSnapshotV1Schema\.parse/);});
test('server validation resolves ownership, strategy, scan and overrides automatic evidence',()=>{assert.match(validateRoute,/eq\('user_id',user\.id\)/);assert.match(validateRoute,/scan\.strategy_profile_id!==strategy\.id/);assert.match(validateRoute,/authoritativeAnalysis\.evidence\[key\]\.value/);assert.match(validateRoute,/analysisId: z\.string\(\)\.uuid/);assert.match(validator,/setValue\('analysisId', analysis\?\.analysisId \?\? ''\)/);assert.match(validator,/body\.analysisId=\(fd\.get\('analysisId'\)[^;]+\|\| analysis\?\.analysisId \|\| null/);});
test('database idempotency protects repeated and concurrent saves',()=>{assert.match(migration,/unique \(user_id, source_analysis_id, deterministic_fingerprint\)/);assert.match(migration,/unique \(user_id, idempotency_key\)/);assert.match(migration,/for update/);assert.match(migration,/exception when unique_violation/);assert.match(saveRoute,/duplicate:Boolean/);});
test('fingerprint is canonical, stable in shape, and excludes AI, random report and user identity',()=>{assert.match(fingerprint,/sort\(\(\[a\],\[b\]\)=>a\.localeCompare\(b\)\)/);assert.match(fingerprint,/createHash\('sha256'\)/);for(const excluded of ['deterministicFingerprint','reportId','userId'])assert.match(fingerprint,new RegExp(excluded));assert.doesNotMatch(fingerprint,/ai|prose/i);});
test('schema is strict, versioned from 1.0.0 and unknown versions fail closed',()=>{assert.match(types,/HISTORICAL_DECISION_SCHEMA_VERSION = '1\.0\.0'/);assert.match(schema,/\.strict\(\)/);assert.match(schema,/UNSUPPORTED_VERSION/);assert.match(schema,/isSupportedHistoricalReportVersion/);assert.doesNotMatch(types,/\bany\b/);});
test('AI remains optional, separate and cannot change deterministic fields',()=>{assert.match(validateRoute,/decisionNarrative\.source==='AI_ENHANCED'/);assert.match(validateRoute,/ai_explanation_json:aiExplanation/);assert.match(types,/authoritative: false/);assert.match(migration,/source_deterministic_fingerprint/);assert.match(report,/Plain-language explanation|Saved snapshot integrity|Persisted risk check|Audit ID/);});
test('owner-only historical route reads saved JSON without recomputation',()=>{assert.match(historicalRoute,/from\('decision_reports'\)/);assert.match(historicalRoute,/parseHistoricalDecisionSnapshot/);assert.match(historicalRoute,/notFound\(\)/);for(const forbidden of ['market-data','market-analysis','decision-engine','trading-dna','buildDecisionExplanation'])assert.doesNotMatch(historicalRoute,new RegExp(forbidden));assert.doesNotMatch(historicalRoute,/fetch\(/);});
test('historical report keeps original identity, provenance and warning state without recomputing',()=>{for(const value of ['HISTORICAL SNAPSHOT','Original decision','Report ID','Saved at','Revision','Provider','Original candle','Primary reason|decision-primary-reason','Next action','Persisted risk check|No trade outcome or realized R was persisted with this report','Audit ID','not updated with later market data'])assert.match(report,new RegExp(value,'i'));});
test('history is a saved-snapshot archive with filters and stable limit',()=>{for(const value of ['decision_reports','verdict','instrument','strategy_id','created_at','limit\\(100\\)','Historical snapshots are never recalculated','Review past decisions and outcomes'])assert.match(history,new RegExp(value));assert.match(history,/filters\.verdict|filters\.instrument|filters\.strategy|name="q"/);assert.doesNotMatch(history,/buildDecisionExplanation|validateTradeWithStrategy|liveAnalysisConfidence|direction/);});

test('history rows use real saved report fields and gracefully degrade missing data',()=>{const page=read('app/history/page.tsx');assert.match(page,/id,created_at,instrument,timeframe,strategy_id,strategy_name,verdict,primary_reason,data_freshness/);assert.match(page,/Strategy not saved/);assert.match(page,/No saved decisions yet/);assert.doesNotMatch(page,/realized_r|result_r|take_profit|stop_loss|direction/);});

test('historical detail pages preserve provenance and omit fabricated chart/outcome claims',()=>{const reportPage=read('app/history/[reportId]/page.tsx');const reportComponent=read('components/decision/HistoricalDecisionReport.tsx');assert.match(reportPage,/Return to History|All saved reports/);assert.match(reportComponent,/Original decision|Historical context|No trade outcome or realized R was persisted with this report./);assert.match(reportComponent,/This saved report does not include a historical chart replay/);assert.doesNotMatch(reportComponent,/market analyze|\/api\/market\/analyze|fetch\(/);});
test('save UX separates report save from trade recording and handles all states accessibly',()=>{for(const value of ['Save Decision Report','does not run another analysis','additional analysis usage','saving','saved','error','duplicate','Open saved report','Report ID','aria-live="polite"','reportSaveStatusRef.*focus'])assert.match(validator,new RegExp(value,'s'));assert.match(validator,/Take Trade/);assert.match(validator,/Take Anyway/);assert.match(validator,/fetch\('\/api\/trades\/take'/);assert.match(validator,/sourceDecisionId:result\.reportSourceId/);});
test('save failures and expired sessions expose no database details',()=>{assert.match(saveRoute,/Your session expired/);assert.match(saveRoute,/no additional analysis was used/);assert.doesNotMatch(saveRoute,/return apiError\([^)]*error\.message/);assert.match(saveRoute,/console\.error/);});
test('mobile, print and overflow rules keep the full-page report usable',()=>{assert.match(styles,/@media\(max-width:600px\)/);assert.match(styles,/\.historical-card\{grid-template-columns:1fr\}/);assert.match(styles,/report-fingerprint\{word-break:break-all/);assert.match(styles,/@media print/);assert.match(styles,/width:100%/);});
test('historical documentation covers ownership, privacy, rollback and known limitations',()=>{const doc=read('docs/HISTORICAL_DECISION_REPORTS.md');for(const value of ['server-owned','Schema `1.0.0`','idempotency','AI','Data minimization','retention','Migration','rollback','Known limitations'])assert.match(doc,new RegExp(value,'i'));});
