import assert from 'node:assert/strict';
import test from 'node:test';
import { HistoricalDatasetManager, InMemoryHistoricalDatasetRepository, type HistoricalDatasetImport } from '../lib/market-intelligence-lab/historical-datasets/index.ts';
import { HistoricalReplayError, HistoricalReplayProviderFactory } from '../lib/market-intelligence-lab/historical-replay/index.ts';
import { MarketDataGateway } from '../lib/market-intelligence/providers/gateway.ts';
import { ProviderRegistry } from '../lib/market-intelligence/providers/provider-registry.ts';

const start = Date.parse('2024-01-02T00:00:00.000Z');
const candles = Array.from({ length: 12 }, (_, index) => ({ openedAt: new Date(start + index * 900_000).toISOString(), closedAt: new Date(start + (index + 1) * 900_000).toISOString(), open: 2000 + index, high: 2002 + index, low: 1999 + index, close: 2001 + index, volume: 100 + index, complete: true }));
const input: HistoricalDatasetImport = { name: 'Gold replay fixture', version: '1.0.0', instrument: 'XAUUSD', assetClass: 'METALS', timeframe: 'M15', provider: 'fixture', createdBy: 'researcher-1', candles };
const request = (overrides = {}) => ({ instrument: 'XAUUSD', timeframe: 'M15', candleCount: 3, includeCurrentPrice: true, includeSpread: false, allowCached: false, maximumDataAge: 900_000, requestedAt: candles[5]!.closedAt, ...overrides });
async function fixture() { const repository = new InMemoryHistoricalDatasetRepository(() => '2026-07-21T00:00:00.000Z'), manager = new HistoricalDatasetManager(repository), imported = await manager.importDataset(input); return { repository, manager, imported }; }

test('factory permits only certified datasets', async () => { const { repository, manager, imported } = await fixture(), factory = new HistoricalReplayProviderFactory(repository); await assert.rejects(() => factory.create(imported.id), (error: unknown) => error instanceof HistoricalReplayError && error.code === 'DATASET_NOT_CERTIFIED'); await manager.validate(imported.id); await assert.rejects(() => factory.create(imported.id), /CERTIFIED/); await manager.certify(imported.id); assert.equal((await factory.create(imported.id)).provenance.datasetCertification, 'CERTIFIED'); });
test('replay is strictly no-lookahead and returns the last requested completed candles', async () => { const { repository, manager, imported } = await fixture(); await manager.validate(imported.id); await manager.certify(imported.id); const provider = await new HistoricalReplayProviderFactory(repository).create(imported.id), result = await provider.fetchSnapshot(request()); assert.deepEqual(result.candles.map((item) => item.timestamp), candles.slice(3, 6).map((item) => item.openedAt)); assert.equal(result.currentPrice, candles[5]!.close); assert.equal(result.receivedAt, candles[5]!.closedAt); const beforeClose = new Date(Date.parse(candles[5]!.closedAt) - 1).toISOString(), prior = await provider.fetchSnapshot(request({ requestedAt: beforeClose })); assert.equal(prior.candles.at(-1)?.timestamp, candles[4]!.openedAt); });
test('replay rejects insufficient history and dataset mismatches with typed errors', async () => { const { repository, manager, imported } = await fixture(); await manager.validate(imported.id); await manager.certify(imported.id); const provider = await new HistoricalReplayProviderFactory(repository).create(imported.id); await assert.rejects(() => provider.fetchSnapshot(request({ candleCount: 7 })), (error: unknown) => error instanceof HistoricalReplayError && error.code === 'INSUFFICIENT_HISTORY'); await assert.rejects(() => provider.fetchSnapshot(request({ instrument: 'EURUSD' })), /contains XAUUSD/); await assert.rejects(() => provider.fetchSnapshot(request({ timeframe: 'H1' })), /contains M15/); });
test('provider exposes frozen provenance, deterministic health, and honest spread availability', async () => { const { repository, manager, imported } = await fixture(); await manager.validate(imported.id); const certified = await manager.certify(imported.id), provider = await new HistoricalReplayProviderFactory(repository).create(imported.id), health = await provider.health(), result = await provider.fetchSnapshot(request({ includeSpread: true })); assert.equal(provider.provenance.datasetId, imported.id); assert.equal(provider.provenance.datasetHash, imported.contentHash); assert.equal(provider.provenance.noLookahead, true); assert.ok(Object.isFrozen(provider.provenance)); assert.equal(health.checkedAt, certified.certifiedAt); assert.equal(result.spread, undefined); assert.match(result.warnings[0]!, /does not contain spread/); });
test('gateway integration creates immutable, byte-stable snapshots without production wiring', async () => { const { repository, manager, imported } = await fixture(); await manager.validate(imported.id); await manager.certify(imported.id); const provider = await new HistoricalReplayProviderFactory(repository).create(imported.id), gateway = new MarketDataGateway(new ProviderRegistry().register(provider).freeze()), first = await gateway.fetchSnapshot(provider.id, request()), second = await gateway.fetchSnapshot(provider.id, request()); assert.deepEqual(first, second); assert.equal(first.provider, 'historical-replay'); assert.equal(first.providerVersion, '1.0.0'); assert.equal(first.candles.length, 3); assert.ok(Object.isFrozen(first) && Object.isFrozen(first.candles)); });
test('historical replay remains research-only and contains no network, clock, database, route, or engine coupling', async () => { const fs = await import('node:fs/promises'); for (const file of ['historical-replay-provider.ts', 'historical-replay-factory.ts']) { const source = await fs.readFile(new URL(`../lib/market-intelligence-lab/historical-replay/${file}`, import.meta.url), 'utf8'); for (const forbidden of ['fetch(', 'Date.now', 'Supabase', 'buildLiveAnalysis', 'DecisionEngine', 'app/api']) assert.doesNotMatch(source, new RegExp(forbidden.replace('(', '\\('), 'i')); } });
