import assert from 'node:assert/strict';
import test from 'node:test';
import { AnalysisContextBuilder } from '../lib/market-intelligence/analysis/analysis-context-builder.ts';
import type { BreakOfStructureObservation, LiquiditySweepObservation, MarketDataSnapshot, NormalizedCandle, RangeLevelsObservation } from '../lib/market-intelligence/contracts.ts';
import { composeLegacyChoch, composeLegacyPremiumDiscount, FullPipelineValidator, LEGACY_PIPELINE_AUDIT } from '../lib/market-intelligence/pipeline-validation/index.ts';
import type { MultiTimeframeAnalysisSnapshot, PipelineFinalProjection } from '../lib/market-intelligence/pipeline-validation/pipeline-types.ts';
import { createDetectorRegistry } from '../lib/market-intelligence/registry/bootstrap.ts';
import { DetectorRunner } from '../lib/market-intelligence/runner/detector-runner.ts';

const ids=['atr','trend','range-levels','break-of-structure','liquidity-sweep','fair-value-gap','rejection-candle','volume-expansion','displacement','volatility-requirement','retest'];
const base=Date.parse('2026-10-01T00:00:00Z'),requestedAt=new Date(base+40*3_600_000).toISOString();
const candle=(index:number,offset=0):NormalizedCandle=>({openedAt:new Date(base+index*3_600_000).toISOString(),closedAt:new Date(base+(index+1)*3_600_000).toISOString(),open:100+index+offset,high:102+index+offset,low:98+index+offset,close:100+index+offset,volume:100+index,complete:true});
const snapshot=(id:string,timeframe:string,offset=0):MarketDataSnapshot=>{const candles=Array.from({length:30},(_,index)=>candle(index,offset));return{id,snapshotVersion:'1',provider:'fixture',providerVersion:'1',providerSymbol:'XAU/USD',instrument:'XAUUSD',timeframe,requestedAt,receivedAt:requestedAt,dataAsOf:candles.at(-1)!.openedAt,freshness:{state:'FRESH',dataAsOf:candles.at(-1)!.openedAt,ageMs:0,maximumAgeMs:60_000},candles,validationWarnings:[]};};
const final:PipelineFinalProjection={evidence:{bosConfirmed:true,chochConfirmed:false},liveAnalysisConfidence:50,readinessPercentage:50,readinessState:'NOT_READY',analysisStatus:'VALID_ANALYSIS',blockers:['choch'],reasons:['BOS matched.']};
const build=async(source:MarketDataSnapshot)=>new AnalysisContextBuilder({now:()=>requestedAt}).build(source,await new DetectorRunner(createDetectorRegistry(),{createRunId:()=>`run-${source.id}`}).execute(source,ids));
async function bundle(withFinal=true):Promise<MultiTimeframeAnalysisSnapshot>{const confirmation=snapshot('confirmation','H1'),entry=snapshot('entry','M15',10),trigger=snapshot('trigger','M5',20);return{symbol:'XAUUSD',requestedAt,strategyId:'gold',strategyVersion:1,direction:'BUY',aligned:true,snapshots:{confirmation,entry,trigger},newContexts:{confirmation:await build(confirmation),entry:await build(entry),trigger:await build(trigger)},...(withFinal?{legacyFinal:final,newFinal:structuredClone(final)}:{})};}

test('legacy audit maps every production category and flags strategy ownership',()=>{assert.ok(LEGACY_PIPELINE_AUDIT.length>=18);assert.ok(LEGACY_PIPELINE_AUDIT.every((item)=>item.legacyField&&item.sourceCalculation&&item.parityStatus));assert.ok(LEGACY_PIPELINE_AUDIT.some((item)=>item.parityStatus==='STRATEGY_LAYER_REQUIRED'&&item.productionInfluencing));assert.ok(LEGACY_PIPELINE_AUDIT.some((item)=>item.legacyField==='calculatedAt'&&item.parityStatus==='NON_DETERMINISTIC'&&!item.productionInfluencing));});

test('premium/discount preserves BUY strictness and SELL equality asymmetry',()=>{const levels={recentHigh:110,recentLow:90} as RangeLevelsObservation;assert.equal(composeLegacyPremiumDiscount('BUY',levels,101),true);assert.equal(composeLegacyPremiumDiscount('BUY',levels,100),false);assert.equal(composeLegacyPremiumDiscount('SELL',levels,100),true);assert.equal(composeLegacyPremiumDiscount('SELL',levels,101),false);assert.equal(composeLegacyPremiumDiscount(null,levels,90),false);});

test('legacy ChoCH ORs timeframe sources and permits sweep/BOS on different frames',()=>{const sweep={lowSideSweep:true,highSideSweep:false} as LiquiditySweepObservation,bos={bullishBreak:true,bearishBreak:false} as BreakOfStructureObservation;const result=composeLegacyChoch('BUY',[{timeframe:'H1',sweep,bos:null},{timeframe:'M15',sweep:null,bos}]);assert.equal(result.chochConfirmed,true);assert.deepEqual(result.directionalSweep.timeframes,['H1']);assert.deepEqual(result.directionalBos.timeframes,['M15']);assert.equal(composeLegacyChoch(null,[{timeframe:'H1',sweep,bos}]).chochConfirmed,false);});

test('complete projections match at all three levels and can become migration-ready',async()=>{const input=await bundle(),before=JSON.stringify(input),report=new FullPipelineValidator().validate(input);assert.equal(report.snapshotIdentityValid,true);assert.ok(report.observationComparisons.every((item)=>item.status==='MATCH'));assert.ok(report.compositionComparisons.every((item)=>item.status==='MATCH'));assert.ok(report.finalOutputComparisons.every((item)=>item.status==='MATCH'));assert.equal(report.migrationReady,true);assert.equal(report.overallStatus,'MATCH');assert.equal(report.generatedAt,requestedAt);assert.equal(JSON.stringify(input),before);assert.ok(Object.isFrozen(report));assert.deepEqual(JSON.parse(JSON.stringify(report)),report);});

test('missing independent final projection blocks readiness conservatively',async()=>{const report=new FullPipelineValidator().validate(await bundle(false));assert.equal(report.migrationReady,false);assert.equal(report.overallStatus,'BLOCKED');assert.equal(report.nonComparableCount,1);assert.ok(report.migrationBlockers.some((item)=>item.includes('final scoring')));});

test('final mismatch is critical and snapshot mismatch is an error',async()=>{const input=await bundle();input.newFinal={...final,readinessPercentage:49};let report=new FullPipelineValidator().validate(input);assert.equal(report.overallStatus,'MISMATCH');assert.equal(report.migrationReady,false);assert.ok(report.criticalMismatchCount>0);const wrong={...input,newContexts:{...input.newContexts,entry:{...input.newContexts.entry,snapshotId:'wrong'}}};report=new FullPipelineValidator().validate(wrong);assert.equal(report.snapshotIdentityValid,false);assert.equal(report.overallStatus,'ERROR');});

test('trigger timeframe is optional and production isolation is structural',async()=>{const input=await bundle();delete input.snapshots.trigger;delete input.newContexts.trigger;const report=new FullPipelineValidator().validate(input);assert.equal(report.snapshotIdentityValid,true);assert.ok(report.observationComparisons.every((item)=>item.timeframe!=='M5'));assert.doesNotMatch(JSON.stringify(report),/AUTHORIZED|REJECTED|takeProfit|stopLoss/);});

test('insufficient data and malformed input block readiness with explicit categories',async()=>{let input=await bundle();input.snapshots.entry={...input.snapshots.entry,candles:input.snapshots.entry.candles.slice(0,7)};input.newContexts.entry=await build(input.snapshots.entry);let report=new FullPipelineValidator().validate(input);assert.equal(report.migrationReady,false);assert.ok(report.unavailableCount>0);input=await bundle();input.snapshots.entry.candles[0]={...input.snapshots.entry.candles[0],high:Number.NaN};input.newContexts.entry=await build(input.snapshots.entry);report=new FullPipelineValidator().validate(input);assert.equal(report.overallStatus,'ERROR');assert.equal(report.migrationReady,false);assert.ok(report.migrationBlockers.some((item)=>item.includes('ERROR')));});

test('incomplete latest candles are excluded identically and composition mismatches are critical',async()=>{const input=await bundle();const tail={...candle(30,999),complete:false,closedAt:new Date(base+50*3_600_000).toISOString()};input.snapshots.entry={...input.snapshots.entry,candles:[...input.snapshots.entry.candles,tail]};input.newContexts.entry=await build(input.snapshots.entry);let report=new FullPipelineValidator().validate(input);assert.ok(report.observationComparisons.filter((item)=>item.timeframe==='M15').every((item)=>item.status==='MATCH'));input.direction='SELL';report=new FullPipelineValidator().validate(input);assert.ok(report.compositionComparisons.every((item)=>item.status==='MATCH'));const altered={...input,newContexts:{...input.newContexts,entry:{...input.newContexts.entry,detectorResults:input.newContexts.entry.detectorResults.map((result)=>result.detectorId==='range-levels'?{...result,payload:{...(result.payload as object),recentHigh:999}}:result)}}};report=new FullPipelineValidator().validate(altered);assert.equal(report.migrationReady,false);assert.ok(report.criticalMismatchCount>0);});
