import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';
const read=(path:string)=>readFileSync(new URL(`../${path}`,import.meta.url),'utf8');
const migration=read('supabase/migrations/043_private_beta_operational_observability.sql'),cleanup=read('app/api/operations/decision-sources/cleanup/route.ts'),health=read('app/api/hq/health/route.ts'),audit=read('app/api/hq/historical-reports/audit/route.ts'),failure=read('lib/historical-decisions/operations.ts'),save=read('app/api/decisions/save-report/route.ts'),registry=read('lib/historical-decisions/version-registry.ts'),schema=read('lib/historical-decisions/schema.ts'),events=read('lib/beta-intelligence.ts'),eventRoute=read('app/api/beta-intelligence/events/route.ts'),webhook=read('app/api/billing/webhook/route.ts'),docs=read('docs/PRIVATE_BETA_OPERATIONS.md'),vercel=read('vercel.json');

test('cleanup targets only expired short-lived sources and preserves completed reports',()=>{assert.match(migration,/delete from public\.decision_report_sources where expires_at<=now\(\)/);assert.doesNotMatch(migration,/delete from public\.decision_reports/);assert.doesNotMatch(cleanup,/from\('decision_reports'\).*delete/s);assert.match(cleanup,/reportsDeleted:0/);});
test('cleanup is idempotent and dry run never deletes',()=>{assert.match(migration,/if not p_dry_run then\s+delete from public\.decision_report_sources/s);assert.match(migration,/where expires_at<=now\(\)/);assert.match(cleanup,/dryRun/);assert.match(cleanup,/p_dry_run:dryRun/);});
test('cleanup requires a configured cron bearer secret and constant-time comparison',()=>{for(const value of ['CRON_SECRET','authorization','Bearer ','timingSafeEqual','UNAUTHORIZED','CLEANUP_NOT_CONFIGURED'])assert.match(cleanup,new RegExp(value));assert.match(vercel,/api\/operations\/decision-sources\/cleanup/);});
test('cleanup records counts without customer content',()=>{for(const value of ['decision_source_cleanup_runs','expired_count','deleted_count','dry_run','ran_at'])assert.match(migration,new RegExp(value));assert.doesNotMatch(migration,/decision_source_cleanup_runs[\s\S]{0,400}(snapshot_json|evidence|prompt|provider_payload)/i);});
test('save failures use only the sanitized allowlisted operational contract',()=>{for(const code of ['AUTHENTICATION_FAILED','SOURCE_EXPIRED','SOURCE_NOT_FOUND','STRATEGY_REVISION_MISMATCH','FINGERPRINT_FAILURE','DATABASE_UNAVAILABLE','IDEMPOTENCY_CONFLICT','UNKNOWN_SAFE_ERROR']){assert.match(migration,new RegExp(code));assert.match(failure,new RegExp(code))}for(const field of ['request_id','user_id','source_analysis_id','retryable','occurred_at'])assert.match(migration,new RegExp(field));assert.doesNotMatch(migration,/decision_report_operational_failures[\s\S]{0,700}(snapshot_json|evidence|ai_prompt|provider_payload|secret)/i);});
test('save route distinguishes source lifecycle, database and idempotency failures without raw errors',()=>{for(const code of ['AUTHENTICATION_FAILED','SOURCE_EXPIRED','SOURCE_NOT_FOUND','DATABASE_UNAVAILABLE','IDEMPOTENCY_CONFLICT'])assert.match(save,new RegExp(code));assert.doesNotMatch(save,/error\.message|JSON\.stringify\(error|return apiError\([^)]*error/);assert.match(migration,/errcode='TP409'/);});
test('health and schema audit endpoints remain authenticated HQ-only',()=>{for(const source of [health,audit]){assert.match(source,/auth\.getUser/);assert.match(source,/has_staff_permission/);assert.match(source,/system\.health/);assert.match(source,/status:403|FORBIDDEN/)}});
test('HQ health uses the required operational states and never returns secret values',()=>{for(const state of ['HEALTHY','DEGRADED','UNAVAILABLE'])assert.match(health,new RegExp(state));for(const capability of ['supabase','marketDataProvider','billingConfiguration','historicalReportPersistence','expiredSourceBacklog','recentSanitizedIncidents'])assert.match(health,new RegExp(capability));assert.doesNotMatch(health,/const payload=.*(process\.env|billingConfig\(\))/s);});
test('schema registry supports 1.0.0 and unknown versions retain safe unsupported handling',()=>{assert.match(registry,/HISTORICAL_DECISION_SCHEMA_VERSION/);assert.match(registry,/SUPPORTED/);assert.match(schema,/isSupportedHistoricalReportVersion/);assert.match(schema,/UNSUPPORTED_VERSION/);assert.match(audit,/dryRun:true/);assert.match(audit,/migratedCount:0/);});
test('schema audit counts versions without mutating reports',()=>{assert.match(migration,/schemaVersions/);assert.match(migration,/group by schema_version/);assert.doesNotMatch(audit,/update\(|delete\(|insert\(/);});
test('beta metrics cover the requested lifecycle with no trading or payment metadata',()=>{for(const event of ['SIGNUP_COMPLETED','ONBOARDING_COMPLETED','STRATEGY_SAVED','FIRST_ANALYSIS_COMPLETED','DECISION_REPORT_OPENED','DECISION_REPORT_SAVED','SAVED_REPORT_REOPENED','UPGRADE_INITIATED','CHECKOUT_COMPLETED'])assert.match(migration,new RegExp(event));for(const event of ['STRATEGY_SAVED','DECISION_REPORT_OPENED','UPGRADE_INITIATED']){assert.match(events,new RegExp(event));assert.match(eventRoute,new RegExp(event))}assert.match(webhook,/CHECKOUT_COMPLETED/);assert.doesNotMatch(migration,/beta_intelligence_events[\s\S]{0,500}(evidence|payment_details|stripe_payload|provider_payload)/i);});
test('documentation covers scheduling monitoring incidents schema policy and metrics',()=>{for(const value of ['Cleanup scheduling','Operational monitoring','incident codes','Schema-version policy','beta metrics','CRON_SECRET','dry-run'])assert.match(docs,new RegExp(value,'i'));});
