import assert from 'node:assert/strict';
import test from 'node:test';
import { AnalysisContextBuilder } from '../lib/market-intelligence/analysis/analysis-context-builder.ts';
import type { DetectorResult, MarketDataSnapshot, NormalizedCandle } from '../lib/market-intelligence/contracts.ts';
import { RetestDetector } from '../lib/market-intelligence/detectors/retest/retest-detector.ts';
import { calculateLegacyRetest, isLegacyRetest } from '../lib/market-intelligence/detectors/retest/retest-utils.ts';
import { createDetectorRegistry } from '../lib/market-intelligence/registry/bootstrap.ts';
import { DetectorRegistry } from '../lib/market-intelligence/registry/detector-registry.ts';
import { DetectorRunner } from '../lib/market-intelligence/runner/detector-runner.ts';
import { ShadowValidator } from '../lib/market-intelligence/shadow-validation/shadow-validator.ts';

const base = Date.parse('2026-09-01T00:00:00.000Z');
const candle = (index: number, close: number, high = close + 1, low = close - 1): NormalizedCandle => ({ openedAt: new Date(base + index * 3_600_000).toISOString(), closedAt: new Date(base + (index + 1) * 3_600_000).toISOString(), open: close, high, low, close, volume: 100, complete: true });
const bullish = () => Array.from({ length: 24 }, (_, index) => candle(index, 100 + index));
const bearish = () => Array.from({ length: 24 }, (_, index) => candle(index, 123 - index));
const range = (price = 100) => Array.from({ length: 24 }, (_, index) => candle(index, price, price, price));
const snapshot = (candles: NormalizedCandle[], timeframe = 'H1'): MarketDataSnapshot => { const requestedAt = new Date(base + Math.max(1, candles.length) * 3_600_000).toISOString(); return { id: `retest-${timeframe}`, snapshotVersion: '1.0.0', provider: 'fixture', providerVersion: '1', providerSymbol: 'XAU/USD', instrument: 'XAUUSD', timeframe, requestedAt, receivedAt: requestedAt, dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, freshness: { state: 'FRESH', dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, ageMs: 0, maximumAgeMs: 60_000 }, candles, validationWarnings: [] }; };

test('bullish, bearish, and RANGE retests preserve target selection', () => { const up = calculateLegacyRetest('H1', bullish())!, down = calculateLegacyRetest('H1', bearish())!, flat = calculateLegacyRetest('H1', range())!; assert.equal(up.trendBias, 'BULLISH'); assert.equal(up.targetLevel, up.recentHigh); assert.equal(up.retestDetected, true); assert.equal(down.trendBias, 'BEARISH'); assert.equal(down.targetLevel, down.recentLow); assert.equal(down.retestDetected, true); assert.equal(flat.trendBias, 'RANGE'); assert.equal(flat.targetLevel, flat.recentLow); assert.equal(flat.retestDetected, true); });

test('outside tolerance is not a retest and exact equality qualifies', () => { const values = bullish(); values[23] = candle(23, 140, 141, 139); const outside = calculateLegacyRetest('H1', values)!; assert.equal(outside.classification, 'NO_RETEST'); assert.equal(isLegacyRetest(1, 1), true); assert.equal(isLegacyRetest(1.0000001, 1), false); });

test('ATR-dominant and price-dominant tolerance preserve max formula', () => { const atrDominant = calculateLegacyRetest('H1', bullish())!; assert.equal(atrDominant.tolerance, atrDominant.atrTolerance); assert.ok(atrDominant.atrTolerance > atrDominant.priceTolerance); const priceDominant = calculateLegacyRetest('H1', range(100_000))!; assert.equal(priceDominant.tolerance, priceDominant.priceTolerance); assert.ok(priceDominant.priceTolerance > priceDominant.atrTolerance); });

test('observation exposes exact windows and ATR metadata', () => { const result = calculateLegacyRetest('H1', bullish())!; assert.equal(result.candleCount, 24); assert.equal(result.atrCandleCount, 15); assert.equal(result.trueRangeCount, 14); assert.equal(result.recentWindowSize, 7); assert.equal(result.atrPeriod, 14); assert.equal(result.atrSmoothingMethod, 'SIMPLE'); assert.equal(result.sourceStartTime, bullish()[0].openedAt); assert.equal(result.eventCandleTime, bullish()[23].openedAt); });

test('latest completed candle selection excludes an incomplete tail', async () => { const values = bullish(), incomplete = { ...candle(24, 500), complete: false, closedAt: new Date(base + 26 * 3_600_000).toISOString() }; const result = await new RetestDetector().execute(snapshot([...values, incomplete])); assert.equal(result.payload?.eventCandleTime, values.at(-1)!.openedAt); assert.equal(result.payload?.currentClose, values.at(-1)!.close); });

test('insufficient history is explicit', async () => { const result = await new RetestDetector().execute(snapshot(bullish().slice(1))); assert.equal(result.status, 'INSUFFICIENT_DATA'); assert.equal(result.payload, null); });

test('malformed OHLC, impossible geometry, timestamps, and ordering return ERROR', async () => { const fixtures: Array<[NormalizedCandle[], string]> = []; const nan = bullish(); nan[0] = { ...nan[0], high: Number.NaN }; fixtures.push([nan, 'INVALID_OHLC']); const geometry = bullish(); geometry[0] = { ...geometry[0], low: geometry[0].high + 1 }; fixtures.push([geometry, 'IMPOSSIBLE_CANDLE_GEOMETRY']); const timestamp = bullish(); timestamp[0] = { ...timestamp[0], closedAt: 'bad' }; fixtures.push([timestamp, 'INVALID_TIMESTAMP']); const duplicate = bullish(); duplicate[1] = { ...duplicate[1], openedAt: duplicate[0].openedAt }; fixtures.push([duplicate, 'INVALID_CANDLE_ORDER']); for (const [values, code] of fixtures) { const result = await new RetestDetector().execute(snapshot(values)); assert.equal(result.status, 'ERROR'); assert.equal(result.errorCode, code); } });

test('metadata, registry, runner, context, shadow parity, JSON, and immutability integrate', async () => { const detector = new RetestDetector(); assert.deepEqual({ id: detector.id, version: detector.version, displayName: detector.displayName, deterministic: detector.deterministic, supportsReplay: detector.metadata.supportsReplay, experimental: detector.metadata.experimental, enabledByDefault: detector.metadata.enabledByDefault }, { id: 'retest', version: '1.0.0', displayName: 'Retest Detector', deterministic: true, supportsReplay: true, experimental: true, enabledByDefault: true }); assert.ok(createDetectorRegistry().exists('retest')); const source = snapshot(bullish()), before = JSON.stringify(source), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze(), { createRunId: () => 'retest-run' }).execute(source, ['retest']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary), beforeContext = JSON.stringify(context), comparison = new ShadowValidator().validate(source, context).comparisons.find((item) => item.detectorId === 'retest'); assert.equal(comparison?.status, 'MATCH'); assert.equal(comparison?.exactMatch, true); assert.equal(JSON.stringify(source), before); assert.equal(JSON.stringify(context), beforeContext); assert.deepEqual(JSON.parse(JSON.stringify(context)), context); assert.doesNotMatch(JSON.stringify(summary.detectorResults[0]), /BUY|SELL|strategy|risk|readiness|entry|stopLoss|takeProfit|orderBlock|choch|decision/i); });

test('wrong target, tolerance, boundary result, or RANGE behavior produces shadow mismatch', async () => { const source = snapshot(range()), detector = new RetestDetector(), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze()).execute(source, ['retest']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary); const patches: Array<Record<string, string | number | boolean>> = [{ targetLevel: 999 }, { tolerance: 999 }, { classification: 'NO_RETEST', retestDetected: false }, { trendBias: 'BULLISH', targetLevel: 999 }]; for (const payloadPatch of patches) { const wrong = context.detectorResults.map((result): DetectorResult => ({ ...result, payload: { ...(result.payload as object), ...payloadPatch } })); assert.equal(new ShadowValidator().validate(source, { ...context, detectorResults: wrong }).comparisons.find((item) => item.detectorId === 'retest')?.status, 'MISMATCH'); } });
