import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import type Stripe from 'stripe';
import {safeStripeReason,StripeBillingError,validateProPrice,validateSubscriptionPrice} from '../lib/billing/stripe-verification.ts';
import {resolveCustomerBinding} from '../lib/billing/webhook-security.ts';
const read=(path:string)=>fs.readFileSync(path,'utf8');
const userA='11111111-1111-4111-8111-111111111111',userB='22222222-2222-4222-8222-222222222222';
function price(overrides:Record<string,unknown>={}):Stripe.Price{return {id:'price_pro',active:true,currency:'usd',livemode:false,product:{id:'prod_pro',object:'product',active:true},recurring:{interval:'month',interval_count:1},type:'recurring',unit_amount:2900,...overrides} as unknown as Stripe.Price}
function subscription(itemPrice=price()):Stripe.Subscription{return {id:'sub_pro',created:1,customer:'cus_a',items:{data:[{price:itemPrice}]},metadata:{tradePoliceUserId:userA},status:'active',cancel_at_period_end:false} as unknown as Stripe.Subscription}

test('configured Pro Price exact contract is accepted',()=>assert.deepEqual(validateProPrice(price(),'price_pro','sk_test_example'),{priceId:'price_pro',productId:'prod_pro',livemode:false,plan:'PRO',interval:'monthly',amount:2900}));
for(const [name,change] of [['inactive',{active:false}],['wrong currency',{currency:'eur'}],['wrong amount',{unit_amount:3000}],['non-monthly',{recurring:{interval:'year',interval_count:1}}]] as const)test(`${name} configured Price is rejected`,()=>assert.throws(()=>validateProPrice(price(change as Record<string,unknown>),'price_pro','sk_test_example'),(error:any)=>error.code==='PRICE_CONFIGURATION_INVALID'));
test('missing expanded product is rejected',()=>assert.throws(()=>validateProPrice(price({product:'prod_pro'}),'price_pro','sk_test_example'),StripeBillingError));
test('Test and Live mode mismatch is rejected in both directions',()=>{assert.throws(()=>validateProPrice(price({livemode:true}),'price_pro','sk_test_example'),(error:any)=>error.code==='STRIPE_MODE_MISMATCH');assert.throws(()=>validateProPrice(price(),'price_pro','sk_live_example'),(error:any)=>error.code==='STRIPE_MODE_MISMATCH')});
test('subscription grants only for the exact configured Price contract',()=>assert.doesNotThrow(()=>validateSubscriptionPrice(subscription(),{priceId:'price_pro',productId:'prod_pro',livemode:false,plan:'PRO',interval:'monthly',amount:2900})));
test('unexpected subscription Price never qualifies',()=>assert.throws(()=>validateSubscriptionPrice(subscription(price({id:'price_other'})),{priceId:'price_pro',productId:'prod_pro',livemode:false,plan:'PRO',interval:'monthly',amount:2900}),(error:any)=>error.code==='UNEXPECTED_SUBSCRIPTION_PRICE'));
test('existing customer binding outranks absent metadata',()=>assert.deepEqual(resolveCustomerBinding('cus_a',undefined,{userId:userA,customerId:'cus_a'},null),{userId:userA,initialize:false}));
test('metadata conflict never replaces an existing customer binding',()=>assert.throws(()=>resolveCustomerBinding('cus_a',userB,{userId:userA,customerId:'cus_a'},{userId:userB,customerId:'cus_b'}),(error:any)=>error.code==='METADATA_USER_MISMATCH'));
test('unknown customer requires valid user metadata',()=>assert.throws(()=>resolveCustomerBinding('cus_new',undefined,null,null),(error:any)=>error.code==='UNKNOWN_STRIPE_CUSTOMER'));
test('same Stripe customer cannot bind to a second user customer',()=>assert.throws(()=>resolveCustomerBinding('cus_new',userA,null,{userId:userA,customerId:'cus_a'}),(error:any)=>error.code==='STRIPE_CUSTOMER_USER_CONFLICT'));
test('metadata initializes only a conflict-free binding',()=>assert.deepEqual(resolveCustomerBinding('cus_new',userA,null,null),{userId:userA,initialize:true}));
test('checkout validates Price before creating customer or Session',()=>{const source=read('app/api/billing/checkout/route.ts');assert.ok(source.indexOf('getValidatedProPrice()')<source.indexOf('customers.create'));assert.match(source,/price:verifiedPrice\.priceId/);assert.doesNotMatch(source,/publishableKey/)});
test('webhook verifies Price, mode, customer binding, and authoritative subscription',()=>{const source=read('app/api/billing/webhook/route.ts');for(const token of ['validateSubscriptionPrice','event.livemode!==verifiedPrice.livemode','bindingFor','subscriptions.retrieve(subscriptionId)','invalid_price'])assert.ok(source.includes(token),token)});
test('atomic claim migration supports claim, duplicate, stale recovery, failure retry and completion',()=>{const migration=read('supabase/migrations/041_stripe_entitlement_hardening.sql');for(const token of ["'PROCESSING'","'PROCESSED'","'FAILED'",'on conflict(event_id) do nothing',"processing_status='FAILED'",'attempt_count=attempt_count+1',"interval '5 minutes'"])assert.ok(migration.includes(token),token);assert.match(read('supabase/migrations/039_secure_stripe_billing.sql'),/event_id text primary key/i)});
test('failed processing is retryable while completed duplicate is safe',()=>{const source=read('app/api/billing/webhook/route.ts');assert.match(source,/claim==='PROCESSED'.+duplicate:true/);assert.match(source,/claim==='PROCESSING'.+409/);assert.match(source,/acknowledge\?'PROCESSED':'FAILED'/);assert.match(source,/WEBHOOK_PROCESSING_FAILED.+500/s)});
test('older invoice cannot restore a missing subscription',()=>{const source=read('app/api/billing/webhook/route.ts');assert.match(source,/resource_missing/);assert.match(source,/revokeMissingSubscription/)});
test('operational errors collapse to an allowlisted reason',()=>{assert.deepEqual(safeStripeReason(new Error('sk_test_secret card 4242')),{code:'STRIPE_REQUEST_FAILED',retryable:true});assert.deepEqual(safeStripeReason(new StripeBillingError('PRICE_CONFIGURATION_INVALID',false)),{code:'PRICE_CONFIGURATION_INVALID',retryable:false});assert.doesNotMatch(read('lib/billing/stripe-verification.ts'),/error\.message|JSON\.stringify\(error|console\.error\([^,]+,error/)});
test('publishable key is optional because no browser Stripe.js is used',()=>{assert.doesNotMatch(read('lib/billing/config.ts'),/NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY/);assert.doesNotMatch(read('.env.example'),/NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY/)});
