import assert from 'node:assert/strict';
import test from 'node:test';
import { AnalysisContextBuilder } from '../lib/market-intelligence/analysis/analysis-context-builder.ts';
import { simpleAtr } from '../lib/market-intelligence/analysis-utils/index.ts';
import type { DetectorResult, MarketDataSnapshot, NormalizedCandle } from '../lib/market-intelligence/contracts.ts';
import { VolatilityRequirementDetector } from '../lib/market-intelligence/detectors/volatility-requirement/volatility-requirement-detector.ts';
import { calculateLegacyVolatilityRequirement } from '../lib/market-intelligence/detectors/volatility-requirement/volatility-requirement-utils.ts';
import { createDetectorRegistry } from '../lib/market-intelligence/registry/bootstrap.ts';
import { DetectorRegistry } from '../lib/market-intelligence/registry/detector-registry.ts';
import { DetectorRunner } from '../lib/market-intelligence/runner/detector-runner.ts';
import { ShadowValidator } from '../lib/market-intelligence/shadow-validation/shadow-validator.ts';

const base = Date.parse('2026-08-01T00:00:00.000Z');
const candle = (index: number, open = 100, high = 105, low = 95, close = 100): NormalizedCandle => ({ openedAt: new Date(base + index * 3_600_000).toISOString(), closedAt: new Date(base + (index + 1) * 3_600_000).toISOString(), open, high, low, close, volume: 100, complete: true });
const history = (last = candle(14)) => [...Array.from({ length: 14 }, (_, index) => candle(index)), last];
const snapshot = (candles: NormalizedCandle[], timeframe = 'H1'): MarketDataSnapshot => { const requestedAt = new Date(base + Math.max(1, candles.length) * 3_600_000).toISOString(); return { id: `volatility-${timeframe}`, snapshotVersion: '1.0.0', provider: 'fixture', providerVersion: '1', providerSymbol: 'XAU/USD', instrument: 'XAUUSD', timeframe, requestedAt, receivedAt: requestedAt, dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, freshness: { state: 'FRESH', dataAsOf: candles.at(-1)?.openedAt ?? requestedAt, ageMs: 0, maximumAgeMs: 60_000 }, candles, validationWarnings: [] }; };
const atr = (value: number) => ({ value, period: 14, smoothingMethod: 'SIMPLE' as const, candleCount: 15, trueRangeCount: 14, sourceStartTime: new Date(base).toISOString(), sourceEndTime: new Date(base + 14 * 3_600_000).toISOString(), sufficientData: true });

test('requirement is met above threshold and not met below threshold', () => { const above = calculateLegacyVolatilityRequirement('H1', history(candle(14, 100, 109, 100, 105)), atr(10)), below = calculateLegacyVolatilityRequirement('H1', history(candle(14, 100, 107, 100, 105)), atr(10)); assert.equal(above?.classification, 'REQUIREMENT_MET'); assert.equal(above?.distanceFromThreshold, 1); assert.equal(below?.classification, 'REQUIREMENT_NOT_MET'); assert.equal(below?.distanceFromThreshold, -1); });

test('exact equality qualifies through inclusive range comparison', () => { const result = calculateLegacyVolatilityRequirement('H1', history(candle(14, 100, 108, 100, 104)), atr(10)); assert.equal(result?.currentRange, 8); assert.equal(result?.volatilityThreshold, 8); assert.equal(result?.distanceFromThreshold, 0); assert.equal(result?.rangeAtOrAboveThreshold, true); assert.equal(result?.volatilityRequirementMet, true); });

test('ATR-positive guard rejects an available zero ATR and ratio remains null', () => { const result = calculateLegacyVolatilityRequirement('H1', history(candle(14, 100, 100, 100, 100)), atr(0)); assert.equal(result?.atrPositive, false); assert.equal(result?.rangeAtOrAboveThreshold, true); assert.equal(result?.classification, 'REQUIREMENT_NOT_MET'); assert.equal(result?.rangeToAtrRatio, null); });

test('bullish, bearish, and doji candles use range without directional meaning', () => { for (const value of [candle(14, 100, 109, 100, 108), candle(14, 108, 109, 100, 101), candle(14, 104, 109, 100, 104)]) assert.equal(calculateLegacyVolatilityRequirement('H1', history(value), atr(10))?.classification, 'REQUIREMENT_MET'); });

test('zero-range candle preserves Number.EPSILON', () => { const result = calculateLegacyVolatilityRequirement('H1', history(candle(14, 100, 100, 100, 100)), atr(1)); assert.equal(result?.currentRange, Number.EPSILON); assert.equal(result?.rangeAtOrAboveThreshold, false); assert.doesNotMatch(JSON.stringify(result), /Infinity|NaN/); });

test('detector reuses SIMPLE ATR(14), last 15 candles, and 14 true ranges', async () => { const values = history(candle(14, 100, 109, 100, 105)), expected = simpleAtr(values, 14), result = await new VolatilityRequirementDetector().execute(snapshot(values)); assert.equal(result.payload?.atr, expected.value); assert.equal(result.payload?.atrPeriod, 14); assert.equal(result.payload?.atrSmoothingMethod, 'SIMPLE'); assert.equal(result.payload?.candleCount, 15); assert.equal(result.payload?.trueRangeCount, 14); assert.equal(result.payload?.sourceStartTime, values[0].openedAt); });

test('exact history minimum, insufficiency, and incomplete latest exclusion are explicit', async () => { const values = history(); assert.equal((await new VolatilityRequirementDetector().execute(snapshot(values))).status, 'DETECTED'); assert.equal((await new VolatilityRequirementDetector().execute(snapshot(values.slice(1)))).status, 'INSUFFICIENT_DATA'); const incomplete = { ...candle(15, 100, 200, 0, 150), complete: false, closedAt: new Date(base + 17 * 3_600_000).toISOString() }, result = await new VolatilityRequirementDetector().execute(snapshot([...values, incomplete])); assert.equal(result.payload?.eventCandleTime, values.at(-1)!.openedAt); });

test('malformed OHLC, geometry, timestamps, and ordering return ERROR', async () => { const fixtures: Array<[NormalizedCandle[], string]> = []; const nan = history(); nan[0] = { ...nan[0], low: Number.NaN }; fixtures.push([nan, 'INVALID_OHLC']); const geometry = history(); geometry[0] = { ...geometry[0], low: 110 }; fixtures.push([geometry, 'IMPOSSIBLE_CANDLE_GEOMETRY']); const timestamp = history(); timestamp[0] = { ...timestamp[0], closedAt: 'bad' }; fixtures.push([timestamp, 'INVALID_TIMESTAMP']); const duplicate = history(); duplicate[1] = { ...duplicate[1], openedAt: duplicate[0].openedAt }; fixtures.push([duplicate, 'INVALID_CANDLE_ORDER']); for (const [values, code] of fixtures) { const result = await new VolatilityRequirementDetector().execute(snapshot(values)); assert.equal(result.status, 'ERROR'); assert.equal(result.errorCode, code); } });

test('metadata, registry, runner, context, shadow parity, JSON, and immutability integrate', async () => { const detector = new VolatilityRequirementDetector(); assert.deepEqual({ id: detector.id, version: detector.version, displayName: detector.displayName, deterministic: detector.deterministic, supportsReplay: detector.metadata.supportsReplay, experimental: detector.metadata.experimental, enabledByDefault: detector.metadata.enabledByDefault }, { id: 'volatility-requirement', version: '1.0.0', displayName: 'Volatility Requirement Detector', deterministic: true, supportsReplay: true, experimental: true, enabledByDefault: true }); assert.ok(createDetectorRegistry().exists('volatility-requirement')); const source = snapshot(history()), before = JSON.stringify(source), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze(), { createRunId: () => 'volatility-run' }).execute(source, ['volatility-requirement']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary), beforeContext = JSON.stringify(context), comparison = new ShadowValidator().validate(source, context).comparisons.find((item) => item.detectorId === 'volatility-requirement'); assert.equal(comparison?.status, 'MATCH'); assert.equal(comparison?.exactMatch, true); assert.equal(JSON.stringify(source), before); assert.equal(JSON.stringify(context), beforeContext); assert.deepEqual(JSON.parse(JSON.stringify(context)), context); assert.doesNotMatch(JSON.stringify(summary.detectorResults[0]), /BUY|SELL|strategy|risk|readiness|entry|stopLoss|takeProfit|target|decision/i); });

test('wrong strict operator, multiplier, and missing ATR guard produce shadow mismatches', async () => { const source = snapshot(history()), detector = new VolatilityRequirementDetector(), summary = await new DetectorRunner(new DetectorRegistry().register(detector).freeze()).execute(source, ['volatility-requirement']), context = new AnalysisContextBuilder({ now: () => source.requestedAt }).build(source, summary); const patches: Array<Record<string, string | number | boolean | null>> = [{ classification: 'REQUIREMENT_NOT_MET', volatilityRequirementMet: false, rangeAtOrAboveThreshold: false }, { thresholdMultiplier: 0.9, volatilityThreshold: 999 }, { atrPositive: false, volatilityRequirementMet: false, classification: 'REQUIREMENT_NOT_MET' }]; for (const payloadPatch of patches) { const wrong = context.detectorResults.map((result): DetectorResult => ({ ...result, payload: { ...(result.payload as object), ...payloadPatch } })); assert.equal(new ShadowValidator().validate(source, { ...context, detectorResults: wrong }).comparisons.find((item) => item.detectorId === 'volatility-requirement')?.status, 'MISMATCH'); } });
