export type BacktestRunStatus = 'QUEUED' | 'RUNNING' | 'COMPLETED' | 'FAILED' | 'CANCELLED';

export type BacktestRun = {
  id: string;
  user_id: string;
  workspace_id: string | null;
  strategy_profile_id: string;
  strategy_revision_id: string;
  strategy_snapshot_hash: string;
  strategy_snapshot_json: Record<string, unknown>;
  instrument: string;
  execution_timeframe: string;
  period_start: string;
  period_end: string;
  starting_balance: number;
  risk_configuration: Record<string, unknown>;
  execution_model: Record<string, unknown>;
  engine_version: string;
  data_provider: string;
  data_revision_fingerprint: string;
  status: BacktestRunStatus;
  failure_reason: string | null;
  created_at: string;
  started_at: string | null;
  completed_at: string | null;
  metadata: Record<string, unknown>;
};

export type BacktestTrade = {
  id: string;
  run_id: string;
  sequence: number;
  signal_timestamp: string;
  entry_timestamp: string;
  exit_timestamp: string | null;
  instrument: string;
  direction: 'LONG' | 'SHORT';
  entry: number;
  stop_loss: number | null;
  take_profit: number | null;
  exit_price: number | null;
  risk_percent: number | null;
  risk_amount: number | null;
  balance_before: number | null;
  balance_after: number | null;
  gross_r: number | null;
  net_r: number | null;
  gross_pnl: number | null;
  net_pnl: number | null;
  spread_cost: number;
  slippage_cost: number;
  commission_cost: number;
  setup_type: string | null;
  session: string | null;
  authoritative_rule_snapshot: Record<string, unknown> | null;
  entry_reason: string | null;
  exit_reason: string | null;
  ambiguous_intrabar: boolean;
  simulation_metadata: Record<string, unknown>;
  created_at: string;
};

export type BacktestResult = {
  id: string;
  run_id: string;
  ending_balance: number | null;
  net_return_percent: number | null;
  total_trades: number | null;
  wins: number | null;
  losses: number | null;
  breakeven: number | null;
  win_rate: number | null;
  profit_factor: number | null;
  expectancy_r: number | null;
  average_r: number | null;
  average_win_r: number | null;
  average_loss_r: number | null;
  max_drawdown_percent: number | null;
  max_drawdown_amount: number | null;
  longest_win_streak: number | null;
  longest_loss_streak: number | null;
  gross_profit: number | null;
  gross_loss: number | null;
  total_costs: number | null;
  summary_snapshot: Record<string, unknown>;
  created_at: string;
};

export type BacktestUsage = {
  id: string;
  user_id: string;
  workspace_id: string | null;
  plan_code: 'FREE' | 'PRO' | 'ELITE' | 'TEAM';
  billing_period_start: string;
  billing_period_end: string;
  run_count: number;
  limit_value: number;
  last_run_id: string | null;
  created_at: string;
  updated_at: string;
};
