import type { ConfidenceAssessment } from '../confidence/confidence-types.ts';
import type { EvidenceGraph } from '../evidence-graph/evidence-graph-types.ts';
import { EvidenceGraphValidator } from '../evidence-graph/evidence-graph-validator.ts';
import { stableFingerprint } from '../serialization/stable-fingerprint.ts';
import type { StrategyContext } from '../strategy-composition/composition-types.ts';
import type { CompiledStrategyDefinition } from '../strategy-definitions/strategy-definition-types.ts';
import { ReadinessPolicyValidator } from './readiness-policy-validator.ts';
import type { ReadinessAssessment, ReadinessCriterionId, ReadinessCriterionResult, ReadinessPolicy, ReadinessSeverity, ReadinessStatus } from './readiness-types.ts';

export const READINESS_ENGINE_VERSION='1.0.0' as const;
const names:Record<ReadinessCriterionId,string>={'confidence-threshold':'Confidence threshold','coverage-threshold':'Coverage threshold','required-rules':'Required rules','required-rule-failure':'Required-rule failure','required-rule-unavailable':'Required-rule availability','rule-errors':'Rule errors','partial-confidence':'Partial confidence','minimum-matched-rules':'Minimum matched rules','maximum-optional-failures':'Maximum optional failures'};
const unique=<T>(values:readonly T[]):T[]=>[...new Set(values)];
function deepFreeze<T>(value:T):T{if(value&&typeof value==='object'&&!Object.isFrozen(value)){Object.values(value).forEach(deepFreeze);Object.freeze(value);}return value;}
export function createReadinessAssessmentId(definition:CompiledStrategyDefinition,context:StrategyContext,graph:EvidenceGraph,confidence:ConfidenceAssessment,policy:ReadinessPolicy):string{return`readiness:${stableFingerprint({compiledStrategyId:definition.compiledStrategyId,strategyContextId:context.contextId,evidenceGraphId:graph.graphId,confidenceAssessmentId:confidence.assessmentId,policyFingerprint:stableFingerprint(policy),requestedAt:context.executionTimestamp,engineVersion:READINESS_ENGINE_VERSION})}`;}

export class ReadinessPolicyEngine{
  assess(definition:CompiledStrategyDefinition,context:StrategyContext,graph:EvidenceGraph,confidence:ConfidenceAssessment,policy:ReadinessPolicy):ReadinessAssessment{
    const invalid=this.inputError(definition,context,graph,confidence,policy);if(invalid)return this.error(definition,context,graph,confidence,policy,invalid);
    const required=context.ruleResults.filter(result=>definition.ruleRequirements?.[result.ruleId]==='REQUIRED'),failedRequired=required.filter(result=>result.status==='FAILED').map(result=>result.ruleId),unavailableRequired=required.filter(result=>result.status==='NOT_EVALUATED').map(result=>result.ruleId),errorIds=context.ruleResults.filter(result=>result.status==='ERROR').map(result=>result.ruleId),failedOptional=context.ruleResults.filter(result=>definition.ruleRequirements?.[result.ruleId]!=='REQUIRED'&&result.status==='FAILED').map(result=>result.ruleId),matchedCount=context.ruleResults.filter(result=>result.status==='MATCHED').length,failedCount=context.ruleResults.filter(result=>result.status==='FAILED').length;
    const evidence=(ruleIds:string[])=>unique(confidence.contributions.filter(item=>ruleIds.includes(item.ruleId)).flatMap(item=>item.evidenceNodeIds));
    const criterion=(id:ReadinessCriterionId,order:number,status:ReadinessCriterionResult['status'],severity:ReadinessSeverity,actualValue:ReadinessCriterionResult['actualValue'],expectedValue:ReadinessCriterionResult['expectedValue'],comparisonOperator:ReadinessCriterionResult['comparisonOperator'],explanation:string,relatedRuleIds:string[]=[],warnings:string[]=[]):ReadinessCriterionResult=>({criterionId:id,name:names[id],order,status,severity,actualValue,expectedValue,comparisonOperator,passed:status==='PASSED',explanation,relatedRuleIds,relatedEvidenceNodeIds:evidence(relatedRuleIds),warnings});
    const evaluate=(id:ReadinessCriterionId,order:number):ReadinessCriterionResult=>{
      switch(id){
        case'confidence-threshold':return confidence.confidencePercent===null?criterion(id,order,'NOT_EVALUATED','WARNING',null,policy.minimumConfidencePercent,'>=','Confidence is unavailable.'):criterion(id,order,confidence.confidencePercent>=policy.minimumConfidencePercent?'PASSED':'FAILED','WARNING',confidence.confidencePercent,policy.minimumConfidencePercent,'>=',`Confidence ${confidence.confidencePercent} must be at least ${policy.minimumConfidencePercent}.`);
        case'coverage-threshold':return confidence.configuredCoveragePercent===null?criterion(id,order,'NOT_EVALUATED','WARNING',null,policy.minimumCoveragePercent,'>=','Configured coverage is unavailable.'):criterion(id,order,confidence.configuredCoveragePercent>=policy.minimumCoveragePercent?'PASSED':'FAILED','WARNING',confidence.configuredCoveragePercent,policy.minimumCoveragePercent,'>=',`Coverage ${confidence.configuredCoveragePercent} must be at least ${policy.minimumCoveragePercent}.`);
        case'required-rules':{const unmatched=required.filter(result=>result.status!=='MATCHED').map(result=>result.ruleId),pass=!policy.requireAllRequiredRulesMatched||unmatched.length===0;return criterion(id,order,pass?'PASSED':'FAILED','WARNING',required.length-unmatched.length,required.length,'ALL_MATCHED',policy.requireAllRequiredRulesMatched?'All required rules must match.':'The policy does not require every required rule to match.',unmatched);}
        case'required-rule-failure':{const pass=failedRequired.length===0;return criterion(id,order,pass?'PASSED':'FAILED',policy.blockOnRequiredRuleFailure?'BLOCKING':'WARNING',failedRequired.length,0,'NONE','No required rule may fail under the configured failure policy.',failedRequired);}
        case'required-rule-unavailable':{const pass=unavailableRequired.length===0;return criterion(id,order,pass?'PASSED':'FAILED',policy.blockOnRequiredRuleUnavailable?'BLOCKING':'WARNING',unavailableRequired.length,0,'NONE','Required-rule evidence availability follows the configured policy.',unavailableRequired);}
        case'rule-errors':{const pass=errorIds.length===0;return criterion(id,order,pass?'PASSED':'FAILED',policy.blockOnAnyRuleError?'BLOCKING':'WARNING',errorIds.length,0,'NONE','Rule evaluation errors follow the configured policy.',errorIds);}
        case'partial-confidence':{const partial=confidence.status==='PARTIAL',pass=!partial||policy.allowPartialConfidence;return criterion(id,order,pass?'PASSED':'FAILED','WARNING',confidence.status,policy.allowPartialConfidence,'ALLOWED',pass?'Confidence status is permitted by policy.':'Partial confidence is not permitted by policy.');}
        case'minimum-matched-rules':return policy.minimumMatchedRuleCount===undefined?criterion(id,order,'NOT_EVALUATED','INFO',matchedCount,null,'>=','No minimum matched-rule count is configured.'):criterion(id,order,matchedCount>=policy.minimumMatchedRuleCount?'PASSED':'FAILED','WARNING',matchedCount,policy.minimumMatchedRuleCount,'>=',`Matched-rule count ${matchedCount} must be at least ${policy.minimumMatchedRuleCount}.`);
        case'maximum-optional-failures':return policy.maximumFailedOptionalRules===undefined?criterion(id,order,'NOT_EVALUATED','INFO',failedOptional.length,null,'<=','No maximum optional-failure count is configured.',failedOptional):criterion(id,order,failedOptional.length<=policy.maximumFailedOptionalRules?'PASSED':'FAILED','WARNING',failedOptional.length,policy.maximumFailedOptionalRules,'<=',`Optional failures ${failedOptional.length} must not exceed ${policy.maximumFailedOptionalRules}.`,failedOptional);
      }
    };
    const criteria=policy.criteriaOrder.map(evaluate),failed=criteria.filter(item=>item.status==='FAILED'),blocking=failed.filter(item=>item.severity==='BLOCKING'),warnings=failed.filter(item=>item.severity==='WARNING');
    const unavailable=confidence.status==='UNAVAILABLE'||confidence.confidencePercent===null||confidence.configuredCoveragePercent===null;
    const status:ReadinessStatus=confidence.status==='ERROR'&&policy.blockOnAnyRuleError?'ERROR':unavailable?'UNAVAILABLE':blocking.length?'BLOCKED':failed.length?'WAIT':'READY';
    return deepFreeze({assessmentId:createReadinessAssessmentId(definition,context,graph,confidence,policy),version:'1.0.0',engineVersion:READINESS_ENGINE_VERSION,policyId:policy.id,policyVersion:policy.version,strategyId:definition.id,strategyVersion:definition.version,compiledStrategyId:definition.compiledStrategyId,strategyContextId:context.contextId,evidenceGraphId:graph.graphId,confidenceAssessmentId:confidence.assessmentId,sourceMarketContextId:graph.marketContextId,generatedAt:context.executionTimestamp,status,criteria,failedCriterionIds:failed.map(item=>item.criterionId),blockingCriterionIds:blocking.map(item=>item.criterionId),warningCriterionIds:warnings.map(item=>item.criterionId),failedRequiredRuleIds:failedRequired,unavailableRequiredRuleIds:unavailableRequired,errorRuleIds:errorIds,matchedRuleCount:matchedCount,failedRuleCount:failedCount,confidencePercent:confidence.confidencePercent,coveragePercent:confidence.configuredCoveragePercent,summary:{totalCriteria:criteria.length,passedCriteria:criteria.filter(item=>item.status==='PASSED').length,failedCriteria:failed.length,notEvaluatedCriteria:criteria.filter(item=>item.status==='NOT_EVALUATED').length,errorCriteria:criteria.filter(item=>item.status==='ERROR').length,blockingFailures:blocking.length,meaning:'SETUP_COMPLETENESS_NOT_TRADE_AUTHORIZATION'},warnings:unique([...confidence.warnings,...criteria.flatMap(item=>item.warnings)])});
  }
  private inputError(definition:CompiledStrategyDefinition,context:StrategyContext,graph:EvidenceGraph,confidence:ConfidenceAssessment,policy:ReadinessPolicy):string|null{
    const pv=new ReadinessPolicyValidator().validate(policy);if(!pv.valid)return`Invalid readiness policy: ${pv.issues.map(issue=>issue.message).join(' ')}`;
    if(definition.id!==context.strategyId||definition.version!==context.strategyVersion||graph.strategyId!==definition.id||graph.strategyContextId!==context.contextId||graph.marketContextId!==context.marketContextId||confidence.strategyId!==definition.id||confidence.compiledStrategyId!==definition.compiledStrategyId||confidence.strategyContextId!==context.contextId||confidence.evidenceGraphId!==graph.graphId||confidence.sourceMarketContextId!==graph.marketContextId||confidence.generatedAt!==context.executionTimestamp)return'Source identity mismatch.';
    if(!new EvidenceGraphValidator().validate(graph).valid)return'Invalid EvidenceGraph.';
    return null;
  }
  private error(definition:CompiledStrategyDefinition,context:StrategyContext,graph:EvidenceGraph,confidence:ConfidenceAssessment,policy:ReadinessPolicy,warning:string):ReadinessAssessment{return deepFreeze({assessmentId:createReadinessAssessmentId(definition,context,graph,confidence,policy),version:'1.0.0',engineVersion:READINESS_ENGINE_VERSION,policyId:policy.id,policyVersion:policy.version,strategyId:definition.id,strategyVersion:definition.version,compiledStrategyId:definition.compiledStrategyId,strategyContextId:context.contextId,evidenceGraphId:graph.graphId,confidenceAssessmentId:confidence.assessmentId,sourceMarketContextId:graph.marketContextId,generatedAt:context.executionTimestamp,status:'ERROR',criteria:[],failedCriterionIds:[],blockingCriterionIds:[],warningCriterionIds:[],failedRequiredRuleIds:[],unavailableRequiredRuleIds:[],errorRuleIds:[],matchedRuleCount:0,failedRuleCount:0,confidencePercent:null,coveragePercent:null,summary:{totalCriteria:0,passedCriteria:0,failedCriteria:0,notEvaluatedCriteria:0,errorCriteria:1,blockingFailures:0,meaning:'SETUP_COMPLETENESS_NOT_TRADE_AUTHORIZATION'},warnings:[warning]});}
}
