import { filterCompletedCandles, validateCandles } from '../analysis-utils/index.ts';
import type { AtrObservation, BreakOfStructureObservation, DisplacementObservation, FairValueGapObservation, LiquiditySweepObservation, MarketDataSnapshot, NormalizedCandle, RangeLevelsObservation, RejectionCandleObservation, RetestObservation, TrendObservation, VolatilityRequirementObservation, VolumeExpansionObservation } from '../contracts.ts';
import type { LegacyComparableObservation, LegacyComparableObservations } from './shadow-types.ts';

const avg = (values: number[]) => values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : 0;
const unavailable = (detectorId: LegacyComparableObservation['detectorId'], timeframe: string, warning: string): LegacyComparableObservation => ({ detectorId, timeframe, status: 'UNAVAILABLE', payload: null, warnings: [warning] });

/** Pure, traceable copies of only the formulas in market-analysis.ts::analyzeTf. */
export function createLegacyComparableObservations(snapshot: MarketDataSnapshot): LegacyComparableObservations {
  const validation = validateCandles(snapshot.candles);
  if (!validation.valid || !snapshot.timeframe.trim()) return { snapshotId: snapshot.id, observations: (['atr', 'trend', 'range-levels', 'break-of-structure', 'liquidity-sweep', 'fair-value-gap', 'rejection-candle', 'volume-expansion', 'displacement', 'volatility-requirement', 'retest'] as const).map((detectorId) => ({ detectorId, timeframe: snapshot.timeframe, status: 'ERROR', payload: null, warnings: validation.valid ? ['Snapshot timeframe is missing.'] : validation.issues.map((issue) => issue.message) })) };
  const filtered = filterCompletedCandles(snapshot.candles, snapshot.requestedAt);
  if (filtered.invalidTimestamp.length) return { snapshotId: snapshot.id, observations: (['atr', 'trend', 'range-levels', 'break-of-structure', 'liquidity-sweep', 'fair-value-gap', 'rejection-candle', 'volume-expansion', 'displacement', 'volatility-requirement', 'retest'] as const).map((detectorId) => ({ detectorId, timeframe: snapshot.timeframe, status: 'ERROR', payload: null, warnings: ['Invalid candle close timestamp.'] })) };
  const candles = filtered.completed;
  return { snapshotId: snapshot.id, observations: [legacyAtr(snapshot.timeframe, candles), legacyTrend(snapshot.timeframe, candles), legacyRange(snapshot.timeframe, candles), legacyBos(snapshot.timeframe, candles), legacySweep(snapshot.timeframe, candles), legacyFairValueGap(snapshot.timeframe, candles), legacyRejectionCandle(snapshot.timeframe, candles), legacyVolumeExpansion(snapshot.timeframe, candles), legacyDisplacement(snapshot.timeframe, candles), legacyVolatilityRequirement(snapshot.timeframe, candles), legacyRetest(snapshot.timeframe, candles)] };
}

function legacyAtr(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'atr'> {
  if (candles.length < 15) return unavailable('atr', timeframe, 'Legacy ATR zero fallback maps to unavailable with fewer than 15 completed candles.') as LegacyComparableObservation<'atr'>;
  const source = candles.slice(-15); const ranges = source.slice(1).map((candle, index) => Math.max(candle.high - candle.low, Math.abs(candle.high - source[index].close), Math.abs(candle.low - source[index].close)));
  const payload: AtrObservation = { timeframe, atr: avg(ranges), period: 14, smoothingMethod: 'SIMPLE', candleCount: source.length, trueRangeCount: ranges.length, unit: 'RAW_PRICE', normalizedAtrPercent: null, sourceStartTime: source[0].openedAt, sourceEndTime: source.at(-1)!.openedAt, lastCandleTime: source.at(-1)!.openedAt };
  return { detectorId: 'atr', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyTrend(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'trend'> {
  if (candles.length < 24) return unavailable('trend', timeframe, 'Legacy RANGE fallback maps to unavailable with fewer than 24 completed candles.') as LegacyComparableObservation<'trend'>;
  const source = candles.slice(-24), latestClose = source.at(-1)!.close, fast = avg(source.slice(-10).map((candle) => candle.close)), slow = avg(source.map((candle) => candle.close));
  const direction = fast > slow && latestClose > slow ? 'BULLISH' : fast < slow && latestClose < slow ? 'BEARISH' : 'RANGE';
  const payload: TrendObservation = { timeframe, direction, latestClose, fastAverage: { type: 'SMA', period: 10, value: fast }, slowAverage: { type: 'SMA', period: 24, value: slow }, fastSlowDifference: fast - slow, fastSlowDifferencePercent: null, closeToSlowDifference: latestClose - slow, closeToSlowDifferencePercent: null, candleCount: source.length, sourceStartTime: source[0].openedAt, sourceEndTime: source.at(-1)!.openedAt, lastCandleTime: source.at(-1)!.openedAt };
  return { detectorId: 'trend', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyRange(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'range-levels'> {
  if (candles.length < 20) return unavailable('range-levels', timeframe, 'Legacy empty structural windows map to unavailable with fewer than 20 completed candles.') as LegacyComparableObservation<'range-levels'>;
  const source = candles.slice(-20), recent = source.slice(-8, -1), previous = source.slice(-20, -8), recentHigh = Math.max(...recent.map((candle) => candle.high)), recentLow = Math.min(...recent.map((candle) => candle.low)), previousHigh = Math.max(...previous.map((candle) => candle.high)), previousLow = Math.min(...previous.map((candle) => candle.low));
  const payload: RangeLevelsObservation = { timeframe, recentHigh, recentLow, previousHigh, previousLow, midpoint: (recentHigh + recentLow) / 2, range: recentHigh - recentLow, candleCount: source.length, sourceStartTime: source[0].openedAt, sourceEndTime: source.at(-1)!.openedAt, lastCandleTime: source.at(-1)!.openedAt };
  return { detectorId: 'range-levels', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyBos(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'break-of-structure'> {
  if (candles.length < 8) return unavailable('break-of-structure', timeframe, 'BOS requires eight completed candles.') as LegacyComparableObservation<'break-of-structure'>;
  const reference = candles.slice(-8, -1), current = candles.at(-1)!, referenceHigh = Math.max(...reference.map((candle) => candle.high)), referenceLow = Math.min(...reference.map((candle) => candle.low)), bullishBreak = current.close > referenceHigh, bearishBreak = current.close < referenceLow, direction = bullishBreak ? 'BULLISH' : bearishBreak ? 'BEARISH' : 'NONE', breakPrice = bullishBreak ? referenceHigh : bearishBreak ? referenceLow : null, breakDistance = bullishBreak ? current.close - referenceHigh : bearishBreak ? referenceLow - current.close : null;
  const payload: BreakOfStructureObservation = { timeframe, direction, bullishBreak, bearishBreak, referenceHigh, referenceLow, currentOpen: current.open, currentHigh: current.high, currentLow: current.low, currentClose: current.close, breakPrice, breakDistance, breakDistancePercent: null, referenceWindowSize: 7, candleCount: 8, referenceStartTime: reference[0].openedAt, referenceEndTime: reference.at(-1)!.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'break-of-structure', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacySweep(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'liquidity-sweep'> {
  if (candles.length < 20) return unavailable('liquidity-sweep', timeframe, 'Liquidity Sweep requires the complete legacy prior window.') as LegacyComparableObservation<'liquidity-sweep'>;
  const prior = candles.slice(-20, -8), current = candles.at(-1)!, referenceHigh = Math.max(...prior.map((candle) => candle.high)), referenceLow = Math.min(...prior.map((candle) => candle.low)), highSideSweep = current.high > referenceHigh && current.close < referenceHigh, lowSideSweep = current.low < referenceLow && current.close > referenceLow, side = highSideSweep && lowSideSweep ? 'BOTH' : highSideSweep ? 'HIGH_SIDE' : lowSideSweep ? 'LOW_SIDE' : 'NONE', highPenetration = current.high > referenceHigh ? current.high - referenceHigh : null, lowPenetration = current.low < referenceLow ? referenceLow - current.low : null;
  const payload: LiquiditySweepObservation = { timeframe, side, highSideSweep, lowSideSweep, referenceHigh, referenceLow, currentOpen: current.open, currentHigh: current.high, currentLow: current.low, currentClose: current.close, highPenetration, lowPenetration, highPenetrationPercent: null, lowPenetrationPercent: null, closeReturnedInsideHigh: current.close < referenceHigh, closeReturnedInsideLow: current.close > referenceLow, referenceWindowSize: 12, candleCount: 13, referenceStartTime: prior[0].openedAt, referenceEndTime: prior.at(-1)!.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'liquidity-sweep', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyFairValueGap(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'fair-value-gap'> {
  if (candles.length < 3) return unavailable('fair-value-gap', timeframe, 'Fair Value Gap requires three completed candles.') as LegacyComparableObservation<'fair-value-gap'>;
  const source = candles.slice(-3), reference = source[0], current = source[2], bullishGap = current.low > reference.high, bearishGap = current.high < reference.low, direction = bullishGap ? 'BULLISH' : bearishGap ? 'BEARISH' : 'NONE', gapTop = bullishGap ? current.low : bearishGap ? reference.low : null, gapBottom = bullishGap ? reference.high : bearishGap ? current.high : null, gapSize = gapTop === null || gapBottom === null ? null : gapTop - gapBottom;
  const payload: FairValueGapObservation = { timeframe, direction, bullishGap, bearishGap, gapTop, gapBottom, gapSize, gapSizePercent: null, currentCandle: { open: current.open, high: current.high, low: current.low, close: current.close }, referenceCandle: { open: reference.open, high: reference.high, low: reference.low, close: reference.close }, candleCount: 3, sourceStartTime: reference.openedAt, sourceEndTime: current.openedAt, referenceCandleTime: reference.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'fair-value-gap', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyRejectionCandle(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'rejection-candle'> {
  const candle = candles.at(-1);
  if (!candle) return unavailable('rejection-candle', timeframe, 'Rejection Candle requires one completed candle.') as LegacyComparableObservation<'rejection-candle'>;
  const bodySize = Math.abs(candle.close - candle.open), fullRange = candle.high - candle.low, upperWick = candle.high - Math.max(candle.open, candle.close), lowerWick = Math.min(candle.open, candle.close) - candle.low, upperRejection = upperWick > bodySize * 1.5, lowerRejection = lowerWick > bodySize * 1.5, classification = upperRejection && lowerRejection ? 'BOTH' : upperRejection ? 'UPPER' : lowerRejection ? 'LOWER' : 'NONE';
  const payload: RejectionCandleObservation = { timeframe, classification, rejectionDetected: upperRejection || lowerRejection, upperRejection, lowerRejection, bodySize, fullRange, upperWick, lowerWick, bodyToRangeRatio: fullRange === 0 ? null : bodySize / fullRange, upperWickToBodyRatio: bodySize === 0 ? null : upperWick / bodySize, lowerWickToBodyRatio: bodySize === 0 ? null : lowerWick / bodySize, open: candle.open, high: candle.high, low: candle.low, close: candle.close, candleCount: 1, sourceStartTime: candle.openedAt, sourceEndTime: candle.openedAt, eventCandleTime: candle.openedAt };
  return { detectorId: 'rejection-candle', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyVolumeExpansion(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'volume-expansion'> {
  if (candles.length < 2) return unavailable('volume-expansion', timeframe, 'Volume Expansion requires two completed candles.') as LegacyComparableObservation<'volume-expansion'>;
  const previous = candles.at(-2)!, current = candles.at(-1)!, currentVolume = Number.isFinite(current.volume) ? current.volume : null, previousVolume = Number.isFinite(previous.volume) ? previous.volume : null, volumeAvailable = currentVolume !== null && previousVolume !== null, expansionDetected = volumeAvailable && currentVolume > previousVolume * 1.15, thresholdVolume = previousVolume === null ? null : previousVolume * 1.15, volumeIncrease = volumeAvailable ? currentVolume - previousVolume : null;
  const payload: VolumeExpansionObservation = { timeframe, classification: expansionDetected ? 'EXPANDED' : 'NOT_EXPANDED', expansionDetected, volumeAvailable, currentVolume, previousVolume, multiplier: 1.15, thresholdVolume, volumeIncrease, volumeRatio: !volumeAvailable || previousVolume === 0 ? null : currentVolume / previousVolume, volumeChangePercent: !volumeAvailable || previousVolume === 0 ? null : (currentVolume - previousVolume) / Math.abs(previousVolume) * 100, candleCount: 2, sourceStartTime: previous.openedAt, sourceEndTime: current.openedAt, previousCandleTime: previous.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'volume-expansion', timeframe, status: 'AVAILABLE', payload, warnings: volumeAvailable ? [] : ['Legacy volume confirmation is false when volume is unavailable.'] };
}
function legacyDisplacement(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'displacement'> {
  if (candles.length < 15) return unavailable('displacement', timeframe, 'Displacement requires 15 completed candles for ATR(14).') as LegacyComparableObservation<'displacement'>;
  const source = candles.slice(-15), ranges = source.slice(1).map((current, index) => Math.max(current.high - current.low, Math.abs(current.high - source[index].close), Math.abs(current.low - source[index].close))), atr = avg(ranges), current = source.at(-1)!, bodySize = Math.abs(current.close - current.open), fullRange = Math.max(current.high - current.low, Number.EPSILON), atrThreshold = atr * 1.1, bodyRatioThreshold = fullRange * 0.65, effectiveThreshold = Math.max(atrThreshold, bodyRatioThreshold), bodyAboveAtrThreshold = bodySize > atrThreshold, bodyAboveRangeThreshold = bodySize > bodyRatioThreshold, displacementDetected = bodySize > effectiveThreshold;
  const payload: DisplacementObservation = { timeframe, classification: displacementDetected ? 'DISPLACEMENT' : 'NOT_DISPLACEMENT', displacementDetected, bodySize, fullRange, bodyToRangeRatio: bodySize / fullRange, atr, atrPeriod: 14, atrSmoothingMethod: 'SIMPLE', atrThresholdMultiplier: 1.1, atrThreshold, bodyRatioThresholdMultiplier: 0.65, bodyRatioThreshold, effectiveThreshold, distanceAboveEffectiveThreshold: bodySize - effectiveThreshold, bodyAboveAtrThreshold, bodyAboveRangeThreshold, open: current.open, high: current.high, low: current.low, close: current.close, candleCount: source.length, trueRangeCount: ranges.length, sourceStartTime: source[0].openedAt, sourceEndTime: source.at(-1)!.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'displacement', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyVolatilityRequirement(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'volatility-requirement'> {
  if (candles.length < 15) return unavailable('volatility-requirement', timeframe, 'Volatility Requirement requires 15 completed candles for ATR(14).') as LegacyComparableObservation<'volatility-requirement'>;
  const source = candles.slice(-15), ranges = source.slice(1).map((current, index) => Math.max(current.high - current.low, Math.abs(current.high - source[index].close), Math.abs(current.low - source[index].close))), atr = avg(ranges), current = source.at(-1)!, currentRange = Math.max(current.high - current.low, Number.EPSILON), volatilityThreshold = atr * 0.8, atrPositive = atr > 0, rangeAtOrAboveThreshold = currentRange >= volatilityThreshold, volatilityRequirementMet = atrPositive && rangeAtOrAboveThreshold;
  const payload: VolatilityRequirementObservation = { timeframe, classification: volatilityRequirementMet ? 'REQUIREMENT_MET' : 'REQUIREMENT_NOT_MET', volatilityRequirementMet, currentRange, atr, atrPeriod: 14, atrSmoothingMethod: 'SIMPLE', thresholdMultiplier: 0.8, volatilityThreshold, rangeToAtrRatio: atr === 0 ? null : currentRange / atr, distanceFromThreshold: currentRange - volatilityThreshold, rangeAtOrAboveThreshold, atrPositive, open: current.open, high: current.high, low: current.low, close: current.close, candleCount: source.length, trueRangeCount: ranges.length, sourceStartTime: source[0].openedAt, sourceEndTime: source.at(-1)!.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'volatility-requirement', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
function legacyRetest(timeframe: string, candles: NormalizedCandle[]): LegacyComparableObservation<'retest'> {
  if (candles.length < 24) return unavailable('retest', timeframe, 'Retest requires 24 completed candles.') as LegacyComparableObservation<'retest'>;
  const source = candles.slice(-24), current = source.at(-1)!, fast = avg(source.slice(-10).map((candle) => candle.close)), slow = avg(source.map((candle) => candle.close)), trendBias = fast > slow && current.close > slow ? 'BULLISH' : fast < slow && current.close < slow ? 'BEARISH' : 'RANGE', recent = source.slice(-8, -1), recentHigh = Math.max(...recent.map((candle) => candle.high)), recentLow = Math.min(...recent.map((candle) => candle.low)), targetLevel = trendBias === 'BULLISH' ? recentHigh : recentLow, atrSource = source.slice(-15), ranges = atrSource.slice(1).map((candle, index) => Math.max(candle.high - candle.low, Math.abs(candle.high - atrSource[index].close), Math.abs(candle.low - atrSource[index].close))), atr = avg(ranges), atrTolerance = atr * 0.35, priceTolerance = current.close * 0.0002, tolerance = Math.max(atrTolerance, priceTolerance), distanceToTarget = Math.abs(current.close - targetLevel), retestDetected = distanceToTarget <= tolerance;
  const payload: RetestObservation = { timeframe, classification: retestDetected ? 'RETEST' : 'NO_RETEST', retestDetected, trendBias, targetLevel, recentHigh, recentLow, tolerance, atrTolerance, priceTolerance, distanceToTarget, atr, atrPeriod: 14, atrSmoothingMethod: 'SIMPLE', currentClose: current.close, candleCount: source.length, atrCandleCount: atrSource.length, trueRangeCount: ranges.length, recentWindowSize: recent.length, sourceStartTime: source[0].openedAt, sourceEndTime: current.openedAt, recentStartTime: recent[0].openedAt, recentEndTime: recent.at(-1)!.openedAt, eventCandleTime: current.openedAt };
  return { detectorId: 'retest', timeframe, status: 'AVAILABLE', payload, warnings: [] };
}
