'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import {useLocale} from '@/components/i18n/LocaleProvider';
import {getAuthCopy} from '@/lib/i18n/auth-copy';

export default function CompleteProfileForm({ email, current }: { email:string; current:any }) {
  const {locale}=useLocale(); const c=getAuthCopy(locale);
  const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage('');const f=new FormData(e.currentTarget);const row={first_name:String(f.get('first_name')||'').trim(),last_name:String(f.get('last_name')||'').trim(),display_name:String(f.get('display_name')||'').trim(),experience_level:String(f.get('experience_level')||''),trader_type:String(f.get('trader_type')||''),profile_completed:true,onboarding_version:2,updated_at:new Date().toISOString()};const {error}=await createClient().from('profiles').update(row).eq('id',current.id);if(error){setMessage(error.message);setSaving(false);return;}window.location.assign('/profile?onboarding=complete');}
  return <form className="card login-card" onSubmit={submit}><div className="brand">TRADE POLICE</div><p className="muted">{c.personalization}</p><h1>{c.completeProfile}</h1><p className="muted">{c.profileIntro}</p><div className="grid grid-2"><label>{c.firstName}<input name="first_name" defaultValue={current.first_name??''} required/></label><label>{c.lastName}<input name="last_name" defaultValue={current.last_name??''} required/></label></div><label>{c.displayName}<input name="display_name" defaultValue={current.display_name??''} placeholder={c.displayPlaceholder} required/></label><label>{c.email}<input value={email} disabled/></label><div className="grid grid-2"><label>{c.experience}<select name="experience_level" defaultValue={current.experience_level??''} required><option value="" disabled>{c.select}</option><option value="Beginner">{c.beginner}</option><option value="Intermediate">{c.intermediate}</option><option value="Advanced">{c.advanced}</option><option value="Professional">{c.professional}</option></select></label><label>{c.traderType}<select name="trader_type" defaultValue={current.trader_type??''} required><option value="" disabled>{c.select}</option><option value="Scalper">Scalper</option><option value="Day trader">{c.dayTrader}</option><option value="Swing trader">{c.swingTrader}</option><option value="Position trader">{c.positionTrader}</option></select></label></div><button className="primary" disabled={saving}>{saving?c.saving:c.continue}</button>{message&&<p className="warning">{message}</p>}</form>;
}
