'use client';
import { FormEvent, useState } from 'react';
import { createClient } from '@/lib/supabase/client';

export default function CompleteProfileForm({ email, current }: { email:string; current:any }) {
  const [message,setMessage]=useState(''); const [saving,setSaving]=useState(false);
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setMessage('');const f=new FormData(e.currentTarget);const row={first_name:String(f.get('first_name')||'').trim(),last_name:String(f.get('last_name')||'').trim(),display_name:String(f.get('display_name')||'').trim(),experience_level:String(f.get('experience_level')||''),trader_type:String(f.get('trader_type')||''),profile_completed:true,onboarding_version:2,updated_at:new Date().toISOString()};const {error}=await createClient().from('profiles').update(row).eq('id',current.id);if(error){setMessage(error.message);setSaving(false);return;}window.location.assign('/');}
  return <form className="card login-card" onSubmit={submit}><div className="brand">TRADE POLICE</div><p className="muted">PROFILE PERSONALIZATION</p><h1>Complete your profile</h1><p className="muted">This takes about a minute and helps Trade Police personalize greetings, reports and your experience.</p><div className="grid grid-2"><label>First name<input name="first_name" defaultValue={current.first_name??''} required/></label><label>Last name<input name="last_name" defaultValue={current.last_name??''} required/></label></div><label>Display name<input name="display_name" defaultValue={current.display_name??''} placeholder="How should Trade Police address you?" required/></label><label>Email<input value={email} disabled/></label><div className="grid grid-2"><label>Experience level<select name="experience_level" defaultValue={current.experience_level??''} required><option value="" disabled>Select</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option><option>Professional</option></select></label><label>Trader type<select name="trader_type" defaultValue={current.trader_type??''} required><option value="" disabled>Select</option><option value="Scalper">Scalper</option><option value="Day trader">Day trader</option><option value="Swing trader">Swing trader</option><option value="Position trader">Position trader</option></select></label></div><button className="primary" disabled={saving}>{saving?'Saving…':'Continue to Trade Police'}</button>{message&&<p className="warning">{message}</p>}</form>;
}
