'use client';

import { useState } from 'react';

type Response='EXACTLY'|'MOSTLY'|'NOT_REALLY';
type Category='MISSING_CONFIRMATION'|'WRONG_INTERPRETATION'|'MISSING_INDICATOR'|'RISK_MANAGEMENT'|'TIMING'|'OTHER';
const categories:[Category,string][]=[['MISSING_CONFIRMATION','Missing confirmation'],['WRONG_INTERPRETATION','Wrong interpretation'],['MISSING_INDICATOR','Missing indicator'],['RISK_MANAGEMENT','Risk management'],['TIMING','Timing'],['OTHER','Other']];

export default function ContextualAnalysisFeedback({analysisId,playbookId,onDismiss}:{analysisId:string;playbookId?:string|null;onDismiss:()=>void}){
  const [response,setResponse]=useState<Response|null>(null),[category,setCategory]=useState<Category|null>(null),[comment,setComment]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
  async function submit(nextResponse=response,nextCategory=category){if(!nextResponse)return;if(nextResponse!=='EXACTLY'&&!nextCategory)return setError('Choose what was missing.');setSaving(true);setError('');try{const request=await fetch('/api/beta-intelligence/feedback',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({analysisId,playbookId:playbookId??null,response:nextResponse,category:nextResponse==='EXACTLY'?null:nextCategory,comment})});if(!request.ok)throw new Error('Feedback could not be saved.');onDismiss()}catch(value){setError(value instanceof Error?value.message:'Feedback could not be saved.')}finally{setSaving(false)}}
  function answer(value:Response){setResponse(value);setCategory(null);setError('');if(value==='EXACTLY')void submit(value,null)}
  return <section className="card contextual-feedback" aria-labelledby="contextual-feedback-title"><button className="contextual-feedback-dismiss" type="button" aria-label="Dismiss feedback" onClick={onDismiss}>×</button><div><p className="muted">BETA FEEDBACK</p><h2 id="contextual-feedback-title">Did this analysis reflect the way you actually trade?</h2></div><div className="button-row contextual-feedback-responses"><button className={response==='EXACTLY'?'selected':undefined} type="button" onClick={()=>answer('EXACTLY')} disabled={saving}>Exactly</button><button className={response==='MOSTLY'?'selected':undefined} type="button" onClick={()=>answer('MOSTLY')} disabled={saving}>Mostly</button><button className={response==='NOT_REALLY'?'selected':undefined} type="button" onClick={()=>answer('NOT_REALLY')} disabled={saving}>Not really</button></div>{response&&response!=='EXACTLY'&&<div className="contextual-feedback-detail"><h3>What was missing?</h3><div className="chip-list">{categories.map(([value,label])=><button className={`chip ${category===value?'selected':''}`} type="button" key={value} onClick={()=>setCategory(value)}>{label}</button>)}</div><label>Optional comments<textarea value={comment} maxLength={1000} onChange={event=>setComment(event.target.value)} placeholder="Tell us what would make the analysis fit your process more closely."/></label><div className="button-row"><button className="primary" type="button" onClick={()=>void submit()} disabled={!category||saving}>{saving?'Saving…':'Send feedback'}</button><button type="button" onClick={onDismiss}>Not now</button></div></div>}{error&&<p className="error" role="alert">{error}</p>}</section>;
}
