'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {useLocale} from '@/components/i18n/LocaleProvider';
import type {Locale} from '@/lib/i18n/config';

type Candidate={id:string;qualification_status:string;owner_consent_status:string;observation_days:number;closed_trades:number;adherence_percent:number|null};
type Policy={minimum_observation_days:number;minimum_closed_trades:number};
type Observation={candidate:Candidate;policy:Policy};

const copy:Record<Locale,Record<string,string>>={
  en:{private:'MARKETPLACE · PRIVATE',loading:'Evaluating privately…',title:'Private observation',unavailable:'Status unavailable.',body:'Trade Police evaluates this exact revision without exposing your rules. Nothing becomes public without your permission.',observation:'Observation',days:'days',trades:'Verified trades',adherence:'Adherence',evidence:'No evidence',consent:'Owner consent',qualified:'This revision reached the evidence threshold. You can authorize Trade Police to send it to internal Compliance review under Marketplace Owner Terms V1.',acknowledge:'I understand that this only authorizes an internal review. It does not publish my strategy or reveal its private rules.',terms:'Read legal and Marketplace terms',saving:'Saving…',authorize:'Authorize internal review',decline:'Decline',saveError:'Consent could not be saved.'},
  es:{private:'MARKETPLACE · PRIVADO',loading:'Evaluando de forma privada…',title:'Observación privada',unavailable:'Estado no disponible.',body:'Trade Police evalúa esta revisión exacta sin exponer tus reglas. Nada se hace público sin tu permiso.',observation:'Observación',days:'días',trades:'Trades verificados',adherence:'Disciplina',evidence:'Sin evidencia',consent:'Consentimiento',qualified:'Esta revisión alcanzó el umbral de evidencia. Puedes autorizar que Trade Police la envíe a revisión interna de Compliance bajo los Términos del Propietario del Marketplace V1.',acknowledge:'Entiendo que esto solo autoriza una revisión interna. No publica mi estrategia ni revela sus reglas privadas.',terms:'Leer términos legales y del Marketplace',saving:'Guardando…',authorize:'Autorizar revisión interna',decline:'Rechazar',saveError:'No se pudo guardar el consentimiento.'},
  fr:{private:'MARKETPLACE · PRIVÉ',loading:'Évaluation privée…',title:'Observation privée',unavailable:'Statut indisponible.',body:'Trade Police évalue cette révision exacte sans exposer vos règles. Rien ne devient public sans votre autorisation.',observation:'Observation',days:'jours',trades:'Trades vérifiés',adherence:'Discipline',evidence:'Aucune preuve',consent:'Consentement',qualified:'Cette révision a atteint le seuil de preuves. Vous pouvez autoriser Trade Police à la soumettre à une revue interne de conformité selon les Conditions Propriétaire Marketplace V1.',acknowledge:'Je comprends que cela autorise uniquement une revue interne. Ma stratégie ne sera pas publiée et ses règles privées ne seront pas révélées.',terms:'Lire les conditions légales et Marketplace',saving:'Enregistrement…',authorize:'Autoriser la revue interne',decline:'Refuser',saveError:'Impossible d’enregistrer le consentement.'},
};
const statuses:Record<Locale,Record<string,string>>={
  en:{OBSERVING:'OBSERVING',INSUFFICIENT_DATA:'INSUFFICIENT DATA',QUALIFIED:'QUALIFIED',OWNER_CONSENT_PENDING:'OWNER CONSENT PENDING',UNDER_REVIEW:'UNDER REVIEW',APPROVED:'APPROVED',DECLINED:'DECLINED',ARCHIVED:'ARCHIVED',NOT_REQUESTED:'NOT REQUESTED',PENDING:'PENDING',GRANTED:'GRANTED',REVOKED:'REVOKED'},
  es:{OBSERVING:'EN OBSERVACIÓN',INSUFFICIENT_DATA:'DATOS INSUFICIENTES',QUALIFIED:'CALIFICADA',OWNER_CONSENT_PENDING:'CONSENTIMIENTO PENDIENTE',UNDER_REVIEW:'EN REVISIÓN',APPROVED:'APROBADA',DECLINED:'RECHAZADA',ARCHIVED:'ARCHIVADA',NOT_REQUESTED:'NO SOLICITADO',PENDING:'PENDIENTE',GRANTED:'AUTORIZADO',REVOKED:'REVOCADO'},
  fr:{OBSERVING:'EN OBSERVATION',INSUFFICIENT_DATA:'DONNÉES INSUFFISANTES',QUALIFIED:'QUALIFIÉE',OWNER_CONSENT_PENDING:'CONSENTEMENT EN ATTENTE',UNDER_REVIEW:'EN COURS DE REVUE',APPROVED:'APPROUVÉE',DECLINED:'REFUSÉE',ARCHIVED:'ARCHIVÉE',NOT_REQUESTED:'NON DEMANDÉ',PENDING:'EN ATTENTE',GRANTED:'AUTORISÉ',REVOKED:'RÉVOQUÉ'},
};

export default function MarketplaceObservationCard({strategyId}:{strategyId:string}){
  const {locale}=useLocale();const c=copy[locale];
  const [data,setData]=useState<Observation|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [acknowledged,setAcknowledged]=useState(false);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/strategies/${strategyId}/marketplace`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(c.unavailable);setData(body);setError('');}catch(caught){setError(caught instanceof Error?caught.message:c.unavailable);}},[c.unavailable,strategyId]);
  useEffect(()=>{void load();},[load]);
  const consent=async(granted:boolean)=>{setBusy(true);try{const response=await fetch(`/api/strategies/${strategyId}/marketplace`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidateId:data?.candidate.id,granted})});if(!response.ok)throw new Error(c.saveError);setAcknowledged(false);await load();}catch(caught){setError(caught instanceof Error?caught.message:c.saveError);}finally{setBusy(false);}};
  if(error)return <section className="card strategy-detail-card"><p className="eyebrow">MARKETPLACE</p><h3>{c.title}</h3><p className="muted">{error}</p></section>;
  if(!data)return <section className="card strategy-detail-card"><p className="eyebrow">MARKETPLACE</p><h3>{c.loading}</h3></section>;
  const candidate=data.candidate,policy=data.policy;const qualified=['OWNER_CONSENT_PENDING','QUALIFIED'].includes(candidate.qualification_status);
  const statusLabel=(value:string)=>statuses[locale][value]??value.replaceAll('_',' ');
  return <section className="card strategy-detail-card marketplace-owner-card"><p className="eyebrow">{c.private}</p><h3>{statusLabel(candidate.qualification_status)}</h3><p className="muted">{c.body}</p><div className="strategy-detail-summary-list"><div className="strategy-detail-meta-row"><span>{c.observation}</span><strong>{candidate.observation_days}/{policy.minimum_observation_days} {c.days}</strong></div><div className="strategy-detail-meta-row"><span>{c.trades}</span><strong>{candidate.closed_trades}/{policy.minimum_closed_trades}</strong></div><div className="strategy-detail-meta-row"><span>{c.adherence}</span><strong>{candidate.adherence_percent==null?c.evidence:`${candidate.adherence_percent}%`}</strong></div><div className="strategy-detail-meta-row"><span>{c.consent}</span><strong>{statusLabel(candidate.owner_consent_status)}</strong></div></div>{qualified?<div className="marketplace-owner-consent"><p>{c.qualified}</p><label className="marketplace-consent-check"><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/><span>{c.acknowledge}</span></label><Link href="/legal">{c.terms}</Link><div className="button-row"><button type="button" className="primary" disabled={busy||!acknowledged} onClick={()=>void consent(true)}>{busy?c.saving:c.authorize}</button><button type="button" className="secondary" disabled={busy} onClick={()=>void consent(false)}>{c.decline}</button></div></div>:null}</section>;
}
