'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {useLocale} from '@/components/i18n/LocaleProvider';
import type {Locale} from '@/lib/i18n/config';

type Candidate={id:string;qualification_status:string;owner_consent_status:string;observation_days:number;observation_started_at:string|null;closed_trades:number;adherence_percent:number|null};
type Policy={minimum_observation_days:number;minimum_closed_trades:number};
type Observation={candidate:Candidate;policy:Policy};

const copy:Record<Locale,Record<string,string>>={
  en:{private:'MARKETPLACE · PRIVATE',loading:'Evaluating privately…',title:'Marketplace path',unavailable:'Status unavailable.',body:'A simple private path from your first real trade to a reviewed listing. Your rules stay private until you explicitly authorize review.',observation:'Observation',days:'days',trades:'Completed trades',adherence:'Rule adherence',evidence:'Waiting for evidence',consent:'Listing permission',notStarted:'Starts automatically when you open the first real trade with this strategy.',tracking:'Day 1 is the first real trade with this strategy. The clock continues across later strategy revisions.',next:'Next step',keepTrading:'Keep using this strategy. Trade Police records eligible days and completed trades automatically.',qualified:'Evidence is ready. Authorize Trade Police to send this revision to internal Compliance review under Marketplace Owner Terms V1.',acknowledge:'I understand that approval publishes sanitized strategy information and verified evidence, but never exposes my private rules or editable source.',terms:'Read legal and Marketplace terms',saving:'Saving…',authorize:'Request listing review',decline:'Not now',saveError:'Consent could not be saved.'},
  es:{private:'MARKETPLACE · PRIVADO',loading:'Evaluando de forma privada…',title:'Camino al Marketplace',unavailable:'Estado no disponible.',body:'Un camino privado y sencillo desde tu primer trade real hasta una publicación revisada. Tus reglas siguen privadas hasta que autorices la revisión.',observation:'Observación',days:'días',trades:'Trades cerrados',adherence:'Disciplina',evidence:'Esperando evidencia',consent:'Permiso para listar',notStarted:'Empieza automáticamente cuando abres el primer trade real con esta estrategia.',tracking:'El primer trade real cuenta como día 1. El reloj continúa aunque después edites la estrategia.',next:'Siguiente paso',keepTrading:'Sigue usando esta estrategia. Trade Police registra automáticamente los días y trades elegibles.',qualified:'La evidencia está lista. Autoriza que Trade Police envíe esta revisión a Compliance bajo los Términos del Propietario del Marketplace V1.',acknowledge:'Entiendo que una aprobación publica información sanitizada y evidencia verificada, pero nunca expone mis reglas privadas ni mi fuente editable.',terms:'Leer términos legales y del Marketplace',saving:'Guardando…',authorize:'Solicitar revisión para listar',decline:'Ahora no',saveError:'No se pudo guardar el consentimiento.'},
  fr:{private:'MARKETPLACE · PRIVÉ',loading:'Évaluation privée…',title:'Parcours Marketplace',unavailable:'Statut indisponible.',body:'Un parcours privé et simple entre votre premier trade réel et une publication contrôlée. Vos règles restent privées jusqu’à votre autorisation.',observation:'Observation',days:'jours',trades:'Trades clôturés',adherence:'Discipline',evidence:'En attente de preuves',consent:'Autorisation de publication',notStarted:'Commence automatiquement au premier trade réel avec cette stratégie.',tracking:'Le premier trade réel compte comme jour 1. Le compteur continue malgré les révisions ultérieures.',next:'Étape suivante',keepTrading:'Continuez à utiliser cette stratégie. Trade Police enregistre automatiquement les jours et trades éligibles.',qualified:'Les preuves sont prêtes. Vous pouvez soumettre cette révision à la revue interne de conformité selon les Conditions Propriétaire Marketplace V1.',acknowledge:'Je comprends qu’une approbation publie des informations filtrées et des preuves vérifiées, sans exposer mes règles privées ni ma source modifiable.',terms:'Lire les conditions légales et Marketplace',saving:'Enregistrement…',authorize:'Demander la revue',decline:'Pas maintenant',saveError:'Impossible d’enregistrer le consentement.'},
};
const statuses:Record<Locale,Record<string,string>>={
  en:{OBSERVING:'OBSERVING',INSUFFICIENT_DATA:'INSUFFICIENT DATA',QUALIFIED:'QUALIFIED',OWNER_CONSENT_PENDING:'OWNER CONSENT PENDING',UNDER_REVIEW:'UNDER REVIEW',APPROVED:'APPROVED',DECLINED:'DECLINED',ARCHIVED:'ARCHIVED',NOT_REQUESTED:'NOT REQUESTED',PENDING:'PENDING',GRANTED:'GRANTED',REVOKED:'REVOKED'},
  es:{OBSERVING:'EN OBSERVACIÓN',INSUFFICIENT_DATA:'DATOS INSUFICIENTES',QUALIFIED:'CALIFICADA',OWNER_CONSENT_PENDING:'CONSENTIMIENTO PENDIENTE',UNDER_REVIEW:'EN REVISIÓN',APPROVED:'APROBADA',DECLINED:'RECHAZADA',ARCHIVED:'ARCHIVADA',NOT_REQUESTED:'NO SOLICITADO',PENDING:'PENDIENTE',GRANTED:'AUTORIZADO',REVOKED:'REVOCADO'},
  fr:{OBSERVING:'EN OBSERVATION',INSUFFICIENT_DATA:'DONNÉES INSUFFISANTES',QUALIFIED:'QUALIFIÉE',OWNER_CONSENT_PENDING:'CONSENTEMENT EN ATTENTE',UNDER_REVIEW:'EN COURS DE REVUE',APPROVED:'APPROUVÉE',DECLINED:'REFUSÉE',ARCHIVED:'ARCHIVÉE',NOT_REQUESTED:'NON DEMANDÉ',PENDING:'EN ATTENTE',GRANTED:'AUTORISÉ',REVOKED:'RÉVOQUÉ'},
};

export default function MarketplaceObservationCard({strategyId}:{strategyId:string}){
  const {locale}=useLocale();const c=copy[locale];
  const [data,setData]=useState<Observation|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [acknowledged,setAcknowledged]=useState(false);
  const load=useCallback(async()=>{try{const response=await fetch(`/api/strategies/${strategyId}/marketplace`,{cache:'no-store'});const body=await response.json();if(!response.ok)throw new Error(c.unavailable);setData(body);setError('');}catch(caught){setError(caught instanceof Error?caught.message:c.unavailable);}},[c.unavailable,strategyId]);
  useEffect(()=>{void load();},[load]);
  const consent=async(granted:boolean)=>{setBusy(true);try{const response=await fetch(`/api/strategies/${strategyId}/marketplace`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({candidateId:data?.candidate.id,granted})});if(!response.ok)throw new Error(c.saveError);setAcknowledged(false);await load();}catch(caught){setError(caught instanceof Error?caught.message:c.saveError);}finally{setBusy(false);}};
  if(error)return <section className="card strategy-detail-card"><p className="eyebrow">MARKETPLACE</p><h3>{c.title}</h3><p className="muted">{error}</p></section>;
  if(!data)return <section className="card strategy-detail-card"><p className="eyebrow">MARKETPLACE</p><h3>{c.loading}</h3></section>;
  const candidate=data.candidate,policy=data.policy;const qualified=['OWNER_CONSENT_PENDING','QUALIFIED'].includes(candidate.qualification_status);
  const statusLabel=(value:string)=>statuses[locale][value]??value.replaceAll('_',' ');const dayProgress=Math.min(100,Math.round(candidate.observation_days/policy.minimum_observation_days*100));const tradeProgress=Math.min(100,Math.round(candidate.closed_trades/policy.minimum_closed_trades*100));
  return <section className="card strategy-detail-card marketplace-owner-card"><p className="eyebrow">{c.private}</p><h3>{c.title}</h3><p className="muted">{c.body}</p><div className="strategy-detail-summary-list"><div className="strategy-detail-meta-row"><span>{c.observation}</span><strong>{candidate.observation_days}/{policy.minimum_observation_days} {c.days}</strong></div><progress max="100" value={dayProgress} aria-label={`${c.observation}: ${dayProgress}%`}/><small className="muted">{candidate.observation_started_at?c.tracking:c.notStarted}</small><div className="strategy-detail-meta-row"><span>{c.trades}</span><strong>{candidate.closed_trades}/{policy.minimum_closed_trades}</strong></div><progress max="100" value={tradeProgress} aria-label={`${c.trades}: ${tradeProgress}%`}/><div className="strategy-detail-meta-row"><span>{c.adherence}</span><strong>{candidate.adherence_percent==null?c.evidence:`${candidate.adherence_percent}%`}</strong></div><div className="strategy-detail-meta-row"><span>{c.consent}</span><strong>{statusLabel(candidate.owner_consent_status)}</strong></div></div>{qualified?<div className="marketplace-owner-consent"><p><strong>{c.next}:</strong> {c.qualified}</p><label className="marketplace-consent-check"><input type="checkbox" checked={acknowledged} onChange={event=>setAcknowledged(event.target.checked)}/><span>{c.acknowledge}</span></label><Link href="/legal">{c.terms}</Link><div className="button-row"><button type="button" className="primary" disabled={busy||!acknowledged} onClick={()=>void consent(true)}>{busy?c.saving:c.authorize}</button><button type="button" className="secondary" disabled={busy} onClick={()=>void consent(false)}>{c.decline}</button></div></div>:<p className="muted"><strong>{c.next}:</strong> {c.keepTrading}</p>}</section>;
}
