import type { StrategyProfile, StrategyRule, StrategySession } from '@/types/trade';
import type { StrategyBuilderV2State } from '@/lib/strategy-builder-v2-persistence';
import type { PersistedV2RuleTreeNode } from '@/lib/strategy-builder-v2';

function value(input: unknown) { return input === undefined || input === null || input === '' ? 'Not configured' : typeof input === 'string' ? input : JSON.stringify(input); }
function Tree({node,depth=0}:{node:PersistedV2RuleTreeNode;depth?:number}){if(node.type==='CONDITION')return <li style={{marginLeft:depth*16}}><strong>{node.requirement}</strong>: {node.ruleKey} {node.timeframe?`— ${node.timeframe}`:''}</li>;return <li style={{marginLeft:depth*16}}><strong>{node.logic}</strong><ul>{node.children.map((child,index)=><Tree key={`${node.logic}-${index}`} node={child} depth={depth+1}/>)}</ul></li>}
export default function StrategyInspector({profile,rules,sessions,v2,onEdit,onDuplicate,onArchive,onRestore,onActivate}:{profile:StrategyProfile;rules:StrategyRule[];sessions:StrategySession[];v2:StrategyBuilderV2State;onEdit:()=>void;onDuplicate:()=>void;onArchive:()=>void;onRestore:()=>void;onActivate:()=>void}){
 const enabled=rules.filter(rule=>rule.enabled); const grouped=(mode:string)=>enabled.filter(rule=>(rule.evaluationMode??'AUTOMATIC')===mode);
 const core=`Trade ${profile.instruments.join(', ')||'no instruments'} during ${sessions.map(item=>item.name).join('/')||'no sessions'}. Use ${v2.contextTimeframe??profile.macroTimeframe??'no context timeframe'} for context and ${v2.executionTimeframe??profile.entryTimeframe??'no execution timeframe'} for execution. Risk ${profile.maximumRiskPercent}%. Minimum RR 1:${profile.minimumRR}.`;
 return <section className="card strategy-inspector" aria-labelledby="strategy-inspector-title"><header><div><p className="muted">SELECTED PERSISTED STRATEGY</p><h2 id="strategy-inspector-title">{profile.name}</h2><p>{profile.isArchived?'Archived':profile.isDefault?'Active':'Saved — not active'}</p></div><div className="button-row"><button onClick={onEdit}>Edit strategy</button><button onClick={onDuplicate}>Duplicate</button>{profile.isArchived?<button onClick={onRestore}>Restore</button>:<><button onClick={onActivate} disabled={profile.isDefault}>Activate</button><button onClick={onArchive} disabled={profile.isDefault}>Archive</button></>}</div></header><section><h3>Strategy Core</h3><p>{core}</p></section><div className="grid grid-3"><Info title="Instruments" value={profile.instruments.join(', ')}/><Info title="Sessions" value={sessions.map(item=>item.name).join(', ')}/><Info title="Timeframes" value={`Context ${v2.contextTimeframe??profile.macroTimeframe??'—'} · Confirmation ${profile.confirmationTimeframe??'—'} · Execution ${v2.executionTimeframe??profile.entryTimeframe??'—'} · Trigger ${profile.triggerTimeframe??'—'}`}/><Info title="Methodologies" value={v2.methodologyIds.join(', ')}/><Info title="Risk / RR" value={`${profile.maximumRiskPercent}% · minimum 1:${profile.minimumRR} · preferred 1:${profile.preferredRR??'—'}`}/><Info title="Limits" value={`Daily trades ${value(profile.maximumTradesPerDay)} · ${JSON.stringify(profile.instrumentTradeLimits??{})}`}/><Info title="Stop logic" value={value(v2.stopLogic??profile.stopLimitSettings)}/><Info title="Target logic" value={value(v2.targetLogic??profile.exitConfig)}/><Info title="News / trend" value={`${profile.newsMode??'—'} · trend alignment ${profile.requireTrendAlignment?'required':'not required'}`}/></div><section><h3>Rule logic</h3>{v2.ruleTree?<ul className="strategy-rule-tree"><Tree node={v2.ruleTree}/></ul>:<p className="muted">No V2 logic tree was persisted. Legacy rules are shown as saved.</p>}<RuleList label="Required" rules={enabled.filter(rule=>rule.mandatory)}/><RuleList label="Optional" rules={enabled.filter(rule=>!rule.mandatory)}/><RuleList label="Automatic" rules={grouped('AUTOMATIC')}/><RuleList label="Manual" rules={grouped('MANUAL')}/><RuleList label="External" rules={grouped('EXTERNAL')}/></section><section><h3>Health</h3><p>{Object.keys(profile.evidenceWeights??{}).length?'Evidence weights saved.':'Missing evidence weights.'} {sessions.length?'':'No sessions configured. '} {profile.stopLimitSettings?.length?'':'Missing stop definition.'}</p></section></section>
}
function Info({title,value:content}:{title:string;value:string}){return <div className="card metric"><span className="muted">{title}</span><strong>{content||'Not configured'}</strong></div>}
function RuleList({label,rules}:{label:string;rules:StrategyRule[]}){return <div><strong>{label}</strong><p>{rules.length?rules.map(rule=>`${rule.label} (${rule.timeframeRole}, ${rule.evaluationMode??'AUTOMATIC'})`).join(' · '):'None'}</p></div>}
