import type {DecisionExplanationState,DecisionExplanationVerdict} from '@/types/intelligence';
import type {DecisionTimeline,DecisionTimelineEvent,DecisionTimelineEventType} from '@/types/decision-timeline';

type TimelineEvidence={id:string;ruleId?:string;title:string;description:string;state:DecisionExplanationState;detectedAt?:string;evidenceIds:string[];deterministic:true};
const rank:Record<DecisionTimelineEventType,number>={MARKET_DATA_VERIFIED:1,RULE_CONFIRMED:2,RULE_BECAME_MISSING:3,RULE_VIOLATED:4,SETUP_DETECTED:5,FINAL_RISK_CHECK_COMPLETED:6,VERDICT_PRODUCED:7,REPORT_SAVED:8};
const ruleEvent:Partial<Record<DecisionExplanationState,{type:DecisionTimelineEventType;state:'CONFIRMED'|'MISSING'|'BLOCKED';description:string}>>={CONFIRMED:{type:'RULE_CONFIRMED',state:'CONFIRMED',description:'This rule was recorded as confirmed.'},MISSING:{type:'RULE_BECAME_MISSING',state:'MISSING',description:'This rule was recorded as missing.'},BLOCKED:{type:'RULE_VIOLATED',state:'BLOCKED',description:'This rule was recorded as violated.'}};
function validTimestamp(value:unknown):value is string{return typeof value==='string'&&value.length>0&&Number.isFinite(Date.parse(value))}
function stableId(value:string){return value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100)||'event'}
export function sortDecisionTimelineEvents(events:DecisionTimelineEvent[]){return [...events].sort((a,b)=>Date.parse(a.timestamp)-Date.parse(b.timestamp)||rank[a.type]-rank[b.type]||a.id.localeCompare(b.id))}
export function buildDecisionTimeline({marketCalculationCompletedAt,marketProvider,evidence,verdict,verdictTimestamp,finalRiskCheckTimestamp,finalRiskCheckStatus}:{marketCalculationCompletedAt?:string;marketProvider?:string;evidence:TimelineEvidence[];verdict:DecisionExplanationVerdict;verdictTimestamp?:string;finalRiskCheckTimestamp?:string;finalRiskCheckStatus?:string}):DecisionTimeline{
  const events:DecisionTimelineEvent[]=[];
  if(validTimestamp(marketCalculationCompletedAt))events.push({id:`market-data-verified:${marketCalculationCompletedAt}`,type:'MARKET_DATA_VERIFIED',timestamp:marketCalculationCompletedAt,title:'Market data verified',description:`Trade Police completed its deterministic market-data calculation${marketProvider?` using ${marketProvider}`:''}.`,state:'INFORMATIONAL',evidenceIds:[],deterministic:true});
  for(const item of evidence){const mapped=ruleEvent[item.state];if(!mapped||!validTimestamp(item.detectedAt))continue;events.push({id:`${mapped.type.toLowerCase()}:${stableId(item.id)}`,type:mapped.type,timestamp:item.detectedAt,title:item.title,description:`${mapped.description} ${item.description}`,state:mapped.state,...(item.ruleId?{ruleId:item.ruleId}:{}),evidenceIds:[...item.evidenceIds],deterministic:true})}
  if(validTimestamp(finalRiskCheckTimestamp))events.push({id:`final-risk-check:${finalRiskCheckTimestamp}`,type:'FINAL_RISK_CHECK_COMPLETED',timestamp:finalRiskCheckTimestamp,title:'Final risk check completed',description:`The deterministic final risk check was recorded as ${finalRiskCheckStatus?.replaceAll('_',' ').toLowerCase()??'completed'}.`,state:finalRiskCheckStatus==='PASSED'?'CONFIRMED':finalRiskCheckStatus==='FAILED'?'BLOCKED':'INFORMATIONAL',evidenceIds:[],deterministic:true});
  if(validTimestamp(verdictTimestamp))events.push({id:`verdict-produced:${verdictTimestamp}`,type:'VERDICT_PRODUCED',timestamp:verdictTimestamp,title:`${verdict.replaceAll('_',' ')} verdict produced`,description:'Trade Police recorded the deterministic verdict shown in this report.',state:verdict==='READY'?'CONFIRMED':verdict==='BLOCKED'?'BLOCKED':verdict==='WAIT'?'MISSING':'INFORMATIONAL',evidenceIds:[],deterministic:true});
  return {events:sortDecisionTimelineEvents(events),detailedTimingAvailable:events.some(event=>event.type.startsWith('RULE_'))};
}
