import type { Direction, EvidenceKey, Instrument, StrategyProfile } from '@/types/trade';
import { normalizeStrategyPolicy, weightedConfidence } from '@/lib/strategy-policy';

export type Candle={datetime:string;open:number;high:number;low:number;close:number};
export type TimeframeAnalysis={timeframe:string;bias:'BULLISH'|'BEARISH'|'RANGE'|'UNCLEAR';lastPrice:number;atr:number;lastSwingHigh:number|null;lastSwingLow:number|null;bosUp:boolean;bosDown:boolean;sweepHigh:boolean;sweepLow:boolean;fvgBullish:boolean;fvgBearish:boolean;retest:boolean;};
export type LiveCandidate={id:string;direction:Direction;entryLow:number;entryHigh:number;stopLoss:number;takeProfit:number;rr:number;status:'READY'|'WAIT'|'INVALID';rationale:string};
export type LiveMarketAnalysis={instrument:Instrument;provider:string;generatedAt:string;timeframes:Record<string,TimeframeAnalysis>;suggestedDirection:Direction|null;setupType:string;setupConfidence:number;waitingFor:string[];evidence:Record<EvidenceKey,{value:boolean;confidence:number;reason:string}>;candidates:LiveCandidate[];warnings:string[];summary:string;};

const avg=(v:number[])=>v.length?v.reduce((a,b)=>a+b,0)/v.length:0;
const round=(n:number,d=5)=>Number(n.toFixed(d));
function atr(c:Candle[],p=14){const xs=c.slice(-p-1);const tr=xs.slice(1).map((x,i)=>Math.max(x.high-x.low,Math.abs(x.high-xs[i].close),Math.abs(x.low-xs[i].close)));return avg(tr);}
function analyzeTf(timeframe:string,c:Candle[]):TimeframeAnalysis{
  if(c.length<25) return {timeframe,bias:'UNCLEAR',lastPrice:c.at(-1)?.close||0,atr:0,lastSwingHigh:null,lastSwingLow:null,bosUp:false,bosDown:false,sweepHigh:false,sweepLow:false,fvgBullish:false,fvgBearish:false,retest:false};
  const last=c.at(-1)!; const fast=avg(c.slice(-10).map(x=>x.close)); const slow=avg(c.slice(-24).map(x=>x.close));
  const recent=c.slice(-8,-1), prior=c.slice(-20,-8); const recentHigh=Math.max(...recent.map(x=>x.high)),recentLow=Math.min(...recent.map(x=>x.low)); const priorHigh=Math.max(...prior.map(x=>x.high)),priorLow=Math.min(...prior.map(x=>x.low));
  const bosUp=last.close>priorHigh, bosDown=last.close<priorLow; const sweepHigh=last.high>priorHigh&&last.close<priorHigh; const sweepLow=last.low<priorLow&&last.close>priorLow;
  let bias:'BULLISH'|'BEARISH'|'RANGE'='RANGE'; if(fast>slow&&last.close>slow)bias='BULLISH'; else if(fast<slow&&last.close<slow)bias='BEARISH';
  const a=atr(c); const fvgBullish=c.length>=3&&c.at(-1)!.low>c.at(-3)!.high; const fvgBearish=c.length>=3&&c.at(-1)!.high<c.at(-3)!.low;
  const retest=Math.abs(last.close-(bias==='BULLISH'?recentHigh:recentLow))<=Math.max(a*.35,last.close*.0002);
  return {timeframe,bias,lastPrice:last.close,atr:round(a),lastSwingHigh:round(recentHigh),lastSwingLow:round(recentLow),bosUp,bosDown,sweepHigh,sweepLow,fvgBullish,fvgBearish,retest};
}
export function buildLiveAnalysis(instrument:Instrument,strategy:StrategyProfile,series:Record<string,Candle[]>,provider:string):LiveMarketAnalysis{
  const policy=normalizeStrategyPolicy(strategy);
  const t=analyzeTf(policy.timeframes.trend,series[policy.timeframes.trend]||[]); const c=analyzeTf(policy.timeframes.confirmation,series[policy.timeframes.confirmation]||[]); const e=analyzeTf(policy.timeframes.entry,series[policy.timeframes.entry]||[]);
  const aligned=t.bias!=='UNCLEAR'&&t.bias===c.bias; const directionalBias=policy.requireTrendAlignment?(aligned?t.bias:null):(c.bias!=='RANGE'&&c.bias!=='UNCLEAR'?c.bias:t.bias); const direction:Direction|null=directionalBias==='BULLISH'?'BUY':directionalBias==='BEARISH'?'SELL':null;
  const bullish=direction==='BUY', bearish=direction==='SELL'; const structure=Boolean(direction)&&(bullish?(c.bosUp||e.bosUp):(c.bosDown||e.bosDown)); const sweep=bullish?(c.sweepLow||e.sweepLow):bearish?(c.sweepHigh||e.sweepHigh):false; const bos=bullish?(c.bosUp||e.bosUp):bearish?(c.bosDown||e.bosDown):false; const fvg=bullish?(c.fvgBullish||e.fvgBullish):bearish?(c.fvgBearish||e.fvgBearish):false; const retest=c.retest||e.retest;
  const ev=(value:boolean,reason:string,confidence= value?82:42)=>({value,confidence,reason});
  const evidence={h4TrendAligned:ev(t.bias!=='RANGE'&&t.bias!=='UNCLEAR',`${strategy.trendTimeframe} bias is ${t.bias}.`),h1TrendAligned:ev(aligned,`${strategy.confirmationTimeframe} bias is ${c.bias}; trend bias is ${t.bias}.`),structurePattern:ev(structure,structure?'A directional break is present in confirmation/entry data.':'No confirmed directional break yet.'),liquiditySweep:ev(sweep,sweep?'A wick swept a prior swing and closed back inside.':'No qualifying sweep detected in the latest window.'),chochConfirmed:ev(sweep&&bos,sweep&&bos?'Sweep followed by directional break approximates ChoCH.':'ChoCH sequence is incomplete.'),bosConfirmed:ev(bos,bos?'Close exceeded a prior swing boundary.':'No confirmed close beyond prior swing.'),orderBlock:ev(false,'Order blocks are not inferred from OHLC alone in v4; optional visual review remains available.',25),fairValueGap:ev(fvg,fvg?'Three-candle imbalance detected.':'No current three-candle imbalance detected.'),retestConfirmed:ev(retest,retest?'Price is retesting a recent structural level.':'Retest is not confirmed.')};
  const setupType=sweep&&bos?'Liquidity Sweep + ChoCH + BoS':fvg?'FVG Retest':structure?'Continuation':'Unclear';
  const confidence=weightedConfidence(evidence,policy); const missingRequired=policy.requiredConfirmations.filter(key=>!evidence[key].value); const setupAllowed=setupType!=='Unclear'&&!policy.forbiddenSetups.includes(setupType)&&(!policy.allowedSetups||policy.allowedSetups.includes(setupType));
  const waitingFor=[...missingRequired, ...(confidence<policy.confidenceThreshold?['confidenceThreshold']:[]), ...(!setupAllowed?['setupClassification']:[])];
  const warnings:string[]=[]; if(policy.requireTrendAlignment&&!aligned)warnings.push('TIMEFRAME CONFLICT: required trend and confirmation timeframes are not aligned.'); if(!direction)warnings.push('No directional authorization candidate while market bias is mixed or ranging.'); if(!setupAllowed)warnings.push('Setup classification is incomplete or not allowed by this strategy.');
  const candidates:LiveCandidate[]=[]; if(direction){const entry=e.lastPrice; const stopBase=direction==='BUY'?(e.lastSwingLow??entry-e.atr):(e.lastSwingHigh??entry+e.atr); const stopSetting=policy.stopPolicy.find(item=>item.instrument===instrument); if(stopSetting&&['ATR','STRUCTURAL'].includes(stopSetting.method))throw new Error(`Unsupported stop method for beta: ${stopSetting.method}.`); const maxStop=strategy.stopLimits[instrument]??Math.max(e.atr*2,e.lastPrice*.01); const rawDist=Math.abs(entry-stopBase); const dist=Math.min(rawDist||e.atr||maxStop,maxStop); const stop=direction==='BUY'?entry-dist:entry+dist; const tp=direction==='BUY'?entry+dist*policy.minimumRR:entry-dist*policy.minimumRR; const ready=waitingFor.length===0; candidates.push({id:'live-primary',direction,entryLow:round(entry),entryHigh:round(entry),stopLoss:round(stop),takeProfit:round(tp),rr:policy.minimumRR,status:ready?'READY':'WAIT',rationale:ready?'Confidence and every mandatory strategy confirmation passed.':`Waiting for ${waitingFor.join(', ')}.`});}
  return {instrument,provider,generatedAt:new Date().toISOString(),timeframes:{[policy.timeframes.trend]:t,[policy.timeframes.confirmation]:c,[policy.timeframes.entry]:e},suggestedDirection:direction,setupType,setupConfidence:confidence,waitingFor,evidence,candidates,warnings,summary:direction?`${instrument} has a ${direction} directional bias under the configured strategy. ${candidates[0]?.status==='READY'?'A rule-based candidate is ready for final police validation.':'Mandatory strategy conditions are still pending.'}`:`${instrument} has no qualifying directional bias under this strategy profile.`};
}
