import Link from 'next/link';
import { getHQContext, HQShell } from '@/lib/hq-page';

function value(input:unknown,suffix=''){return input==null?'No data':`${input}${suffix}`}
function duration(seconds:unknown){const value=Number(seconds);if(!Number.isFinite(value)||value<=0)return 'No data';const minutes=Math.floor(value/60),remaining=Math.round(value%60);return minutes?`${minutes}m ${remaining}s`:`${remaining}s`}

export default async function Page(){
  const {supabase,role,displayName,permissions}=await getHQContext('system.health');
  const [intelligenceResult,feedbackResult]=await Promise.all([supabase.rpc('staff_beta_intelligence_metrics'),supabase.rpc('staff_contextual_feedback_metrics')]);
  if(intelligenceResult.error||feedbackResult.error)throw new Error('Beta Intelligence metrics could not be loaded.');
  const metrics=intelligenceResult.data??{},feedback=feedbackResult.data??{};
  return <HQShell displayName={displayName} role={role} permissions={permissions}><div className="stack"><nav className="sales-subnav"><Link href="/hq/system">Operations</Link><Link href="/hq/system/queue">Action Queue</Link><Link className="active" href="/hq/system/beta-intelligence">Beta Intelligence</Link></nav><section className="hq-section-heading"><div><span className="eyebrow">INTERNAL PRODUCT METRICS</span><h1>Beta Intelligence</h1><p>Methodology teaching, verification, and first-analysis conversion. No market data or personal notes are collected.</p></div></section><section className="beta-intelligence-grid"><Metric label="Onboarding completion rate" value={value(metrics.onboardingCompletionRate,'%')} detail="Completed onboarding ÷ onboarding starts"/><Metric label="Methodology rejection rate" value={value(metrics.methodologyRejectionRate,'%')} detail="Rejected ÷ confirmed or rejected methodology reviews"/><Metric label="Simulation acceptance rate" value={value(metrics.simulationAcceptanceRate,'%')} detail="Approved ÷ completed simulation responses"/><Metric label="First analysis completion rate" value={value(metrics.firstAnalysisCompletionRate,'%')} detail="First completions ÷ first starts"/><Metric label="Average onboarding duration" value={duration(metrics.averageOnboardingDurationSeconds)} detail="Start to completed verification"/></section><section className="grid grid-4 beta-feedback-rankings"><Ranking title="Top missing confirmations" rows={feedback.topMissingConfirmations??[]}/><Ranking title="Most edited playbook rules" rows={feedback.mostEditedPlaybookRules??[]}/><Ranking title="Most rejected simulations" rows={feedback.mostRejectedSimulations??[]}/><Ranking title="Most common feedback categories" rows={feedback.mostCommonFeedbackCategories??[]}/></section><p className="muted">Aggregate based on {Number(metrics.eventCount??0).toLocaleString()} allowlisted events.</p></div></HQShell>;
}

function Metric({label,value,detail}:{label:string;value:string;detail:string}){return <article className="card beta-intelligence-metric"><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
function Ranking({title,rows}:{title:string;rows:Array<{label:string;count:number}>}){return <article className="card beta-feedback-ranking"><h2>{title}</h2>{rows.length?rows.map((row,index)=><div className="event-row" key={`${row.label}:${index}`}><span>{String(row.label).replaceAll('_',' ').toLowerCase()}</span><strong>{row.count}</strong></div>):<p className="muted">No feedback yet.</p>}</article>}
