import { createHash } from 'node:crypto';
import { canonicalStringify, stableFingerprint } from '../../../market-intelligence/serialization/stable-fingerprint.ts';
import type { FairValueGap, FairValueGapStatus } from '../../../market-intelligence/imbalance/fair-value-gap/fair-value-gap-lifecycle-types.ts';
import type { LiquidityTargetStatus, StructuralLiquidityTarget } from '../../../market-intelligence/liquidity/targets/structural-liquidity-target-types.ts';
import type { PreregisteredStrategyComposer, PreregisteredStrategySetupCandidate, StrategyCompositionConfig, StrategyCompositionEdge, StrategyCompositionInput, StrategyCompositionRequest, StrategyCompositionResult, StrategyConditionEvaluation, StrategyConditionStatus, StrategySetupStatus } from './composition-types.ts';

export const XAUUSD_STRUCTURE_PULLBACK_COMPOSER_VERSION = '1.0.0';
export const XAUUSD_STRUCTURE_PULLBACK_DNA_SHA256 = '6ddfec4c112b22535dec5d9660a81e49e4de54d9d4336e0c8c0564000fc05d40';
export const DEFAULT_STRATEGY_COMPOSITION_CONFIG: StrategyCompositionConfig = Object.freeze({ ambiguityPolicy: 'REJECT_AMBIGUOUS', evidenceSelectionPolicy: 'EXACT_SOURCE_REFERENCES', outputOrdering: 'CHRONOLOGICAL', includeRejectedAlternatives: true });
export class StrategyCompositionError extends Error { readonly code: 'INVALID_INPUT' | 'DUPLICATE_INPUT' | 'OUT_OF_ORDER_INCREMENTAL_INPUT'; constructor(code: StrategyCompositionError['code'], message: string) { super(message); this.name = 'StrategyCompositionError'; this.code = code; } }
const t = (v: string): number => { const n = Date.parse(v); if (!Number.isFinite(n)) throw new StrategyCompositionError('INVALID_INPUT', `Invalid timestamp: ${v}.`); return n; };
function freeze<T>(v: T): T { if (v && typeof v === 'object' && !Object.isFrozen(v)) { Object.values(v).forEach(freeze); Object.freeze(v); } return v; }
const sha256 = (value: string): string => createHash('sha256').update(value).digest('hex');
const configFor = (v: Partial<StrategyCompositionConfig> = {}): StrategyCompositionConfig => freeze({ ambiguityPolicy: v.ambiguityPolicy ?? 'REJECT_AMBIGUOUS', evidenceSelectionPolicy: v.evidenceSelectionPolicy ?? 'EXACT_SOURCE_REFERENCES', outputOrdering: v.outputOrdering ?? 'CHRONOLOGICAL', includeRejectedAlternatives: v.includeRejectedAlternatives ?? true });
type Dna = { id?: string; version?: string; instrument?: string; primaryTimeframe?: string; direction?: string; entry?: Record<string, unknown>; stop?: Record<string, unknown>; target?: Record<string, unknown>; invalidation?: unknown; maximumHolding?: unknown; exitPrecedence?: unknown; sessions?: unknown; minimumRewardToRisk?: number; executionAssumptions?: unknown; dependencies?: Array<{ concept?: string; required?: boolean }> };
function parseDna(raw: string): { dna: Dna | null; hash: string; reasons: string[] } {
  const hash = sha256(raw), reasons: string[] = []; let dna: Dna | null = null;
  try { dna = JSON.parse(raw) as Dna; } catch { reasons.push('STRATEGY_DNA_INVALID_JSON'); }
  if (hash !== XAUUSD_STRUCTURE_PULLBACK_DNA_SHA256) reasons.push('STRATEGY_DNA_HASH_MISMATCH');
  if (dna && (dna.id !== 'xauusd-structure-pullback' || dna.version !== '1.0.0')) reasons.push('STRATEGY_IDENTITY_MISMATCH');
  return { dna, hash, reasons };
}
function unique<T>(values: readonly T[], id: (v: T) => string, time: (v: T) => string): T[] { const seen = new Set<string>(); for (const v of values) { if (!id(v) || seen.has(id(v))) throw new StrategyCompositionError('DUPLICATE_INPUT', `Duplicate input ID: ${id(v)}.`); seen.add(id(v)); t(time(v)); } return [...values].sort((a, b) => t(time(a)) - t(time(b)) || id(a).localeCompare(id(b))); }
function gapStatusAt(g: FairValueGap, ref: number): FairValueGapStatus | null { if (t(g.detectedAt) > ref) return null; const states: [string | null, FairValueGapStatus][] = [[g.partiallyMitigatedAt, 'PARTIALLY_MITIGATED'], [g.fullyMitigatedAt, 'FULLY_MITIGATED'], [g.invalidatedAt, 'INVALIDATED'], [g.expiredAt, 'EXPIRED']]; return states.filter((x): x is [string, FairValueGapStatus] => Boolean(x[0]) && t(x[0]!) <= ref).sort((a, b) => t(a[0]) - t(b[0])).at(-1)?.[1] ?? 'ACTIVE'; }
function targetStatusAt(v: StructuralLiquidityTarget, ref: number): LiquidityTargetStatus | null { if (t(v.detectedAt) > ref) return null; const states: [string | null, LiquidityTargetStatus][] = [[v.firstTestedAt, 'TESTED'], [v.sweptAt, 'SWEPT'], [v.brokenAt, 'BROKEN'], [v.invalidatedAt, 'INVALIDATED'], [v.expiredAt, 'EXPIRED']]; return states.filter((x): x is [string, LiquidityTargetStatus] => Boolean(x[0]) && t(x[0]!) <= ref).sort((a, b) => t(a[0]) - t(b[0])).at(-1)?.[1] ?? 'AVAILABLE'; }
type EvalArgs = { id: string; type: string; expected: string; status: StrategyConditionStatus; at: string; events?: string[]; objects?: string[]; facts?: string[]; reason?: string; evidence?: string[] };
function evaluation(a: EvalArgs): StrategyConditionEvaluation { const base = { conditionId: a.id, conditionVersion: '1.0.0', conditionType: a.type, required: true, status: a.status, sourceEventIds: a.events ?? [], sourceObjectIds: a.objects ?? [], evaluatedAt: a.at, expectedRule: a.expected, observedFacts: a.facts ?? [], rejectionReason: a.reason ?? null, evidence: a.evidence ?? [] }; return freeze({ ...base, fingerprint: stableFingerprint(base) }); }
export function resolveStrategySetupStatus(statuses: readonly StrategyConditionStatus[], reasons: { blocking?: readonly string[]; invalid?: readonly string[]; ambiguous?: readonly string[] } = {}): StrategySetupStatus { if (reasons.blocking?.length || statuses.includes('UNSUPPORTED')) return 'BLOCKED'; if (reasons.invalid?.length || statuses.includes('VIOLATED')) return 'INVALID'; if (reasons.ambiguous?.length || statuses.includes('AMBIGUOUS')) return 'AMBIGUOUS'; if (statuses.includes('UNSATISFIED')) return 'INCOMPLETE'; return 'COMPLETE'; }
function createSetup(input: StrategyCompositionInput, direction: 'LONG' | 'SHORT', dnaHash: string, dnaReasons: string[], c: StrategyCompositionConfig): { setup: PreregisteredStrategySetupCandidate; edges: StrategyCompositionEdge[] } {
  const request = input.request, ref = t(request.referenceTimestamp), wanted = direction === 'LONG' ? 'BULLISH' : 'BEARISH', blocking = [...dnaReasons], invalid: string[] = [], ambiguous: string[] = [];
  if (request.strategyId !== 'xauusd-structure-pullback' || request.strategyVersion !== '1.0.0') invalid.push('REQUEST_STRATEGY_IDENTITY_MISMATCH');
  if (request.symbol !== 'XAUUSD') invalid.push('SYMBOL_MUST_BE_XAUUSD'); if (request.timeframe !== 'M15') invalid.push('TIMEFRAME_MUST_BE_M15');
  const snapshots = unique(input.structureSnapshots ?? [], (v) => v.id, (v) => v.processedAt ?? request.referenceTimestamp).filter((v) => v.processedAt && t(v.processedAt) <= ref);
  const transitions = unique(input.transitionEvents ?? [], (v) => v.id, (v) => v.detectedAt).filter((v) => v.accepted && v.direction === wanted && t(v.detectedAt) <= ref && ['MARKET_STRUCTURE_SHIFT', 'CHOCH'].includes(v.classification));
  const transition = transitions.length === 1 ? transitions[0]! : null; if (transitions.length > 1) ambiguous.push('MULTIPLE_ELIGIBLE_STRUCTURE_TRANSITIONS_NO_DNA_SELECTOR');
  const snapshot = transition?.priorStructureSnapshotId ? snapshots.find((v) => v.id === transition.priorStructureSnapshotId) ?? null : null;
  const sweeps = unique(input.sweepEvents ?? [], (v) => v.id, (v) => v.detectedAt).filter((v) => v.accepted && t(v.detectedAt) <= ref);
  const gaps = unique(input.fairValueGaps ?? [], (v) => v.id, (v) => v.detectedAt).filter((v) => v.direction === wanted && ['ACTIVE', 'PARTIALLY_MITIGATED'].includes(gapStatusAt(v, ref) ?? ''));
  const stops = unique(input.stopCandidates ?? [], (v) => v.id, (v) => v.sourceDetectedAt).filter((v) => v.valid && v.direction === (direction === 'LONG' ? 'FOR_LONG' : 'FOR_SHORT') && v.referenceTimestamp === request.referenceTimestamp && v.referencePrice === request.referencePrice);
  const targets = unique(input.liquidityTargets ?? [], (v) => v.id, (v) => v.detectedAt).filter((v) => (direction === 'LONG' ? v.side === 'BUY_SIDE' : v.side === 'SELL_SIDE') && ['AVAILABLE', 'TESTED'].includes(targetStatusAt(v, ref) ?? ''));
  const e: StrategyConditionEvaluation[] = [];
  e.push(evaluation({ id: 'entry.structure-shift', type: 'STRUCTURE_TRANSITION', expected: direction === 'LONG' ? 'Bullish MSS closes above the most recent confirmed opposing swing high.' : 'Bearish MSS closes below the most recent confirmed opposing swing low.', status: transitions.length > 1 ? 'AMBIGUOUS' : transition ? 'SATISFIED' : 'UNSATISFIED', at: request.referenceTimestamp, events: transitions.map((v) => v.id), objects: snapshot ? [snapshot.id] : [], facts: transitions.map((v) => `${v.classification}:${v.direction}`), evidence: transition ? [`Immutable ${transition.classification} ${transition.id} existed before the reference timestamp.`] : ['No unique eligible immutable structure transition was available.'] }));
  e.push(evaluation({ id: 'entry.displacement', type: 'DISPLACEMENT', expected: 'bodySize > max(SIMPLE ATR14 * 1.1, candleRange * 0.65), strict.', status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'DISPLACEMENT_OBSERVATION_NOT_ACCEPTED_BY_COMPOSITION_INPUT', evidence: ['The DNA requires the frozen displacement detector result; this composer does not recalculate it from candles.'] }));
  e.push(evaluation({ id: 'dependency.liquidity-sweep', type: 'LIQUIDITY_SWEEP', expected: 'Liquidity sweep is a required dependency, but no long/short binding or sequence is defined in Strategy DNA.', status: 'UNSUPPORTED', at: request.referenceTimestamp, events: sweeps.map((v) => v.id), reason: 'DNA_OMITS_SWEEP_BINDING_SEMANTICS', evidence: ['No event window, side, or ordering rule may be invented.'] }));
  e.push(evaluation({ id: 'entry.retrace-zone', type: 'FVG_RETRACE', expected: `${wanted} unmitigated FVG created by or immediately following the shift.`, status: 'UNSUPPORTED', at: request.referenceTimestamp, objects: gaps.map((v) => v.id), reason: gaps.length ? 'DNA_DOES_NOT_DEFINE_CREATED_BY_OR_IMMEDIATELY_FOLLOWING_RELATION' : 'NO_ELIGIBLE_FVG', evidence: ['FVG historical state can be reconstructed, but the origin-association rule is not formally defined.'] }));
  e.push(evaluation({ id: 'entry.trigger', type: 'REJECTION_TRIGGER', expected: `First completed M15 candle that rejects the zone and closes ${direction === 'LONG' ? 'above' : 'below'} its open.`, status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'DNA_DOES_NOT_DEFINE_ZONE_REJECTION_GEOMETRY', evidence: ['Candle direction alone cannot substitute for an undefined rejection rule.'] }));
  e.push(evaluation({ id: 'entry.session', type: 'SESSION', expected: 'Trigger and next-open entry inside fixed UTC London or New York window.', status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'TRIGGER_AND_NEXT_OPEN_NOT_DETERMINISTIC', evidence: ['Session windows are exact, but their required trigger and entry timestamps are unresolved.'] }));
  e.push(evaluation({ id: 'entry.timing', type: 'ENTRY_TIMING', expected: 'NEXT_M15_OPEN_AFTER_CONFIRMATION', status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'CONFIRMATION_TRIGGER_UNRESOLVED' }));
  e.push(evaluation({ id: 'entry.zone-expiry', type: 'ZONE_EXPIRY', expected: '20 completed M15 bars.', status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'ORIGINATING_FVG_NOT_UNIQUELY_BOUND' }));
  e.push(evaluation({ id: 'entry.one-per-structure', type: 'ENTRY_CARDINALITY', expected: 'One entry per structure event.', status: transition ? 'SATISFIED' : 'UNSATISFIED', at: request.referenceTimestamp, events: transition ? [transition.id] : [], facts: ['Composer emits at most one setup per direction and reference query.'] }));
  e.push(evaluation({ id: 'risk.structural-stop', type: 'STRUCTURAL_STOP', expected: direction === 'LONG' ? 'min(origin swing low, zone low) - SIMPLE ATR14*0.1' : 'max(origin swing high, zone high) + SIMPLE ATR14*0.1', status: 'UNSUPPORTED', at: request.referenceTimestamp, objects: stops.map((v) => v.id), reason: 'COMBINED_ORIGIN_ZONE_STOP_NOT_PREGENERATED', evidence: [`${stops.length} objective stop candidates were eligible, but none may substitute for the exact combined formula.`] }));
  e.push(evaluation({ id: 'reward.liquidity-target', type: 'LIQUIDITY_TARGET', expected: 'Nearest confirmed opposing swing liquidity beyond entry satisfying minimum RR.', status: targets.length > 1 ? 'AMBIGUOUS' : targets.length === 1 ? 'UNSATISFIED' : 'UNSATISFIED', at: request.referenceTimestamp, objects: targets.map((v) => v.id), reason: 'ENTRY_AND_STOP_REQUIRED_BEFORE_TARGET_RR_FILTER', evidence: [`${targets.length} historical opposing liquidity facts were eligible; selection cannot precede exact entry and stop.`] }));
  e.push(evaluation({ id: 'reward.minimum-rr', type: 'MINIMUM_REWARD_TO_RISK', expected: 'Reward-to-risk >= 2.', status: 'UNSUPPORTED', at: request.referenceTimestamp, reason: 'ENTRY_STOP_TARGET_NOT_EXACT' }));
  e.push(evaluation({ id: 'risk.invalidation', type: 'INVALIDATION', expected: 'Stop touch or completed M15 close beyond structural origin; cancellation on invalidation, expiry, or session end.', status: 'SATISFIED', at: request.referenceTimestamp, facts: ['Deterministic rule is present in immutable DNA.'] }));
  e.push(evaluation({ id: 'exit.maximum-holding', type: 'MAXIMUM_HOLDING', expected: 'Close of 32nd completed M15 bar after entry.', status: 'SATISFIED', at: request.referenceTimestamp, facts: ['Deterministic rule is present in immutable DNA.'] }));
  e.push(evaluation({ id: 'exit.precedence-and-execution', type: 'EXECUTION_ASSUMPTIONS', expected: 'Frozen exit precedence and xauusd-structure-pullback-execution@1.0.0 assumptions.', status: 'SATISFIED', at: request.referenceTimestamp, facts: ['Deterministic rules are present in immutable DNA.'] }));
  const edges: StrategyCompositionEdge[] = e.flatMap((condition) => [...condition.sourceEventIds, ...condition.sourceObjectIds].map((fromId) => { const base = { fromId, toConditionId: condition.conditionId, relationship: (condition.status === 'VIOLATED' ? 'VIOLATES' : condition.conditionId.includes('stop') ? 'SUPPORTS_STOP' : condition.conditionId.includes('target') ? 'SUPPORTS_TARGET' : condition.conditionId.includes('entry') ? 'SUPPORTS_ENTRY' : 'SATISFIES') as StrategyCompositionEdge['relationship'], evidence: [`Immutable source ${fromId} was considered for ${condition.conditionId}.`] }; return freeze({ ...base, fingerprint: stableFingerprint(base) }); }));
  const status = resolveStrategySetupStatus(e.map((v) => v.status), { blocking, invalid, ambiguous }), setupBase = { version: XAUUSD_STRUCTURE_PULLBACK_COMPOSER_VERSION, strategyId: request.strategyId, strategyVersion: request.strategyVersion, strategyDnaHash: dnaHash, direction, symbol: request.symbol, timeframe: request.timeframe, referenceTimestamp: request.referenceTimestamp, referenceCandleIndex: request.referenceCandleIndex ?? null, referencePrice: request.referencePrice ?? null, status, conditionEvaluations: e, sourceStructureSnapshotId: snapshot?.id ?? null, sourceBosEventId: transition?.sourceBosEventId ?? null, sourceTransitionEventId: transition?.id ?? null, sourceSweepEventId: null, sourceFvgId: null, eligibleEntryZone: null, eligibleStopCandidateIds: stops.map((v) => v.id), eligibleLiquidityTargetIds: targets.map((v) => v.id), selectedStopCandidateId: null, selectedLiquidityTargetId: null, ambiguityReasons: ambiguous, blockingReasons: [...blocking, ...e.filter((v) => v.status === 'UNSUPPORTED').map((v) => `${v.conditionId}:${v.rejectionReason}`)], invalidationReasons: invalid, evidence: ['Every immutable Strategy DNA condition was retained.', `Setup classified ${status}; no execution approval is implied.`, 'This setup candidate is a deterministic research composition, not a trade recommendation.'] };
  const fingerprint = stableFingerprint({ ...setupBase, config: c }), setup = freeze({ ...setupBase, id: `preregistered-setup:${fingerprint}`, fingerprint });
  return { setup, edges };
}
export function composePreregisteredStrategySetups(input: StrategyCompositionInput): StrategyCompositionResult {
  const c = configFor(input.config), parsed = parseDna(input.strategyDna); t(input.request.referenceTimestamp);
  const directions: ('LONG' | 'SHORT')[] = input.request.direction ? [input.request.direction] : ['LONG', 'SHORT'];
  const composed = directions.map((direction) => createSetup(input, direction, parsed.hash, parsed.reasons, c)), setups = composed.map((v) => v.setup), compositionGraph = composed.flatMap((v) => v.edges).sort((a, b) => a.toConditionId.localeCompare(b.toConditionId) || a.fromId.localeCompare(b.fromId));
  const evaluations = setups.flatMap((v) => v.conditionEvaluations), coverage = { total: evaluations.length, supported: evaluations.filter((v) => v.status !== 'UNSUPPORTED').length, unsupported: evaluations.filter((v) => v.status === 'UNSUPPORTED').length, satisfied: evaluations.filter((v) => v.status === 'SATISFIED').length, unsatisfied: evaluations.filter((v) => v.status === 'UNSATISFIED').length, violated: evaluations.filter((v) => v.status === 'VIOLATED').length, ambiguous: evaluations.filter((v) => v.status === 'AMBIGUOUS').length };
  const base = { strategyId: input.request.strategyId, strategyVersion: input.request.strategyVersion, strategyDnaHash: parsed.hash, setups, rejectedAlternatives: [], compositionGraph, conditionCoverage: coverage, warnings: parsed.reasons, configuration: c };
  return freeze({ ...base, fingerprint: stableFingerprint(base) });
}
export function serializeStrategyCompositionResult(v: StrategyCompositionResult): string { return canonicalStringify(v); }

export function createPreregisteredStrategyComposer(args: { strategyDna: string; config?: Partial<StrategyCompositionConfig> }): PreregisteredStrategyComposer {
  const config = configFor(args.config), state: Record<string, unknown[]> = { candles: [], confirmedSwings: [], classifiedSwings: [], structureSnapshots: [], bosEvents: [], transitionEvents: [], sweepEvents: [], fairValueGaps: [], fvgLifecycleEvents: [], liquidityTargets: [], liquidityTargetLifecycleEvents: [], stopCandidates: [] }; let watermark = -Infinity;
  const push = <T>(key: string, v: T, id: string, at: string) => { const values = state[key]! as Array<T & { __id?: string; __at?: string }>; if (values.some((x) => x.__id === id)) throw new StrategyCompositionError('DUPLICATE_INPUT', `Duplicate input ID: ${id}.`); if (t(at) <= watermark || (values.length && t(at) < t(values.at(-1)!.__at ?? at))) throw new StrategyCompositionError('OUT_OF_ORDER_INCREMENTAL_INPUT', 'Incremental inputs cannot move backward or alter queried history.'); values.push(freeze({ ...structuredClone(v), __id: id, __at: at } as T & { __id: string; __at: string })); };
  const api: PreregisteredStrategyComposer = {
    pushCandle(v) { push('candles', v, v.openedAt, v.openedAt); }, pushConfirmedSwing(v) { push('confirmedSwings', v, v.id, v.confirmedAt); }, pushClassifiedSwing(v) { push('classifiedSwings', v, v.id, v.processedAt); }, pushStructureSnapshot(v) { if (!v.processedAt) throw new StrategyCompositionError('INVALID_INPUT', 'Snapshot requires processedAt.'); push('structureSnapshots', v, v.id, v.processedAt); },
    pushBosEvent(v) { push('bosEvents', v, v.id, v.detectedAt); }, pushTransitionEvent(v) { push('transitionEvents', v, v.id, v.detectedAt); }, pushSweepEvent(v) { push('sweepEvents', v, v.id, v.detectedAt); }, pushFairValueGap(v) { push('fairValueGaps', v, v.id, v.detectedAt); }, pushFvgLifecycleEvent(v) { push('fvgLifecycleEvents', v, v.id, v.detectedAt); }, pushLiquidityTarget(v) { push('liquidityTargets', v, v.id, v.detectedAt); }, pushLiquidityTargetLifecycleEvent(v) { push('liquidityTargetLifecycleEvents', v, v.id, v.detectedAt); }, pushStopCandidate(v) { push('stopCandidates', v, v.id, v.sourceDetectedAt); },
    compose(request) { const clean = Object.fromEntries(Object.entries(state).map(([k, values]) => [k, values.map((v) => { const copy = { ...(v as Record<string, unknown>) }; delete copy.__id; delete copy.__at; return copy; })])); const result = composePreregisteredStrategySetups({ request, strategyDna: args.strategyDna, config, ...clean } as unknown as StrategyCompositionInput); watermark = Math.max(watermark, t(request.referenceTimestamp)); return result; },
    getWarnings() { return freeze([...parseDna(args.strategyDna).reasons]); }, getDependencyStatus() { const reasons = ['entry.displacement', 'dependency.liquidity-sweep', 'entry.retrace-zone', 'entry.trigger', 'risk.structural-stop', 'reward.minimum-rr']; return freeze({ blocked: true, reasons }); }, reset() { Object.values(state).forEach((v) => { v.length = 0; }); watermark = -Infinity; },
  }; return Object.freeze(api);
}
