import type {Locale} from './config';

const en = {
  customerEmail:'Customer email', password:'Password', wait:'Please wait…', enter:'Enter client portal', create:'Create customer account', forgot:'Forgot password?', createLink:'Create a customer account', existing:'I already have a customer account', created:'Customer account created. Check your email to confirm your account.', signupFailed:'We could not create the account. Please try again. If the problem continues, contact Trade Police support.', badCredentials:'The email or password is incorrect.', staffBlocked:'This account cannot access the client portal. Please use your authorized access link.', recover:'Recover password', recoverIntro:'Enter the email used for your Trade Police account.', email:'Email', sending:'Sending…', sendRecovery:'Send recovery email', recoverySent:'If this email is tied to an account, a secure recovery link has been sent. Please check your email and spam folder.', back:'Back to sign in', invalidLink:'This recovery link is invalid or expired. Request a new email.', newPasswordTitle:'Create a new password', verifying:'Verifying your secure recovery link…', choosePassword:'Choose a secure password with at least 8 characters.', newPassword:'New password', confirmPassword:'Confirm password', saving:'Saving…', savePassword:'Save new password', unusable:'This recovery link cannot be used. Request a new password email below.', requestAgain:'Request another recovery email', passwordLength:'Password must contain at least 8 characters.', passwordMismatch:'Passwords do not match.', passwordUpdated:'Password updated successfully. Redirecting to sign in…', personalization:'PROFILE PERSONALIZATION', completeProfile:'Complete your profile', profileIntro:'This takes about a minute and helps Trade Police personalize greetings, reports and your experience.', firstName:'First name', lastName:'Last name', displayName:'Display name', displayPlaceholder:'How should Trade Police address you?', experience:'Experience level', traderType:'Trader type', select:'Select', beginner:'Beginner', intermediate:'Intermediate', advanced:'Advanced', professional:'Professional', dayTrader:'Day trader', swingTrader:'Swing trader', positionTrader:'Position trader', continue:'Continue to Trade Police'
};
type AuthCopy = typeof en;
const es: AuthCopy = {
  customerEmail:'Correo del cliente', password:'Contraseña', wait:'Espera…', enter:'Entrar al portal', create:'Crear cuenta de cliente', forgot:'¿Olvidaste tu contraseña?', createLink:'Crear una cuenta de cliente', existing:'Ya tengo una cuenta de cliente', created:'Cuenta creada. Revisa tu correo para confirmarla.', signupFailed:'No pudimos crear la cuenta. Inténtalo de nuevo. Si continúa, contacta a soporte de Trade Police.', badCredentials:'El correo o la contraseña son incorrectos.', staffBlocked:'Esta cuenta no puede acceder al portal de clientes. Usa tu enlace de acceso autorizado.', recover:'Recuperar contraseña', recoverIntro:'Ingresa el correo de tu cuenta de Trade Police.', email:'Correo electrónico', sending:'Enviando…', sendRecovery:'Enviar correo de recuperación', recoverySent:'Si este correo corresponde a una cuenta, enviamos un enlace seguro. Revisa tu bandeja de entrada y spam.', back:'Volver a iniciar sesión', invalidLink:'Este enlace de recuperación no es válido o expiró. Solicita uno nuevo.', newPasswordTitle:'Crear una contraseña nueva', verifying:'Verificando tu enlace seguro…', choosePassword:'Elige una contraseña segura de al menos 8 caracteres.', newPassword:'Contraseña nueva', confirmPassword:'Confirmar contraseña', saving:'Guardando…', savePassword:'Guardar contraseña nueva', unusable:'Este enlace no puede usarse. Solicita otro correo de recuperación.', requestAgain:'Solicitar otro correo de recuperación', passwordLength:'La contraseña debe tener al menos 8 caracteres.', passwordMismatch:'Las contraseñas no coinciden.', passwordUpdated:'Contraseña actualizada. Redirigiendo al inicio de sesión…', personalization:'PERSONALIZACIÓN DEL PERFIL', completeProfile:'Completa tu perfil', profileIntro:'Toma cerca de un minuto y permite personalizar saludos, reportes y tu experiencia.', firstName:'Nombre', lastName:'Apellido', displayName:'Nombre visible', displayPlaceholder:'¿Cómo debe llamarte Trade Police?', experience:'Nivel de experiencia', traderType:'Tipo de trader', select:'Seleccionar', beginner:'Principiante', intermediate:'Intermedio', advanced:'Avanzado', professional:'Profesional', dayTrader:'Day trader', swingTrader:'Swing trader', positionTrader:'Position trader', continue:'Continuar a Trade Police'
};
const fr: AuthCopy = {
  customerEmail:'E-mail client', password:'Mot de passe', wait:'Veuillez patienter…', enter:'Accéder au portail client', create:'Créer un compte client', forgot:'Mot de passe oublié?', createLink:'Créer un compte client', existing:'J’ai déjà un compte client', created:'Compte créé. Consultez votre e-mail pour le confirmer.', signupFailed:'Impossible de créer le compte. Réessayez. Si le problème persiste, contactez le support Trade Police.', badCredentials:'L’e-mail ou le mot de passe est incorrect.', staffBlocked:'Ce compte ne peut pas accéder au portail client. Utilisez votre lien autorisé.', recover:'Récupérer le mot de passe', recoverIntro:'Saisissez l’e-mail de votre compte Trade Police.', email:'E-mail', sending:'Envoi…', sendRecovery:'Envoyer l’e-mail de récupération', recoverySent:'Si cet e-mail correspond à un compte, un lien sécurisé a été envoyé. Vérifiez votre boîte de réception et vos spams.', back:'Retour à la connexion', invalidLink:'Ce lien de récupération est invalide ou expiré. Demandez-en un nouveau.', newPasswordTitle:'Créer un nouveau mot de passe', verifying:'Vérification de votre lien sécurisé…', choosePassword:'Choisissez un mot de passe sécurisé d’au moins 8 caractères.', newPassword:'Nouveau mot de passe', confirmPassword:'Confirmer le mot de passe', saving:'Enregistrement…', savePassword:'Enregistrer le nouveau mot de passe', unusable:'Ce lien ne peut pas être utilisé. Demandez un nouvel e-mail ci-dessous.', requestAgain:'Demander un autre e-mail', passwordLength:'Le mot de passe doit contenir au moins 8 caractères.', passwordMismatch:'Les mots de passe ne correspondent pas.', passwordUpdated:'Mot de passe mis à jour. Redirection vers la connexion…', personalization:'PERSONNALISATION DU PROFIL', completeProfile:'Complétez votre profil', profileIntro:'Cela prend environ une minute et personnalise les salutations, rapports et votre expérience.', firstName:'Prénom', lastName:'Nom', displayName:'Nom affiché', displayPlaceholder:'Comment Trade Police doit-il vous appeler?', experience:'Niveau d’expérience', traderType:'Type de trader', select:'Sélectionner', beginner:'Débutant', intermediate:'Intermédiaire', advanced:'Avancé', professional:'Professionnel', dayTrader:'Day trader', swingTrader:'Swing trader', positionTrader:'Position trader', continue:'Continuer vers Trade Police'
};
const copies: Record<Locale, AuthCopy> = {en,es,fr};
export const getAuthCopy = (locale: Locale) => copies[locale];
