import type { Locale } from './config';

const en = {
  active: {
    eyebrow: 'TRADE POLICE / ACTIVE TRADE MONITOR', description: 'Manage the thesis, not the emotion.', noOpen: 'No open trades', noOpenBody: 'Take a trade from the Decision workspace to start monitoring.', analyze: 'Analyze market', openTrades: 'Open trades', awaiting: 'Awaiting re-analysis', restore: 'Restore original trade session', restoreBody: 'This trade was created before session persistence was repaired. Select the session used when you took it; Trade Police will save it during the next re-analysis.', originalSession: 'Original session', selectSession: 'Select session', noAccount: 'No account', strategySnapshot: 'Strategy snapshot', manualSetup: 'Manual setup', refresh: 'Refresh price', reanalyzing: 'Re-analyzing…', reanalyze: 'Re-analyze active trade', close: 'Close trade', against: 'TAKEN AGAINST VERDICT', originalVerdict: 'Original verdict', traderReason: 'Trader reason', entry: 'Entry', currentPrice: 'Current price', currentR: 'Current R', stopLoss: 'Stop loss', takeProfit: 'Take profit', initialRR: 'Initial R:R', mfe: 'MFE', mae: 'MAE', risk: 'Risk', balanceEntry: 'Balance at entry', riskAmount: 'Risk amount', legacyTrade: 'Legacy trade', guidance: 'CURRENT POLICE GUIDANCE', notAnalyzed: 'NOT ANALYZED', guidanceEmpty: 'Run a re-analysis to compare the live market with the original thesis.', updated: 'Updated', eventLog: 'Trade event log', noEvents: 'No monitor events yet.', actionFailed: 'Action failed.', guidanceUpdated: 'Guidance updated', closedSuccess: 'Trade closed successfully',
  },
  close: {
    title: 'CLOSE TRADE', dialog: 'Close trade dialog', exitPrice: 'Exit price', fees: 'Fees / commission', notes: 'Notes', notesPlaceholder: 'What happened?', result: 'Result', pnl: 'Realized P&L', balanceAfter: 'Balance after', legacyTrade: 'Legacy trade', cancel: 'Cancel', updating: 'Updating balance…', confirm: 'Confirm close', failed: 'Could not close trade.',
  },
  decision: {
    eyebrow: 'TRADE POLICE / DECISION', description: 'Should I take this trade?', notFound: 'Saved strategy not found', noActive: 'No active strategy', needsConfiguration: 'Active strategy needs configuration', configure: 'Build or configure strategy',
  },
  auth: {
    signIn: 'Sign in', create: 'Create account', email: 'Email', password: 'Password', wait: 'Please wait…', forgot: 'Forgot password?', createNew: 'Create a new account', existing: 'I already have an account', customerIntro: 'Private trading intelligence, protected by your own account.', accountCreated: 'Account created. Check your email if confirmation is enabled.',
  },
  history: {
    eyebrow: 'TRADE POLICE / HISTORY', description: 'Review past decisions and outcomes as one chronological journal.', journal: 'TRADING JOURNAL', title: 'Your decisions, in context.', intro: 'Trace every market read from evidence to execution and outcome—without rewriting what you knew at the time.', openWorkspace: 'Open decision workspace', openTrades: 'Open trades', closedTrades: 'Closed trades', savedDecisions: 'Saved decisions', realizedR: 'Realized R', activity: 'RECORDED ACTIVITY', timeline: 'Journal timeline', event: 'event', events: 'events', inView: 'in this view', integrity: 'Historical snapshots are never recalculated. Simulation and internal-test records are excluded.', allActivity: 'All activity', trades: 'Trades', decisions: 'Decisions', filter: 'Filter journal', activeFilters: 'Filters active', filterHint: 'Search, dates and record attributes', search: 'Search', searchPlaceholder: 'Instrument or strategy', verdict: 'Verdict', allVerdicts: 'All verdicts', status: 'Status', allStatuses: 'All statuses', open: 'Open', closed: 'Closed', result: 'Result', allResults: 'All results', win: 'Win', loss: 'Loss', breakeven: 'Breakeven', partial: 'Partial', instrument: 'Instrument', allInstruments: 'All instruments', strategy: 'Strategy', allStrategies: 'All strategies', from: 'From', to: 'To', apply: 'Apply filters', clear: 'Clear', loadFailed: 'History could not be loaded', loadFailedBody: 'The recorded journal is temporarily unavailable. Please try again.', noMatches: 'No activity matches these filters', noActivity: 'No recorded activity yet', noMatchesBody: 'Clear or adjust the filters to review other journal entries.', noActivityBody: 'Saved decisions and executed trades will appear here with their original timestamps and context.', clearFilters: 'Clear filters', reviewLive: 'Review a live decision', trade: 'TRADE', decision: 'DECISION', override: 'OVERRIDE', opened: 'Opened', closedAt: 'Closed', setupMissing: 'Setup not recorded', activeSupervision: 'Trade is currently under active supervision.', completedLifecycle: 'This trade has completed its lifecycle.', tradeDetails: 'Trade details', tradeDetailsHint: 'Entry, risk and lifecycle context', entry: 'Entry', stop: 'Stop', target: 'Target', originalVerdict: 'Original verdict', initialRR: 'Initial R:R', risk: 'Risk', notRecorded: 'Not recorded', currentR: 'Current R', inProgress: 'In progress', openDecision: 'Open decision', manageTrade: 'Manage trade', viewAnalytics: 'View analytics', savedMarketDecision: 'Saved market decision', readiness: 'Readiness', freshness: 'Freshness', provider: 'Provider', openReport: 'Open report', notAvailable: 'Not available',
  },
  analytics: {
    eyebrow: 'TRADE POLICE / ANALYTICS', description: 'Turn disciplined execution into evidence.', failed: 'Analytics could not be loaded', failedBody: 'Your closed trades remain recorded. Please refresh and try again.', cockpit: 'PERFORMANCE COCKPIT', emptyTitle: 'Your edge starts with evidence.', emptyBody: 'No closed trades yet. Analytics becomes meaningful after a trade closes with a real outcome.', reviewDecision: 'Review a live decision', openJournal: 'Open trading journal', early: 'Early sample', established: 'Established sample', title: 'Your edge, measured.', intro: 'See what is working, where discipline slips, and which patterns deserve more capital.', canonicalOnly: 'Metrics only count canonical closed trades · Internal simulations excluded', netR: 'Net realized R', closedTrades: 'closed trades', winRate: 'win rate', source: 'Source: active_trades.status = CLOSED', wins: 'wins', losses: 'losses', breakeven: 'breakeven', averageR: 'Average R', expectancy: 'Expectancy per closed trade', profitFactor: 'Profit factor', profitFactorHint: 'Gross winning R ÷ losing R', closedTradesLabel: 'Closed trades', averageWinner: 'Average winner', averageLoser: 'Average loser', account: 'Account', realized: 'REALIZED R', trajectory: 'Performance trajectory', periodChange: 'Period change', trajectoryHint: 'Cumulative R across canonical closed trades, ordered by close time.', noRealized: 'No realized R is available yet.', outcomes: 'OUTCOMES', resultMix: 'Result mix', trades: 'trades', winsLabel: 'Wins', lossesLabel: 'Losses', breakevenLabel: 'Breakeven', discipline: 'DISCIPLINE', activationMode: 'Activation mode', edgeMap: 'EDGE MAP', sourceTitle: 'Where performance comes from', sourceHint: 'Compare expectancy and win rate across the dimensions that shape your execution.', strategy: 'STRATEGY', byPlaybook: 'By playbook', instrument: 'INSTRUMENT', byMarket: 'By market', direction: 'DIRECTION', longShort: 'Long vs short', recent: 'RECENT CLOSED TRADES', latest: 'Latest outcomes', fullJournal: 'Open full journal', trade: 'Trade', outcome: 'Outcome', realizedLabel: 'Realized', decision: 'Decision', noR: 'No R', oneTrade: 'trade', manyTrades: 'trades', winShort: 'win', avg: 'avg', activeAccount: 'Active account', verificationOnly: 'Verification-only records', verificationHint: 'These trades never count toward premium live-performance analytics.', mode: 'Mode',
  },
} as const;

type DeepCatalog<T> = { [K in keyof T]: T[K] extends Record<string, unknown> ? DeepCatalog<T[K]> : string };
export type ScreenCopy = DeepCatalog<typeof en>;

const es: ScreenCopy = {
  active: {
    eyebrow: 'TRADE POLICE / MONITOR DE TRADE ACTIVO', description: 'Gestiona la tesis, no la emoción.', noOpen: 'No hay trades abiertos', noOpenBody: 'Toma un trade desde Decisión para comenzar a monitorearlo.', analyze: 'Analizar mercado', openTrades: 'Trades abiertos', awaiting: 'Esperando reanálisis', restore: 'Restaurar sesión original del trade', restoreBody: 'Este trade se creó antes de reparar la persistencia de sesiones. Selecciona la sesión en que lo tomaste; Trade Police la guardará durante el próximo reanálisis.', originalSession: 'Sesión original', selectSession: 'Seleccionar sesión', noAccount: 'Sin cuenta', strategySnapshot: 'Snapshot de estrategia', manualSetup: 'Setup manual', refresh: 'Actualizar precio', reanalyzing: 'Reanalizando…', reanalyze: 'Reanalizar trade activo', close: 'Cerrar trade', against: 'TOMADO CONTRA EL VEREDICTO', originalVerdict: 'Veredicto original', traderReason: 'Razón del trader', entry: 'Entrada', currentPrice: 'Precio actual', currentR: 'R actual', stopLoss: 'Stop loss', takeProfit: 'Take profit', initialRR: 'R:R inicial', mfe: 'MFE', mae: 'MAE', risk: 'Riesgo', balanceEntry: 'Balance al entrar', riskAmount: 'Monto en riesgo', legacyTrade: 'Trade anterior', guidance: 'GUÍA ACTUAL DE TRADE POLICE', notAnalyzed: 'SIN ANALIZAR', guidanceEmpty: 'Ejecuta un reanálisis para comparar el mercado actual con la tesis original.', updated: 'Actualizado', eventLog: 'Registro de eventos del trade', noEvents: 'Aún no hay eventos de monitoreo.', actionFailed: 'La acción falló.', guidanceUpdated: 'Guía actualizada', closedSuccess: 'Trade cerrado correctamente',
  },
  close: {
    title: 'CERRAR TRADE', dialog: 'Diálogo para cerrar trade', exitPrice: 'Precio de salida', fees: 'Comisiones', notes: 'Notas', notesPlaceholder: '¿Qué ocurrió?', result: 'Resultado', pnl: 'Ganancia/pérdida realizada', balanceAfter: 'Balance final', legacyTrade: 'Trade anterior', cancel: 'Cancelar', updating: 'Actualizando balance…', confirm: 'Confirmar cierre', failed: 'No se pudo cerrar el trade.',
  },
  decision: {
    eyebrow: 'TRADE POLICE / DECISIÓN', description: '¿Debo tomar este trade?', notFound: 'No se encontró la estrategia guardada', noActive: 'No hay una estrategia activa', needsConfiguration: 'La estrategia activa necesita configuración', configure: 'Crear o configurar estrategia',
  },
  auth: {
    signIn: 'Iniciar sesión', create: 'Crear cuenta', email: 'Correo electrónico', password: 'Contraseña', wait: 'Espera…', forgot: '¿Olvidaste tu contraseña?', createNew: 'Crear una cuenta nueva', existing: 'Ya tengo una cuenta', customerIntro: 'Inteligencia privada de trading, protegida por tu propia cuenta.', accountCreated: 'Cuenta creada. Revisa tu correo si la confirmación está activada.',
  },
  history: {
    eyebrow: 'TRADE POLICE / HISTORIAL', description: 'Revisa decisiones y resultados como un solo diario cronológico.', journal: 'DIARIO DE TRADING', title: 'Tus decisiones, con contexto.', intro: 'Sigue cada lectura del mercado desde la evidencia hasta la ejecución y el resultado, sin reescribir lo que sabías en ese momento.', openWorkspace: 'Abrir espacio de decisión', openTrades: 'Trades abiertos', closedTrades: 'Trades cerrados', savedDecisions: 'Decisiones guardadas', realizedR: 'R realizado', activity: 'ACTIVIDAD REGISTRADA', timeline: 'Cronología del diario', event: 'evento', events: 'eventos', inView: 'en esta vista', integrity: 'Los snapshots históricos nunca se recalculan. Se excluyen simulaciones y pruebas internas.', allActivity: 'Toda la actividad', trades: 'Trades', decisions: 'Decisiones', filter: 'Filtrar diario', activeFilters: 'Filtros activos', filterHint: 'Búsqueda, fechas y atributos', search: 'Buscar', searchPlaceholder: 'Instrumento o estrategia', verdict: 'Veredicto', allVerdicts: 'Todos los veredictos', status: 'Estado', allStatuses: 'Todos los estados', open: 'Abierto', closed: 'Cerrado', result: 'Resultado', allResults: 'Todos los resultados', win: 'Ganancia', loss: 'Pérdida', breakeven: 'Breakeven', partial: 'Parcial', instrument: 'Instrumento', allInstruments: 'Todos los instrumentos', strategy: 'Estrategia', allStrategies: 'Todas las estrategias', from: 'Desde', to: 'Hasta', apply: 'Aplicar filtros', clear: 'Limpiar', loadFailed: 'No se pudo cargar el historial', loadFailedBody: 'El diario registrado no está disponible temporalmente. Inténtalo de nuevo.', noMatches: 'Ninguna actividad coincide con estos filtros', noActivity: 'Aún no hay actividad registrada', noMatchesBody: 'Limpia o ajusta los filtros para revisar otras entradas.', noActivityBody: 'Las decisiones guardadas y los trades ejecutados aparecerán aquí con sus marcas de tiempo y contexto originales.', clearFilters: 'Limpiar filtros', reviewLive: 'Revisar una decisión en vivo', trade: 'TRADE', decision: 'DECISIÓN', override: 'OVERRIDE', opened: 'Abierto', closedAt: 'Cerrado', setupMissing: 'Setup no registrado', activeSupervision: 'El trade está bajo supervisión activa.', completedLifecycle: 'Este trade completó su ciclo de vida.', tradeDetails: 'Detalles del trade', tradeDetailsHint: 'Entrada, riesgo y contexto del ciclo', entry: 'Entrada', stop: 'Stop', target: 'Objetivo', originalVerdict: 'Veredicto original', initialRR: 'R:R inicial', risk: 'Riesgo', notRecorded: 'No registrado', currentR: 'R actual', inProgress: 'En progreso', openDecision: 'Abrir decisión', manageTrade: 'Gestionar trade', viewAnalytics: 'Ver analítica', savedMarketDecision: 'Decisión de mercado guardada', readiness: 'Preparación', freshness: 'Actualidad', provider: 'Proveedor', openReport: 'Abrir reporte', notAvailable: 'No disponible',
  },
  analytics: {
    eyebrow: 'TRADE POLICE / ANALÍTICA', description: 'Convierte la ejecución disciplinada en evidencia.', failed: 'No se pudo cargar Analytics', failedBody: 'Tus trades cerrados siguen registrados. Actualiza e inténtalo de nuevo.', cockpit: 'CENTRO DE RENDIMIENTO', emptyTitle: 'Tu ventaja comienza con evidencia.', emptyBody: 'Aún no hay trades cerrados. Analytics cobra sentido cuando un trade cierra con un resultado real.', reviewDecision: 'Revisar una decisión en vivo', openJournal: 'Abrir diario de trading', early: 'Muestra inicial', established: 'Muestra establecida', title: 'Tu ventaja, medida.', intro: 'Descubre qué funciona, dónde falla la disciplina y qué patrones merecen más capital.', canonicalOnly: 'Las métricas sólo cuentan trades cerrados canónicos · Simulaciones internas excluidas', netR: 'R neto realizado', closedTrades: 'trades cerrados', winRate: 'tasa de acierto', source: 'Fuente: active_trades.status = CLOSED', wins: 'ganancias', losses: 'pérdidas', breakeven: 'breakeven', averageR: 'R promedio', expectancy: 'Expectativa por trade cerrado', profitFactor: 'Factor de beneficio', profitFactorHint: 'R bruto ganador ÷ R perdedor', closedTradesLabel: 'Trades cerrados', averageWinner: 'Ganancia promedio', averageLoser: 'Pérdida promedio', account: 'Cuenta', realized: 'R REALIZADO', trajectory: 'Trayectoria de rendimiento', periodChange: 'Cambio del periodo', trajectoryHint: 'R acumulado de trades cerrados canónicos, ordenado por hora de cierre.', noRealized: 'Aún no hay R realizado disponible.', outcomes: 'RESULTADOS', resultMix: 'Distribución de resultados', trades: 'trades', winsLabel: 'Ganancias', lossesLabel: 'Pérdidas', breakevenLabel: 'Breakeven', discipline: 'DISCIPLINA', activationMode: 'Modo de activación', edgeMap: 'MAPA DE VENTAJA', sourceTitle: 'De dónde viene el rendimiento', sourceHint: 'Compara expectativa y tasa de acierto en las dimensiones que forman tu ejecución.', strategy: 'ESTRATEGIA', byPlaybook: 'Por playbook', instrument: 'INSTRUMENTO', byMarket: 'Por mercado', direction: 'DIRECCIÓN', longShort: 'Long vs short', recent: 'TRADES CERRADOS RECIENTES', latest: 'Últimos resultados', fullJournal: 'Abrir diario completo', trade: 'Trade', outcome: 'Resultado', realizedLabel: 'Realizado', decision: 'Decisión', noR: 'Sin R', oneTrade: 'trade', manyTrades: 'trades', winShort: 'acierto', avg: 'prom.', activeAccount: 'Cuenta activa', verificationOnly: 'Registros sólo de verificación', verificationHint: 'Estos trades nunca cuentan para la analítica premium de rendimiento real.', mode: 'Modo',
  },
};

const fr: ScreenCopy = {
  active: {
    eyebrow: 'TRADE POLICE / SUIVI DU TRADE ACTIF', description: 'Gérez la thèse, pas l’émotion.', noOpen: 'Aucun trade ouvert', noOpenBody: 'Prenez un trade depuis Décision pour commencer le suivi.', analyze: 'Analyser le marché', openTrades: 'Trades ouverts', awaiting: 'En attente de réanalyse', restore: 'Restaurer la session initiale du trade', restoreBody: 'Ce trade a été créé avant la correction de la conservation des sessions. Sélectionnez la session utilisée lors de sa prise; Trade Police l’enregistrera à la prochaine réanalyse.', originalSession: 'Session initiale', selectSession: 'Sélectionner une session', noAccount: 'Aucun compte', strategySnapshot: 'Snapshot de stratégie', manualSetup: 'Setup manuel', refresh: 'Actualiser le prix', reanalyzing: 'Réanalyse…', reanalyze: 'Réanalyser le trade actif', close: 'Clôturer le trade', against: 'PRIS CONTRE LE VERDICT', originalVerdict: 'Verdict initial', traderReason: 'Raison du trader', entry: 'Entrée', currentPrice: 'Prix actuel', currentR: 'R actuel', stopLoss: 'Stop loss', takeProfit: 'Take profit', initialRR: 'R:R initial', mfe: 'MFE', mae: 'MAE', risk: 'Risque', balanceEntry: 'Solde à l’entrée', riskAmount: 'Montant risqué', legacyTrade: 'Ancien trade', guidance: 'DIRECTIVE ACTUELLE DE TRADE POLICE', notAnalyzed: 'NON ANALYSÉ', guidanceEmpty: 'Lancez une réanalyse pour comparer le marché actuel à la thèse initiale.', updated: 'Mis à jour', eventLog: 'Journal des événements du trade', noEvents: 'Aucun événement de suivi pour le moment.', actionFailed: 'L’action a échoué.', guidanceUpdated: 'Directive mise à jour', closedSuccess: 'Trade clôturé avec succès',
  },
  close: {
    title: 'CLÔTURER LE TRADE', dialog: 'Fenêtre de clôture du trade', exitPrice: 'Prix de sortie', fees: 'Frais / commission', notes: 'Notes', notesPlaceholder: 'Que s’est-il passé?', result: 'Résultat', pnl: 'P&L réalisé', balanceAfter: 'Solde après clôture', legacyTrade: 'Ancien trade', cancel: 'Annuler', updating: 'Mise à jour du solde…', confirm: 'Confirmer la clôture', failed: 'Impossible de clôturer le trade.',
  },
  decision: {
    eyebrow: 'TRADE POLICE / DÉCISION', description: 'Dois-je prendre ce trade?', notFound: 'Stratégie enregistrée introuvable', noActive: 'Aucune stratégie active', needsConfiguration: 'La stratégie active doit être configurée', configure: 'Créer ou configurer la stratégie',
  },
  auth: {
    signIn: 'Se connecter', create: 'Créer un compte', email: 'E-mail', password: 'Mot de passe', wait: 'Veuillez patienter…', forgot: 'Mot de passe oublié?', createNew: 'Créer un nouveau compte', existing: 'J’ai déjà un compte', customerIntro: 'Une intelligence de trading privée, protégée par votre propre compte.', accountCreated: 'Compte créé. Consultez votre e-mail si la confirmation est activée.',
  },
  history: {
    eyebrow: 'TRADE POLICE / HISTORIQUE', description: 'Consultez décisions et résultats dans un journal chronologique unique.', journal: 'JOURNAL DE TRADING', title: 'Vos décisions, dans leur contexte.', intro: 'Suivez chaque lecture du marché, de la preuve à l’exécution et au résultat, sans réécrire ce que vous saviez alors.', openWorkspace: 'Ouvrir l’espace Décision', openTrades: 'Trades ouverts', closedTrades: 'Trades clôturés', savedDecisions: 'Décisions enregistrées', realizedR: 'R réalisé', activity: 'ACTIVITÉ ENREGISTRÉE', timeline: 'Chronologie du journal', event: 'événement', events: 'événements', inView: 'dans cette vue', integrity: 'Les snapshots historiques ne sont jamais recalculés. Les simulations et tests internes sont exclus.', allActivity: 'Toute l’activité', trades: 'Trades', decisions: 'Décisions', filter: 'Filtrer le journal', activeFilters: 'Filtres actifs', filterHint: 'Recherche, dates et attributs', search: 'Rechercher', searchPlaceholder: 'Instrument ou stratégie', verdict: 'Verdict', allVerdicts: 'Tous les verdicts', status: 'Statut', allStatuses: 'Tous les statuts', open: 'Ouvert', closed: 'Clôturé', result: 'Résultat', allResults: 'Tous les résultats', win: 'Gain', loss: 'Perte', breakeven: 'Équilibre', partial: 'Partiel', instrument: 'Instrument', allInstruments: 'Tous les instruments', strategy: 'Stratégie', allStrategies: 'Toutes les stratégies', from: 'Du', to: 'Au', apply: 'Appliquer les filtres', clear: 'Effacer', loadFailed: 'Impossible de charger l’historique', loadFailedBody: 'Le journal enregistré est temporairement indisponible. Réessayez.', noMatches: 'Aucune activité ne correspond à ces filtres', noActivity: 'Aucune activité enregistrée', noMatchesBody: 'Effacez ou ajustez les filtres pour consulter d’autres entrées.', noActivityBody: 'Les décisions enregistrées et les trades exécutés apparaîtront ici avec leurs horodatages et leur contexte initiaux.', clearFilters: 'Effacer les filtres', reviewLive: 'Examiner une décision en direct', trade: 'TRADE', decision: 'DÉCISION', override: 'OVERRIDE', opened: 'Ouvert', closedAt: 'Clôturé', setupMissing: 'Setup non enregistré', activeSupervision: 'Le trade est actuellement sous surveillance active.', completedLifecycle: 'Ce trade a terminé son cycle de vie.', tradeDetails: 'Détails du trade', tradeDetailsHint: 'Entrée, risque et contexte du cycle', entry: 'Entrée', stop: 'Stop', target: 'Objectif', originalVerdict: 'Verdict initial', initialRR: 'R:R initial', risk: 'Risque', notRecorded: 'Non enregistré', currentR: 'R actuel', inProgress: 'En cours', openDecision: 'Ouvrir la décision', manageTrade: 'Gérer le trade', viewAnalytics: 'Voir les analyses', savedMarketDecision: 'Décision de marché enregistrée', readiness: 'Préparation', freshness: 'Actualité', provider: 'Fournisseur', openReport: 'Ouvrir le rapport', notAvailable: 'Indisponible',
  },
  analytics: {
    eyebrow: 'TRADE POLICE / ANALYSES', description: 'Transformez une exécution disciplinée en preuves.', failed: 'Impossible de charger les analyses', failedBody: 'Vos trades clôturés restent enregistrés. Actualisez et réessayez.', cockpit: 'CENTRE DE PERFORMANCE', emptyTitle: 'Votre avantage commence par les preuves.', emptyBody: 'Aucun trade clôturé. Les analyses deviennent pertinentes après la clôture d’un trade avec un résultat réel.', reviewDecision: 'Examiner une décision en direct', openJournal: 'Ouvrir le journal de trading', early: 'Échantillon initial', established: 'Échantillon établi', title: 'Votre avantage, mesuré.', intro: 'Découvrez ce qui fonctionne, où la discipline faiblit et quels schémas méritent davantage de capital.', canonicalOnly: 'Les métriques comptent uniquement les trades clôturés canoniques · Simulations internes exclues', netR: 'R net réalisé', closedTrades: 'trades clôturés', winRate: 'taux de réussite', source: 'Source : active_trades.status = CLOSED', wins: 'gains', losses: 'pertes', breakeven: 'équilibres', averageR: 'R moyen', expectancy: 'Espérance par trade clôturé', profitFactor: 'Facteur de profit', profitFactorHint: 'R gagnant brut ÷ R perdant', closedTradesLabel: 'Trades clôturés', averageWinner: 'Gain moyen', averageLoser: 'Perte moyenne', account: 'Compte', realized: 'R RÉALISÉ', trajectory: 'Trajectoire de performance', periodChange: 'Variation de la période', trajectoryHint: 'R cumulé des trades clôturés canoniques, classés par heure de clôture.', noRealized: 'Aucun R réalisé disponible.', outcomes: 'RÉSULTATS', resultMix: 'Répartition des résultats', trades: 'trades', winsLabel: 'Gains', lossesLabel: 'Pertes', breakevenLabel: 'Équilibres', discipline: 'DISCIPLINE', activationMode: 'Mode d’activation', edgeMap: 'CARTE DE L’AVANTAGE', sourceTitle: 'Origine de la performance', sourceHint: 'Comparez l’espérance et le taux de réussite selon les dimensions de votre exécution.', strategy: 'STRATÉGIE', byPlaybook: 'Par playbook', instrument: 'INSTRUMENT', byMarket: 'Par marché', direction: 'DIRECTION', longShort: 'Long vs short', recent: 'TRADES RÉCEMMENT CLÔTURÉS', latest: 'Derniers résultats', fullJournal: 'Ouvrir le journal complet', trade: 'Trade', outcome: 'Résultat', realizedLabel: 'Réalisé', decision: 'Décision', noR: 'Sans R', oneTrade: 'trade', manyTrades: 'trades', winShort: 'réussite', avg: 'moy.', activeAccount: 'Compte actif', verificationOnly: 'Enregistrements de vérification uniquement', verificationHint: 'Ces trades ne comptent jamais dans les analyses premium de performance réelle.', mode: 'Mode',
  },
};

const catalogs: Record<Locale, ScreenCopy> = { en, es, fr };
export function getScreenCopy(locale: Locale): ScreenCopy { return catalogs[locale]; }
