import type { DecisionOutcome } from '../decision/decision-types.ts';
import type { DirectionOutcome } from '../direction/direction-types.ts';
import type { MarketIntelligenceV2Flags } from '../feature-flags.ts';
import type { IntelligencePipelineResult } from '../pipeline/intelligence-pipeline-types.ts';
import type { BetaAccess } from './beta-access.ts';

export type ShadowAgreement = 'AGREED' | 'DISAGREED' | 'NOT_COMPARABLE' | 'ERROR';
export type ShadowComparison = { legacyOutcome: string | null; v2Actionability: DecisionOutcome | null; v2Direction: DirectionOutcome | null; agreementStatus: ShadowAgreement; warnings: string[] };
export type BetaIntelligenceView = { label: 'Beta'; informationalOnly: true; direction: DirectionOutcome; actionability: DecisionOutcome; readiness: string; confidencePercent: number | null; evidenceCoveragePercent: number | null; matchedRules: number; failedRequiredRules: string[]; unavailableRequiredRules: string[]; warnings: string[]; message: 'Informational decision support. BUY or SELL is not an order.' };
export type AdminPipelineDiagnostics = { status: IntelligencePipelineResult['status']; stages: Array<{ stage: string; status: string; warnings: string[]; errors: Array<{ code: string; message: string }> }>; shadowComparison: ShadowComparison | null };
export type BetaIntegrationResult<T> = { source: 'LEGACY' | 'V2' | 'UNAVAILABLE'; legacy: T | null; intelligenceV2: BetaIntelligenceView | null; adminDiagnostics: AdminPipelineDiagnostics | null; safeMessage?: string };

export function createBetaView(result: IntelligencePipelineResult): BetaIntelligenceView | null { const direction = result.directionAssessment, decision = result.decisionAssessment, readiness = result.readinessAssessment, confidence = result.confidenceAssessment; if (!direction || !decision || !readiness || !confidence) return null; const ruleName = (id: string) => confidence.contributions.find((item) => item.ruleId === id)?.ruleName ?? 'Required strategy rule'; const warnings = [...new Set([...(confidence.failedRequiredRuleIds.length ? ['Required strategy conditions were not met.'] : []), ...(confidence.unavailableRequiredRuleIds.length ? ['Some required market evidence is unavailable.'] : []), ...(direction.outcome === 'CONFLICTED' ? ['Bullish and bearish evidence conflict.'] : []), ...(result.status === 'PARTIAL' ? ['The beta analysis completed with partial evidence.'] : [])])]; return Object.freeze({ label: 'Beta', informationalOnly: true, direction: direction.outcome, actionability: decision.outcome, readiness: readiness.status, confidencePercent: confidence.confidencePercent, evidenceCoveragePercent: confidence.configuredCoveragePercent, matchedRules: result.strategyContext?.totalMatched ?? 0, failedRequiredRules: confidence.failedRequiredRuleIds.map(ruleName), unavailableRequiredRules: confidence.unavailableRequiredRuleIds.map(ruleName), warnings, message: 'Informational decision support. BUY or SELL is not an order.' }); }
export function compareShadow(legacyOutcome: string | null, result: IntelligencePipelineResult): ShadowComparison { const actionability = result.decisionAssessment?.outcome ?? null, direction = result.directionAssessment?.outcome ?? null; if (result.status === 'ERROR') return Object.freeze({ legacyOutcome, v2Actionability: actionability, v2Direction: direction, agreementStatus: 'ERROR', warnings: ['V2 pipeline failed during shadow comparison.'] }); if (!legacyOutcome || !direction || !['BUY', 'SELL'].includes(direction)) return Object.freeze({ legacyOutcome, v2Actionability: actionability, v2Direction: direction, agreementStatus: 'NOT_COMPARABLE', warnings: [] }); return Object.freeze({ legacyOutcome, v2Actionability: actionability, v2Direction: direction, agreementStatus: legacyOutcome === direction ? 'AGREED' : 'DISAGREED', warnings: [] }); }
export async function integrateBetaAnalysis<T>(options: { flags: MarketIntelligenceV2Flags; access: BetaAccess; legacy: T; legacyOutcome: string | null; runV2: () => Promise<IntelligencePipelineResult> }): Promise<BetaIntegrationResult<T>> { const { flags, access, legacy } = options; if (!access.eligible) return Object.freeze({ source: 'LEGACY', legacy, intelligenceV2: null, adminDiagnostics: null }); try { const result = await options.runV2(); const failed = ['ERROR', 'UNAVAILABLE'].includes(result.status) || !createBetaView(result); const shadow = compareShadow(options.legacyOutcome, result); const diagnostics = access.diagnosticsAllowed ? { status: result.status, stages: result.stages.map((item) => ({ stage: item.stage, status: item.status, warnings: [...item.warnings], errors: item.errors.map(({ code, message }) => ({ code, message })) })), shadowComparison: shadow } : null; if (flags.shadowMode) return Object.freeze({ source: 'LEGACY', legacy, intelligenceV2: access.admin ? createBetaView(result) : null, adminDiagnostics: diagnostics }); if (failed && flags.allowFallback) return Object.freeze({ source: 'LEGACY', legacy, intelligenceV2: null, adminDiagnostics: diagnostics }); if (failed) return Object.freeze({ source: 'UNAVAILABLE', legacy: null, intelligenceV2: null, adminDiagnostics: diagnostics, safeMessage: 'Beta analysis is currently unavailable.' }); return Object.freeze({ source: 'V2', legacy: null, intelligenceV2: createBetaView(result), adminDiagnostics: diagnostics }); } catch { if (flags.allowFallback || flags.shadowMode) return Object.freeze({ source: 'LEGACY', legacy, intelligenceV2: null, adminDiagnostics: access.diagnosticsAllowed ? { status: 'ERROR', stages: [], shadowComparison: { legacyOutcome: options.legacyOutcome, v2Actionability: null, v2Direction: null, agreementStatus: 'ERROR', warnings: ['V2 pipeline was unavailable.'] } } : null }); return Object.freeze({ source: 'UNAVAILABLE', legacy: null, intelligenceV2: null, adminDiagnostics: null, safeMessage: 'Beta analysis is currently unavailable.' }); } }
