import { z } from 'zod';
import { HISTORICAL_DECISION_SCHEMA_VERSION, type HistoricalDecisionReportSnapshot } from '@/types/historical-decision';
import { isSupportedHistoricalReportVersion } from './version-registry';

const optionalText=z.string().min(1).optional();
const evidence=z.object({id:z.string().min(1),ruleId:optionalText,title:z.string().min(1),description:z.string().min(1),state:z.enum(['CONFIRMED','MISSING','BLOCKED','NOT_AVAILABLE','NOT_REQUIRED']),required:z.boolean(),supported:z.boolean(),observedValue:optionalText,expectedValue:optionalText,detectedAt:optionalText,source:optionalText,nextAction:optionalText,evidenceIds:z.array(z.string().min(1)),deterministic:z.literal(true)}).strict();
export const historicalDecisionSnapshotV1Schema=z.object({reportId:z.string().uuid(),schemaVersion:z.literal(HISTORICAL_DECISION_SCHEMA_VERSION),userId:z.string().uuid(),verdict:z.enum(['READY','WAIT','BLOCKED','NO_SETUP','MARKET_CLOSED','DATA_UNAVAILABLE','STRATEGY_INCOMPLETE']),readinessPercent:z.number().min(0).max(100).optional(),confirmedRequiredCount:z.number().int().nonnegative(),totalRequiredCount:z.number().int().nonnegative(),confirmedOptionalCount:z.number().int().nonnegative(),totalOptionalCount:z.number().int().nonnegative(),headline:z.string().min(1),explanation:z.string().min(1),primaryReason:z.string().min(1),nextAction:z.string().min(1),instrument:z.string().min(1),timeframe:z.string().min(1),strategyId:z.string().uuid(),strategyName:z.string().min(1),strategyRevisionId:optionalText,strategyVersion:optionalText,marketData:z.object({provider:z.string().min(1),lastVerifiedCandleAt:optionalText,candleAgeSeconds:z.number().int().nonnegative().optional(),freshness:z.enum(['CURRENT','DELAYED','MARKET_CLOSED','UNAVAILABLE']),calculationCompletedAt:optionalText}).strict(),requiredRules:z.array(evidence),helpfulConfirmations:z.array(evidence),blockingConditions:z.array(evidence),unavailableEvidence:z.array(evidence),notRequiredEvidence:z.array(evidence).optional(),finalRiskCheck:z.object({status:z.enum(['NOT_RUN','PASSED','FAILED','INCOMPLETE']),entryPrice:z.number().finite().optional(),stopPrice:z.number().finite().optional(),targetPrice:z.number().finite().optional(),riskReward:z.number().finite().optional(),riskPercent:z.number().finite().optional(),blockingReasons:z.array(z.string()),overrideEligible:z.boolean(),overrideBlockers:z.array(z.object({id:z.string(),label:z.string(),reason:z.string()}).strict()),vetoes:z.array(z.object({id:z.string(),label:z.string(),overrideable:z.boolean(),actual:z.string().optional(),limit:z.string().optional(),source:z.string().optional(),reason:z.string()}).strict())}).strict().optional(),integrityStatement:z.string().min(1),limitations:z.array(z.string().min(1)),deterministicFingerprint:z.string().regex(/^[a-f0-9]{64}$/),createdAt:z.string().datetime()}).strict();

export type HistoricalSnapshotParseResult={ok:true;snapshot:HistoricalDecisionReportSnapshot}|{ok:false;reason:'INVALID'|'UNSUPPORTED_VERSION';version?:string};
export function parseHistoricalDecisionSnapshot(value:unknown):HistoricalSnapshotParseResult{
  const version=value&&typeof value==='object'&&'schemaVersion' in value?String((value as {schemaVersion?:unknown}).schemaVersion):undefined;
  if(!isSupportedHistoricalReportVersion(version))return {ok:false,reason:'UNSUPPORTED_VERSION',version};
  const parsed=historicalDecisionSnapshotV1Schema.safeParse(value);
  return parsed.success?{ok:true,snapshot:parsed.data}:{ok:false,reason:'INVALID',version};
}
