export type ExecutionEnvironment = { runtime: string; runtimeVersion: string; operatingSystem: string; architecture: string; deployment: string; timezone: string };
export type ResearchArtifactProvenance = {
  provenanceVersion: '1.0.0';
  experimentId: `TP-EXP-${number}-${number}`;
  datasetId: string;
  datasetHash: string;
  datasetCertification: 'CERTIFIED';
  strategyId: string;
  strategyVersion: string;
  compiledStrategyId: string;
  strategyDefinitionHash: string;
  strategyImmutable: true;
  pipelineVersion: string;
  detectorVersions: Readonly<Record<string, string>>;
  decisionPolicyVersion: string;
  readinessPolicyVersion: string;
  directionPolicyVersion: string;
  validationFrameworkVersion: string;
  explainabilityFrameworkVersion: string;
  gitCommitSha: string;
  randomSeed: number;
  configurationHash: string;
  executionTimestamp: string;
  executionEnvironment: ExecutionEnvironment;
  deterministicReplay: true;
  statisticalProtocolLocked: true;
};
export type ReproducibilityCriterion = { id: 'DATASET_CERTIFIED' | 'IMMUTABLE_STRATEGY' | 'FROZEN_ENGINE' | 'DETERMINISTIC_REPLAY' | 'FULL_PROVENANCE' | 'FIXED_RANDOM_SEED' | 'LOCKED_STATISTICAL_PROTOCOL'; passed: boolean; explanation: string };
export type ReproducibilityAssessment = { score: number; fullyReproducible: boolean; criteria: readonly ReproducibilityCriterion[]; issues: readonly string[] };
