import type { IntelligencePipelineResult } from '../pipeline/intelligence-pipeline-types.ts';
import { bootstrapMean, wilsonInterval } from './statistics.ts';
import type { EngineValidationProtocol, ValidationOpportunity } from './validation-types.ts';
import type { DetectorCombination, DetectorExplainabilityAggregate, DetectorInteraction, DetectorOpportunityTrace, DetectorRedundancy, EngineExplainabilitySummary, OpportunityExplainabilityTrace, PipelineTimingTrace, RegimeDetectorFailure } from './explainability-types.ts';

const unique = <T>(values: readonly T[]): T[] => [...new Set(values)];
const observationFired = (status: DetectorOpportunityTrace['status'], payload: unknown): boolean => {
  if (status !== 'DETECTED') return false;
  if (!payload || typeof payload !== 'object') return true;
  const record = payload as Record<string, unknown>, explicit = Object.entries(record).filter(([key, value]) => typeof value === 'boolean' && /(detected|sweep|break|gap|expanded|requirementMet)$/i.test(key));
  if (explicit.length) return explicit.some(([, value]) => value === true);
  for (const key of ['classification', 'direction', 'side']) if (typeof record[key] === 'string') return !['NONE', 'NOT_DETECTED', 'NOT_EXPANDED', 'NOT_DISPLACEMENT', 'NOT_MET', 'CLOSED'].includes(record[key] as string);
  return true;
};
const payloadTag = (detectorId: string, payload: unknown): string[] => {
  if (!payload || typeof payload !== 'object') return [];
  const record = payload as Record<string, unknown>;
  for (const key of ['direction', 'classification', 'side', 'status', 'trendBias']) if (typeof record[key] === 'string') return [`${detectorId}:${record[key]}`];
  return [];
};

export function extractOpportunityExplainability(result: IntelligencePipelineResult, timing: PipelineTimingTrace | null, counterfactualDirection: 'BUY' | 'SELL' | null = null): OpportunityExplainabilityTrace {
  const rules = result.strategyContext?.ruleResults ?? [], confidence = result.confidenceAssessment?.contributions ?? [], failedRequired = new Set([...(result.readinessAssessment?.failedRequiredRuleIds ?? []), ...(result.decisionAssessment?.failedRequiredRuleIds ?? [])]);
  const detectorResults = result.marketContext?.detectorResults ?? [], configuredTotal = result.confidenceAssessment?.configuredWeight ?? 0;
  const detectorTraces: DetectorOpportunityTrace[] = detectorResults.map((detector) => {
    const references = rules.filter((rule) => rule.evidenceReferences.some((reference) => reference.detectorId === detector.detectorId)), referenceIds = new Set(references.map((rule) => rule.ruleId));
    const contributions = confidence.filter((item) => referenceIds.has(item.ruleId));
    const share = (item: typeof contributions[number], field: 'configuredWeight' | 'eligibleWeight' | 'earnedWeight'): number => {
      const rule = references.find((candidate) => candidate.ruleId === item.ruleId), detectorCount = unique(rule?.evidenceReferences.map((reference) => reference.detectorId) ?? []).length;
      return detectorCount ? item[field] / detectorCount : 0;
    };
    const configured = contributions.reduce((sum, item) => sum + share(item, 'configuredWeight'), 0), eligible = contributions.reduce((sum, item) => sum + share(item, 'eligibleWeight'), 0), earned = contributions.reduce((sum, item) => sum + share(item, 'earnedWeight'), 0);
    const blockingRuleIds = references.filter((rule) => failedRequired.has(rule.ruleId) || rule.requirement === 'REQUIRED' && rule.status !== 'MATCHED').map((rule) => rule.ruleId);
    return Object.freeze({ detectorId: detector.detectorId, detectorVersion: detector.detectorVersion, status: detector.status, fired: observationFired(detector.status, detector.payload), blocked: blockingRuleIds.length > 0, blockingRuleIds: Object.freeze(blockingRuleIds), referencedRuleIds: Object.freeze([...referenceIds]), confidenceConfiguredWeight: configured, confidenceEligibleWeight: eligible, confidenceEarnedWeight: earned, readinessContributionPercent: configuredTotal ? earned / configuredTotal * 100 : 0, evidenceIds: Object.freeze(detector.evidence.map((item) => item.id)) });
  });
  const regimeTags = unique(detectorResults.flatMap((detector) => payloadTag(detector.detectorId, detector.payload)));
  const engineDirection = result.directionAssessment?.direction ?? null;
  return Object.freeze({ detectorTraces: Object.freeze(detectorTraces), firedDetectorIds: Object.freeze(detectorTraces.filter((item) => item.fired).map((item) => item.detectorId)), blockingDetectorIds: Object.freeze(detectorTraces.filter((item) => item.blocked).map((item) => item.detectorId)), evidenceGraph: result.evidenceGraph, decisionPath: Object.freeze([...(result.decisionAssessment?.criteria ?? [])]), finalDecisionOutcome: result.decisionAssessment?.outcome ?? null, finalDirection: engineDirection ?? counterfactualDirection, directionSource: engineDirection ? 'ENGINE' : counterfactualDirection ? 'DIAGNOSTIC' : 'UNAVAILABLE', timing, regimeTags: Object.freeze(regimeTags) });
}

const detectorTrace = (row: ValidationOpportunity, detectorId: string) => row.explainability?.detectorTraces.find((item) => item.detectorId === detectorId);
const combination = (rows: readonly ValidationOpportunity[], protocol: EngineValidationProtocol): DetectorCombination[] => {
  const groups = new Map<string, ValidationOpportunity[]>();
  for (const row of rows) { const ids = [...(row.explainability?.firedDetectorIds ?? [])].sort(), key = ids.join('+') || 'NONE'; groups.set(key, [...groups.get(key) ?? [], row]); }
  return [...groups].map(([key, group]) => { const approved = group.filter((row) => row.approved && row.successful !== null), wins = approved.filter((row) => row.successful).length; return { detectorIds: Object.freeze(key === 'NONE' ? [] : key.split('+')), occurrences: group.length, approved: approved.length, wins, successRate: approved.length ? wilsonInterval(wins, approved.length, protocol.confidenceLevel) : null, meanDirectionalReturnBps: bootstrapMean(approved.flatMap((row) => row.directionalReturnBps === null ? [] : [row.directionalReturnBps]), protocol.bootstrapIterations, protocol.seed + group.length, protocol.confidenceLevel) }; });
};

export function aggregateExplainability(rows: readonly ValidationOpportunity[], detectorIds: readonly string[], protocol: EngineValidationProtocol, contributionByDetector: ReadonlyMap<string, DetectorExplainabilityAggregate['predictiveContribution']>): EngineExplainabilitySummary {
  const engineApproved = rows.filter((row) => row.approved && row.successful !== null), engineRate = engineApproved.length ? engineApproved.filter((row) => row.successful).length / engineApproved.length : null;
  const detectors: DetectorExplainabilityAggregate[] = detectorIds.map((detectorId) => {
    const traces = rows.flatMap((row) => { const trace = detectorTrace(row, detectorId); return trace ? [{ row, trace }] : []; }), fired = traces.filter((item) => item.trace.fired), firedApproved = fired.filter((item) => item.row.approved && item.row.successful !== null), falsePositives = firedApproved.filter((item) => item.row.successful === false).length, blockers = traces.filter((item) => item.trace.blocked), rejectedWinners = blockers.filter((item) => !item.row.approved && item.row.successful === true).length;
    const influence = traces.filter((item) => item.trace.blocked || item.trace.confidenceEarnedWeight > 0).length / Math.max(1, traces.length), predictive = contributionByDetector.get(detectorId) ?? 'INCONCLUSIVE';
    const fpRate = firedApproved.length ? falsePositives / firedApproved.length : 0, priority = Math.round((fpRate * .35 + rejectedWinners / Math.max(1, blockers.length) * .35 + (predictive === 'REDUCES_PERFORMANCE' ? .2 : predictive === 'INCONCLUSIVE' ? .1 : 0) + (1 - influence) * .1) * 10_000) / 100;
    return { detectorId, evaluated: traces.length, fired: fired.length, fireRate: traces.length ? wilsonInterval(fired.length, traces.length, protocol.confidenceLevel) : { estimate: 0, lower: 0, upper: 0, confidenceLevel: protocol.confidenceLevel }, blockedTrades: blockers.length, approvedWinsWhenFired: firedApproved.filter((item) => item.row.successful).length, falsePositivesWhenFired: falsePositives, falsePositiveRateWhenFired: firedApproved.length ? wilsonInterval(falsePositives, firedApproved.length, protocol.confidenceLevel) : null, rejectedWinningTradesAttributed: rejectedWinners, falseNegativesAttributed: rejectedWinners, averageConfidenceEarnedWeight: traces.reduce((sum, item) => sum + item.trace.confidenceEarnedWeight, 0) / Math.max(1, traces.length), averageReadinessContributionPercent: traces.reduce((sum, item) => sum + item.trace.readinessContributionPercent, 0) / Math.max(1, traces.length), verdictInfluenceRate: influence, predictiveContribution: predictive, calibrationPriorityScore: priority };
  }).sort((a, b) => b.calibrationPriorityScore - a.calibrationPriorityScore);
  const interactions: DetectorInteraction[] = [];
  for (let left = 0; left < detectorIds.length; left += 1) for (let right = left + 1; right < detectorIds.length; right += 1) {
    const leftId = detectorIds[left]!, rightId = detectorIds[right]!, coFired = rows.filter((row) => detectorTrace(row, leftId)?.fired && detectorTrace(row, rightId)?.fired), approved = coFired.filter((row) => row.approved && row.successful !== null), wins = approved.filter((row) => row.successful).length, success = approved.length ? wins / approved.length : null, lift = success === null || engineRate === null ? null : success - engineRate, interval = approved.length ? wilsonInterval(wins, approved.length, protocol.confidenceLevel) : null;
    interactions.push({ leftDetectorId: leftId, rightDetectorId: rightId, coFired: coFired.length, approved: approved.length, wins, successRate: interval, liftVersusEngine: lift, interpretation: !interval || engineRate === null || interval.lower <= engineRate && interval.upper >= engineRate ? 'INCONCLUSIVE' : interval.lower > engineRate ? 'POSITIVE' : 'NEGATIVE' });
  }
  const combinations = combination(rows, protocol).filter((item) => item.approved >= 5), ranked = [...combinations].sort((a, b) => (b.successRate?.estimate ?? -1) - (a.successRate?.estimate ?? -1));
  const redundancy: DetectorRedundancy[] = interactions.map((pair) => { const leftFired = rows.filter((row) => detectorTrace(row, pair.leftDetectorId)?.fired).length, rightFired = rows.filter((row) => detectorTrace(row, pair.rightDetectorId)?.fired).length, union = leftFired + rightFired - pair.coFired, jaccard = union ? pair.coFired / union : 0, same = rows.filter((row) => detectorTrace(row, pair.leftDetectorId)?.status === detectorTrace(row, pair.rightDetectorId)?.status).length / Math.max(1, rows.length); return { leftDetectorId: pair.leftDetectorId, rightDetectorId: pair.rightDetectorId, jaccardSimilarity: jaccard, sameStateRate: same, interpretation: jaccard >= .9 && same >= .9 ? 'POTENTIALLY_REDUNDANT' as const : 'DISTINCT' as const }; }).sort((a, b) => b.jaccardSimilarity - a.jaccardSimilarity);
  const regimeFailures: RegimeDetectorFailure[] = [];
  const regimes = unique(rows.flatMap((row) => row.explainability?.regimeTags ?? []));
  for (const regime of regimes) for (const detectorId of detectorIds) { const sample = rows.filter((row) => row.approved && row.explainability?.regimeTags.includes(regime) && detectorTrace(row, detectorId)?.fired && row.successful !== null), failures = sample.filter((row) => row.successful === false).length; if (sample.length >= 5) regimeFailures.push({ regime, detectorId, sampleSize: sample.length, failures, failureRate: wilsonInterval(failures, sample.length, protocol.confidenceLevel) }); }
  regimeFailures.sort((a, b) => b.failureRate.estimate - a.failureRate.estimate || b.sampleSize - a.sampleSize);
  const timed = rows.flatMap((row) => row.explainability?.timing ? [row.explainability.timing] : []), stageNames = unique(timed.flatMap((item) => item.stages.map((stage) => stage.stage))), timings = { measuredOpportunities: timed.length, meanTotalDurationMs: timed.length ? timed.reduce((sum, item) => sum + item.totalDurationMs, 0) / timed.length : null, stages: stageNames.map((stage) => { const values = timed.flatMap((item) => item.stages.filter((candidate) => candidate.stage === stage).map((candidate) => candidate.durationMs)); return { stage, samples: values.length, meanMs: values.reduce((a, b) => a + b, 0) / values.length, maximumMs: Math.max(...values) }; }), diagnosticOnly: true as const };
  const calibrationPriority = detectors.map((item) => item.detectorId), mostPredictive = detectors.filter((item) => item.predictiveContribution === 'CONTRIBUTES').sort((a, b) => b.averageReadinessContributionPercent - a.averageReadinessContributionPercent)[0], mostFalsePositive = [...detectors].sort((a, b) => b.falsePositivesWhenFired - a.falsePositivesWhenFired)[0], mostRejectedWinner = [...detectors].sort((a, b) => b.rejectedWinningTradesAttributed - a.rejectedWinningTradesAttributed)[0];
  const leastInfluential = [...detectors].sort((a, b) => a.verdictInfluenceRate - b.verdictInfluenceRate)[0], redundant = redundancy.find((item) => item.interpretation === 'POTENTIALLY_REDUNDANT');
  const conclusions = [mostPredictive ? `${mostPredictive.detectorId} has the strongest statistically supported predictive contribution among detectors labeled CONTRIBUTES.` : 'No detector has a statistically supported positive marginal contribution.', mostFalsePositive ? `${mostFalsePositive.detectorId} appears in the largest number of approved false positives (${mostFalsePositive.falsePositivesWhenFired}).` : 'No false-positive attribution is available.', mostRejectedWinner ? `${mostRejectedWinner.detectorId} blocks the largest number of rejected winning opportunities (${mostRejectedWinner.rejectedWinningTradesAttributed}).` : 'No rejected-winner attribution is available.', leastInfluential ? `${leastInfluential.detectorId} has the lowest observed verdict-influence rate (${(leastInfluential.verdictInfluenceRate * 100).toFixed(1)}%).` : 'No verdict-influence result is available.', redundant ? `${redundant.leftDetectorId} and ${redundant.rightDetectorId} are potentially redundant based on firing and state overlap.` : 'No detector pair meets the configured potential-redundancy threshold.', calibrationPriority[0] ? `${calibrationPriority[0]} has the highest calibration-priority score.` : 'No calibration priority is available.'];
  const opportunities = rows.flatMap((row) => row.explainability ? [{ opportunityId: row.id, evaluatedAt: row.evaluatedAt, approved: row.approved, successful: row.successful, readinessPercent: row.readinessPercent, directionalReturnBps: row.directionalReturnBps, trace: row.explainability }] : []);
  return Object.freeze({ opportunities: Object.freeze(opportunities), detectors, interactionMatrix: interactions, bestCombinations: ranked.slice(0, 10), failingCombinations: ranked.slice(-10).reverse(), redundancy: redundancy.slice(0, 20), regimeFailures: regimeFailures.slice(0, 50), timings, calibrationPriority, conclusions });
}
