-- Trade Police v5: Strategy Builder foundation
-- Safe to run after 002_strategy_profiles.sql.

alter table public.strategy_profiles
  add column if not exists description text not null default '',
  add column if not exists is_archived boolean not null default false,
  add column if not exists market_types text[] not null default array['FOREX'],
  add column if not exists macro_timeframe text,
  add column if not exists trigger_timeframe text,
  add column if not exists preferred_rr numeric not null default 3,
  add column if not exists maximum_daily_risk_percent numeric not null default 1.5,
  add column if not exists maximum_weekly_risk_percent numeric not null default 4,
  add column if not exists maximum_daily_loss_percent numeric not null default 2,
  add column if not exists maximum_total_exposure_percent numeric not null default 2,
  add column if not exists maximum_currency_exposure_percent numeric not null default 1,
  add column if not exists maximum_consecutive_losses integer not null default 5,
  add column if not exists news_mode text not null default 'RELEVANT_CURRENCIES',
  add column if not exists news_block_minutes_before integer not null default 30,
  add column if not exists news_block_minutes_after integer not null default 15,
  add column if not exists news_currencies text[] not null default array['USD','GBP','JPY'],
  add column if not exists preferred_setups text[] not null default array[]::text[],
  add column if not exists reject_unlisted_setups boolean not null default false,
  add column if not exists trailing_config jsonb not null default '{}'::jsonb,
  add column if not exists exit_config jsonb not null default '{}'::jsonb,
  add column if not exists monitor_config jsonb not null default '{}'::jsonb;

create table if not exists public.instrument_catalog (
  id bigint generated by default as identity primary key,
  symbol text not null,
  display_name text not null,
  market_type text not null check (market_type in ('FOREX','FUTURES','STOCKS','ETFS','CRYPTO','INDEX','METALS')),
  category text not null default 'OTHER',
  exchange text,
  country text,
  sector text,
  base_currency text,
  quote_currency text,
  provider_symbol text,
  is_active boolean not null default true,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(symbol, market_type)
);

create table if not exists public.custom_instruments (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  display_name text not null,
  market_type text not null,
  provider_symbol text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(user_id, symbol, market_type)
);

create table if not exists public.strategy_instruments (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  symbol text not null,
  market_type text not null,
  provider_symbol text,
  sort_order integer not null default 0,
  enabled boolean not null default true,
  created_at timestamptz not null default now(),
  unique(strategy_id, symbol, market_type)
);

create table if not exists public.strategy_sessions (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  session_code text not null,
  name text not null,
  timezone text not null default 'UTC',
  start_time time not null,
  end_time time not null,
  days smallint[] not null default array[1,2,3,4,5],
  allow_open_outside boolean not null default false,
  allow_hold_outside boolean not null default true,
  is_custom boolean not null default false,
  created_at timestamptz not null default now(),
  unique(strategy_id, session_code)
);

create table if not exists public.strategy_rules (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rule_key text not null,
  label text not null,
  enabled boolean not null default true,
  mandatory boolean not null default false,
  weight numeric not null default 0 check (weight >= 0 and weight <= 100),
  minimum_confidence integer not null default 0 check (minimum_confidence between 0 and 100),
  timeframe_role text not null default 'CONFIRMATION',
  configuration jsonb not null default '{}'::jsonb,
  sort_order integer not null default 0,
  unique(strategy_id, rule_key)
);

create table if not exists public.strategy_stop_limits (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  instrument text not null,
  method text not null check (method in ('PIPS','POINTS','TICKS','PERCENT','ATR','STRUCTURAL')),
  maximum_value numeric not null check (maximum_value > 0),
  atr_multiplier numeric,
  configuration jsonb not null default '{}'::jsonb,
  unique(strategy_id, instrument)
);

create table if not exists public.strategy_exit_rules (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rule_type text not null,
  enabled boolean not null default true,
  priority integer not null default 0,
  configuration jsonb not null default '{}'::jsonb
);

create table if not exists public.strategy_trailing_rules (
  id uuid primary key default gen_random_uuid(),
  strategy_id uuid not null references public.strategy_profiles(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  rule_type text not null,
  enabled boolean not null default true,
  priority integer not null default 0,
  configuration jsonb not null default '{}'::jsonb
);

create index if not exists strategy_profiles_owner_active_idx
  on public.strategy_profiles(user_id, is_archived, is_default);
create index if not exists strategy_instruments_strategy_idx on public.strategy_instruments(strategy_id);
create index if not exists strategy_sessions_strategy_idx on public.strategy_sessions(strategy_id);
create index if not exists strategy_rules_strategy_idx on public.strategy_rules(strategy_id);
create index if not exists strategy_stop_limits_strategy_idx on public.strategy_stop_limits(strategy_id);
create index if not exists instrument_catalog_search_idx on public.instrument_catalog(market_type, category, symbol);

alter table public.instrument_catalog enable row level security;
alter table public.custom_instruments enable row level security;
alter table public.strategy_instruments enable row level security;
alter table public.strategy_sessions enable row level security;
alter table public.strategy_rules enable row level security;
alter table public.strategy_stop_limits enable row level security;
alter table public.strategy_exit_rules enable row level security;
alter table public.strategy_trailing_rules enable row level security;

-- Public authenticated catalog, private user configuration.
drop policy if exists "instrument_catalog_read" on public.instrument_catalog;
create policy "instrument_catalog_read" on public.instrument_catalog
  for select to authenticated using (is_active = true);

-- Helper macro repeated explicitly so each table remains easy to audit.
drop policy if exists "custom_instruments_own" on public.custom_instruments;
create policy "custom_instruments_own" on public.custom_instruments for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_instruments_own" on public.strategy_instruments;
create policy "strategy_instruments_own" on public.strategy_instruments for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_sessions_own" on public.strategy_sessions;
create policy "strategy_sessions_own" on public.strategy_sessions for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_rules_own" on public.strategy_rules;
create policy "strategy_rules_own" on public.strategy_rules for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_stop_limits_own" on public.strategy_stop_limits;
create policy "strategy_stop_limits_own" on public.strategy_stop_limits for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_exit_rules_own" on public.strategy_exit_rules;
create policy "strategy_exit_rules_own" on public.strategy_exit_rules for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

drop policy if exists "strategy_trailing_rules_own" on public.strategy_trailing_rules;
create policy "strategy_trailing_rules_own" on public.strategy_trailing_rules for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

grant select on public.instrument_catalog to authenticated;
grant select, insert, update, delete on public.custom_instruments to authenticated;
grant select, insert, update, delete on public.strategy_instruments to authenticated;
grant select, insert, update, delete on public.strategy_sessions to authenticated;
grant select, insert, update, delete on public.strategy_rules to authenticated;
grant select, insert, update, delete on public.strategy_stop_limits to authenticated;
grant select, insert, update, delete on public.strategy_exit_rules to authenticated;
grant select, insert, update, delete on public.strategy_trailing_rules to authenticated;

-- Ensure exactly one active profile per user while allowing zero during account setup.
create or replace function public.set_active_strategy(target_strategy_id uuid)
returns void
language plpgsql
security invoker
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.strategy_profiles
    where id = target_strategy_id and user_id = auth.uid() and is_archived = false
  ) then
    raise exception 'Strategy not found or unavailable';
  end if;

  update public.strategy_profiles
  set is_default = false, updated_at = now()
  where user_id = auth.uid() and is_default = true;

  update public.strategy_profiles
  set is_default = true, updated_at = now()
  where id = target_strategy_id and user_id = auth.uid();
end;
$$;

grant execute on function public.set_active_strategy(uuid) to authenticated;

insert into public.instrument_catalog
(symbol, display_name, market_type, category, base_currency, quote_currency, provider_symbol)
values
('EURUSD','Euro / US Dollar','FOREX','MAJOR','EUR','USD','EUR/USD'),
('GBPUSD','British Pound / US Dollar','FOREX','MAJOR','GBP','USD','GBP/USD'),
('USDJPY','US Dollar / Japanese Yen','FOREX','MAJOR','USD','JPY','USD/JPY'),
('USDCHF','US Dollar / Swiss Franc','FOREX','MAJOR','USD','CHF','USD/CHF'),
('AUDUSD','Australian Dollar / US Dollar','FOREX','MAJOR','AUD','USD','AUD/USD'),
('USDCAD','US Dollar / Canadian Dollar','FOREX','MAJOR','USD','CAD','USD/CAD'),
('NZDUSD','New Zealand Dollar / US Dollar','FOREX','MAJOR','NZD','USD','NZD/USD'),
('EURGBP','Euro / British Pound','FOREX','MINOR','EUR','GBP','EUR/GBP'),
('EURJPY','Euro / Japanese Yen','FOREX','CROSS','EUR','JPY','EUR/JPY'),
('EURCHF','Euro / Swiss Franc','FOREX','MINOR','EUR','CHF','EUR/CHF'),
('EURAUD','Euro / Australian Dollar','FOREX','CROSS','EUR','AUD','EUR/AUD'),
('EURCAD','Euro / Canadian Dollar','FOREX','CROSS','EUR','CAD','EUR/CAD'),
('EURNZD','Euro / New Zealand Dollar','FOREX','CROSS','EUR','NZD','EUR/NZD'),
('GBPJPY','British Pound / Japanese Yen','FOREX','CROSS','GBP','JPY','GBP/JPY'),
('GBPCHF','British Pound / Swiss Franc','FOREX','CROSS','GBP','CHF','GBP/CHF'),
('GBPAUD','British Pound / Australian Dollar','FOREX','CROSS','GBP','AUD','GBP/AUD'),
('GBPCAD','British Pound / Canadian Dollar','FOREX','CROSS','GBP','CAD','GBP/CAD'),
('GBPNZD','British Pound / New Zealand Dollar','FOREX','CROSS','GBP','NZD','GBP/NZD'),
('AUDJPY','Australian Dollar / Japanese Yen','FOREX','CROSS','AUD','JPY','AUD/JPY'),
('AUDNZD','Australian Dollar / New Zealand Dollar','FOREX','CROSS','AUD','NZD','AUD/NZD'),
('AUDCAD','Australian Dollar / Canadian Dollar','FOREX','CROSS','AUD','CAD','AUD/CAD'),
('AUDCHF','Australian Dollar / Swiss Franc','FOREX','CROSS','AUD','CHF','AUD/CHF'),
('CADJPY','Canadian Dollar / Japanese Yen','FOREX','CROSS','CAD','JPY','CAD/JPY'),
('CADCHF','Canadian Dollar / Swiss Franc','FOREX','CROSS','CAD','CHF','CAD/CHF'),
('CHFJPY','Swiss Franc / Japanese Yen','FOREX','CROSS','CHF','JPY','CHF/JPY'),
('NZDJPY','New Zealand Dollar / Japanese Yen','FOREX','CROSS','NZD','JPY','NZD/JPY'),
('NZDCAD','New Zealand Dollar / Canadian Dollar','FOREX','CROSS','NZD','CAD','NZD/CAD'),
('NZDCHF','New Zealand Dollar / Swiss Franc','FOREX','CROSS','NZD','CHF','NZD/CHF'),
('USDNOK','US Dollar / Norwegian Krone','FOREX','EXOTIC','USD','NOK','USD/NOK'),
('USDSEK','US Dollar / Swedish Krona','FOREX','EXOTIC','USD','SEK','USD/SEK'),
('USDMXN','US Dollar / Mexican Peso','FOREX','EXOTIC','USD','MXN','USD/MXN'),
('USDZAR','US Dollar / South African Rand','FOREX','EXOTIC','USD','ZAR','USD/ZAR'),
('USDTRY','US Dollar / Turkish Lira','FOREX','EXOTIC','USD','TRY','USD/TRY'),
('XAUUSD','Gold / US Dollar','METALS','METAL','XAU','USD','XAU/USD'),
('XAGUSD','Silver / US Dollar','METALS','METAL','XAG','USD','XAG/USD')
on conflict (symbol, market_type) do update set
  display_name = excluded.display_name,
  category = excluded.category,
  provider_symbol = excluded.provider_symbol,
  is_active = true;
