-- Trade Police V21 — auditable Compliance case management.

alter table public.compliance_cases drop constraint if exists compliance_cases_status_check;
alter table public.compliance_cases drop constraint if exists compliance_cases_severity_check;
alter table public.compliance_cases add column if not exists title text;
alter table public.compliance_cases add column if not exists description text;
alter table public.compliance_cases add column if not exists created_by uuid references auth.users(id) on delete set null;
alter table public.compliance_cases add column if not exists due_at timestamptz;
alter table public.compliance_cases add column if not exists decision text;
alter table public.compliance_cases add column if not exists resolution text;
alter table public.compliance_cases add column if not exists updated_at timestamptz not null default now();
update public.compliance_cases set title=coalesce(nullif(title,''),summary),description=coalesce(description,summary) where title is null or description is null;
update public.compliance_cases set status='UNDER_REVIEW' where status='REVIEWING';
alter table public.compliance_cases alter column title set not null;
alter table public.compliance_cases add constraint compliance_cases_status_check check(status in ('NEW','OPEN','ASSIGNED','UNDER_REVIEW','AWAITING_EVIDENCE','AWAITING_CUSTOMER','DECISION_PENDING','MONITORING','RESOLVED','DISMISSED','CLOSED')) not valid;
alter table public.compliance_cases validate constraint compliance_cases_status_check;
alter table public.compliance_cases add constraint compliance_cases_severity_check check(severity in ('INFO','LOW','MEDIUM','WARNING','HIGH','CRITICAL')) not valid;
alter table public.compliance_cases validate constraint compliance_cases_severity_check;

create table if not exists public.compliance_evidence(id uuid primary key default gen_random_uuid(),case_id uuid not null references public.compliance_cases(id) on delete cascade,evidence_type text not null,source_table text,source_id text,description text not null,metadata jsonb not null default '{}'::jsonb,added_by uuid not null references auth.users(id) on delete restrict,occurred_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.compliance_case_updates(id bigint generated always as identity primary key,case_id uuid not null references public.compliance_cases(id) on delete cascade,previous_status text,new_status text not null,note text,created_by uuid not null references auth.users(id) on delete restrict,created_at timestamptz not null default now());
alter table public.compliance_evidence enable row level security;alter table public.compliance_case_updates enable row level security;
revoke all on public.compliance_evidence,public.compliance_case_updates from anon,authenticated;
create index if not exists compliance_cases_review_idx on public.compliance_cases(status,severity,due_at,created_at desc);
create index if not exists compliance_cases_customer_idx on public.compliance_cases(customer_user_id,created_at desc);
create index if not exists compliance_cases_assigned_idx on public.compliance_cases(assigned_to,status,due_at);
create index if not exists compliance_evidence_case_idx on public.compliance_evidence(case_id,created_at desc);
create index if not exists compliance_updates_case_idx on public.compliance_case_updates(case_id,created_at desc);

create or replace function public.staff_compliance_overview() returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;begin if not public.has_staff_permission('compliance.view') then raise exception 'Compliance view permission denied';end if;select jsonb_build_object(
 'openCases',(select count(*) from public.compliance_cases where status not in ('RESOLVED','DISMISSED','CLOSED')),
 'highPriority',(select count(*) from public.compliance_cases where status not in ('RESOLVED','DISMISSED','CLOSED') and severity in ('HIGH','CRITICAL')),
 'awaitingReview',(select count(*) from public.compliance_cases where status in ('NEW','OPEN','ASSIGNED')),
 'policyFlags7d',(select count(*) from public.security_events where created_at>=now()-interval '7 days' and lower(coalesce(metadata->>'compliance_relevant','false'))='true'),
 'resolved30d',(select count(*) from public.compliance_cases where resolved_at>=now()-interval '30 days'),
 'auditEvents7d',(select count(*) from public.admin_access_logs where created_at>=now()-interval '7 days' and (resource_type ilike '%COMPLIANCE%' or action in ('CHANGE_STAFF_PERMISSION','SUSPEND_CUSTOMER','RESTORE_CUSTOMER'))),
 'overdue',(select count(*) from public.compliance_cases where status not in ('RESOLVED','DISMISSED','CLOSED') and due_at<now()),
 'queue',coalesce((select jsonb_agg(x) from (select c.id,c.title,c.case_type,c.severity,c.status,c.customer_user_id,p.display_name,p.email,c.assigned_to,c.created_at,c.due_at,(select count(*) from public.compliance_evidence e where e.case_id=c.id) evidence_count,case when c.severity='CRITICAL' then 'Critical unresolved case' when c.severity='HIGH' then 'High-severity case' when c.due_at<now() then 'Internal review overdue' when c.assigned_to is null then 'Unassigned case' when not exists(select 1 from public.compliance_evidence e where e.case_id=c.id) then 'Missing evidence' when c.status='DECISION_PENDING' then 'Awaiting final decision' when c.status='AWAITING_CUSTOMER' then 'Awaiting customer response' else 'Open review' end attention_reason from public.compliance_cases c left join public.profiles p on p.id=c.customer_user_id where c.status not in ('RESOLVED','DISMISSED','CLOSED') order by case c.severity when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 when 'WARNING' then 4 else 5 end,c.due_at asc nulls last,c.created_at limit 10)x),'[]'::jsonb),
 'policyFlags',coalesce((select jsonb_agg(x) from (select id,event_type,severity,user_id,created_at,metadata from public.security_events where lower(coalesce(metadata->>'compliance_relevant','false'))='true' order by created_at desc limit 8)x),'[]'::jsonb),
 'auditEvidence',coalesce((select jsonb_agg(x) from (select id,staff_user_id,customer_user_id,action,resource_type,resource_id,success,created_at from public.admin_access_logs where resource_type ilike '%COMPLIANCE%' or action in ('CHANGE_STAFF_PERMISSION','SUSPEND_CUSTOMER','RESTORE_CUSTOMER') order by created_at desc limit 10)x),'[]'::jsonb),
 'activity',coalesce((select jsonb_agg(x) from (select u.id,u.case_id,u.new_status,u.note,u.created_by,u.created_at,c.title from public.compliance_case_updates u join public.compliance_cases c on c.id=u.case_id order by u.created_at desc limit 10)x),'[]'::jsonb)
 )into result;return result;end;$$;

create or replace function public.staff_compliance_cases(p_query text default '',p_page integer default 1,p_page_size integer default 25,p_severity text default 'ALL',p_status text default 'ALL',p_case_type text default 'ALL',p_overdue text default 'ALL',p_sort text default 'PRIORITY',p_direction text default 'ASC')returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;begin if not public.has_staff_permission('compliance.view') then raise exception 'Compliance view permission denied';end if;with f as(select c.*,p.display_name,p.email,(select count(*) from public.compliance_evidence e where e.case_id=c.id)evidence_count,count(*) over()total_count from public.compliance_cases c left join public.profiles p on p.id=c.customer_user_id where (nullif(trim(p_query),'') is null or concat_ws(' ',c.title,c.summary,c.case_type,p.display_name,p.email) ilike '%'||trim(p_query)||'%') and (upper(p_severity)='ALL' or c.severity=upper(p_severity)) and (upper(p_status)='ALL' or c.status=upper(p_status)) and (upper(p_case_type)='ALL' or upper(c.case_type)=upper(p_case_type)) and (upper(p_overdue)='ALL' or (upper(p_overdue)='OVERDUE' and c.due_at<now() and c.status not in ('RESOLVED','DISMISSED','CLOSED'))) order by case when upper(p_sort)='PRIORITY' then case c.severity when 'CRITICAL' then 1 when 'HIGH' then 2 when 'MEDIUM' then 3 when 'WARNING' then 4 else 5 end end asc,c.due_at asc nulls last,c.created_at desc limit greatest(1,least(p_page_size,100)) offset (greatest(p_page,1)-1)*greatest(1,least(p_page_size,100)))select jsonb_build_object('rows',coalesce(jsonb_agg(to_jsonb(f)-'total_count'),'[]'::jsonb),'total',coalesce(max(total_count),0),'page',greatest(p_page,1),'pageSize',greatest(1,least(p_page_size,100)))into result from f;return result;end;$$;

create or replace function public.staff_compliance_case(p_case_id uuid)returns jsonb language plpgsql security definer set search_path=public as $$declare result jsonb;begin if not public.has_staff_permission('compliance.view') then raise exception 'Compliance view permission denied';end if;select to_jsonb(c)||jsonb_build_object('customer',case when public.has_staff_permission('customers.view_metadata') then (select jsonb_build_object('id',p.id,'display_name',p.display_name,'email',p.email,'plan',p.plan,'status',p.subscription_status) from public.profiles p where p.id=c.customer_user_id) else null end,'evidence',coalesce((select jsonb_agg(to_jsonb(e) order by e.created_at desc)from public.compliance_evidence e where e.case_id=c.id),'[]'::jsonb),'updates',coalesce((select jsonb_agg(to_jsonb(u) order by u.created_at desc)from public.compliance_case_updates u where u.case_id=c.id),'[]'::jsonb))into result from public.compliance_cases c where c.id=p_case_id;return result;end;$$;

create or replace function public.staff_compliance_case_action(p_case_id uuid,p_status text,p_note text,p_severity text default null,p_assigned_to uuid default null,p_due_at timestamptz default null)returns void language plpgsql security definer set search_path=public as $$declare old_status text;s text:=upper(p_status);begin if not public.has_staff_permission('compliance.manage') then raise exception 'Compliance manage permission denied';end if;if s not in ('NEW','OPEN','ASSIGNED','UNDER_REVIEW','AWAITING_EVIDENCE','AWAITING_CUSTOMER','DECISION_PENDING','MONITORING','RESOLVED','DISMISSED','CLOSED') then raise exception 'Invalid case status';end if;if nullif(trim(p_note),'') is null then raise exception 'A case action note is required';end if;select status into old_status from public.compliance_cases where id=p_case_id for update;if old_status is null then raise exception 'Case not found';end if;if p_assigned_to is not null and not exists(select 1 from public.staff_roles where user_id=p_assigned_to and is_active)then raise exception 'Reviewer is not authorized staff';end if;update public.compliance_cases set status=s,severity=coalesce(upper(p_severity),severity),assigned_to=coalesce(p_assigned_to,assigned_to),due_at=coalesce(p_due_at,due_at),updated_at=now(),resolved_at=case when s in ('RESOLVED','DISMISSED','CLOSED')then now()else null end,resolution=case when s in ('RESOLVED','DISMISSED')then p_note else resolution end where id=p_case_id;insert into public.compliance_case_updates(case_id,previous_status,new_status,note,created_by)values(p_case_id,old_status,s,trim(p_note),auth.uid());insert into public.admin_access_logs(staff_user_id,customer_user_id,action,resource_type,resource_id,success,metadata)select auth.uid(),customer_user_id,'COMPLIANCE_CASE_'||s,'COMPLIANCE_CASE',id::text,true,jsonb_build_object('previous_status',old_status,'note_recorded',true)from public.compliance_cases where id=p_case_id;end;$$;

revoke all on function public.staff_compliance_overview(),public.staff_compliance_cases(text,integer,integer,text,text,text,text,text,text),public.staff_compliance_case(uuid),public.staff_compliance_case_action(uuid,text,text,text,uuid,timestamptz) from public;
grant execute on function public.staff_compliance_overview(),public.staff_compliance_cases(text,integer,integer,text,text,text,text,text,text),public.staff_compliance_case(uuid),public.staff_compliance_case_action(uuid,text,text,text,uuid,timestamptz) to authenticated;
notify pgrst,'reload schema';
