import { ConfidenceEngine } from '../confidence/confidence-engine.ts';
import { DecisionEngine } from '../decision/decision-engine.ts';
import { DirectionResolutionEngine } from '../direction/direction-resolution-engine.ts';
import { EvidenceGraphBuilder } from '../evidence-graph/evidence-graph-builder.ts';
import { ReadinessPolicyEngine } from '../readiness/readiness-policy-engine.ts';
import { stableFingerprint } from '../serialization/stable-fingerprint.ts';
import type { CompositionRuleRunner } from '../strategy-composition/composition-rule-runner.ts';
import type { DetectorRunSummary } from '../types/detector.ts';
import type { MarketDataGatewayPort, ContextBuilderPort, DetectorRunnerPort } from '../analysis/analysis-orchestrator.ts';
import type { MarketContext } from '../contracts.ts';
import type { StrategyContext } from '../strategy-composition/composition-types.ts';
import type { EvidenceGraph } from '../evidence-graph/evidence-graph-types.ts';
import type { ConfidenceAssessment } from '../confidence/confidence-types.ts';
import type { ReadinessAssessment } from '../readiness/readiness-types.ts';
import type { DecisionAssessment } from '../decision/decision-types.ts';
import type { DirectionAssessment } from '../direction/direction-types.ts';
import type { CompiledStrategyDefinition } from '../strategy-definitions/strategy-definition-types.ts';
import type { IntelligencePipelineConfig, IntelligencePipelineError, IntelligencePipelineInput, IntelligencePipelineResult, IntelligencePipelineStage, IntelligencePipelineStageResult, IntelligencePipelineStatus } from './intelligence-pipeline-types.ts';

const ORDER: IntelligencePipelineStage[] = ['MARKET_DATA', 'DETECTORS', 'MARKET_CONTEXT', 'STRATEGY_COMPOSITION', 'EVIDENCE_GRAPH', 'CONFIDENCE', 'READINESS', 'DECISION', 'DIRECTION'];
function deepFreeze<T>(value: T): T { if (value && typeof value === 'object' && !Object.isFrozen(value)) { Object.values(value).forEach(deepFreeze); Object.freeze(value); } return value; }
const safeError = (stage: IntelligencePipelineStage, error: unknown): IntelligencePipelineError => ({ stage, code: error instanceof Error && 'code' in error && typeof error.code === 'string' ? error.code : `${stage}_FAILED`, message: error instanceof Error ? error.message : `${stage} failed.`, recoverable: false });

export type IntelligencePipelineDependencies = { gateway: MarketDataGatewayPort; runner: DetectorRunnerPort; contextBuilder: ContextBuilderPort; compositionRunner: Pick<CompositionRuleRunner, 'execute'>; evidenceGraphBuilder?: { build(definition: CompiledStrategyDefinition, market: MarketContext, strategy: StrategyContext): EvidenceGraph }; confidenceEngine?: { assess(definition: CompiledStrategyDefinition, strategy: StrategyContext, graph: EvidenceGraph): ConfidenceAssessment }; readinessEngine?: { assess(definition: CompiledStrategyDefinition, strategy: StrategyContext, graph: EvidenceGraph, confidence: ConfidenceAssessment, policy: IntelligencePipelineConfig['readinessPolicy']): ReadinessAssessment }; decisionEngine?: { assess(definition: CompiledStrategyDefinition, strategy: StrategyContext, graph: EvidenceGraph, confidence: ConfidenceAssessment, readiness: ReadinessAssessment, policy: IntelligencePipelineConfig['decisionPolicy']): DecisionAssessment }; directionEngine?: { assess(definition: CompiledStrategyDefinition, strategy: StrategyContext, graph: EvidenceGraph, confidence: ConfidenceAssessment, readiness: ReadinessAssessment, decision: DecisionAssessment, policy: IntelligencePipelineConfig['directionPolicy']): DirectionAssessment } };

export class IntelligencePipelineOrchestrator {
  readonly #d: Required<IntelligencePipelineDependencies>;
  constructor(dependencies: IntelligencePipelineDependencies) { this.#d = { ...dependencies, evidenceGraphBuilder: dependencies.evidenceGraphBuilder ?? new EvidenceGraphBuilder(), confidenceEngine: dependencies.confidenceEngine ?? new ConfidenceEngine(), readinessEngine: dependencies.readinessEngine ?? new ReadinessPolicyEngine(), decisionEngine: dependencies.decisionEngine ?? new DecisionEngine(), directionEngine: dependencies.directionEngine ?? new DirectionResolutionEngine() }; }

  async execute(input: IntelligencePipelineInput, config: IntelligencePipelineConfig): Promise<IntelligencePipelineResult> {
    const requestedAt = input.marketDataRequest.requestedAt;
    const stages: IntelligencePipelineStageResult[] = [], errors: IntelligencePipelineError[] = [], warnings: string[] = [];
    let snapshot: IntelligencePipelineResult['marketDataSnapshot'] = null, market: IntelligencePipelineResult['marketContext'] = null, strategy: IntelligencePipelineResult['strategyContext'] = null, graph: IntelligencePipelineResult['evidenceGraph'] = null, confidence: IntelligencePipelineResult['confidenceAssessment'] = null, readiness: IntelligencePipelineResult['readinessAssessment'] = null, decision: IntelligencePipelineResult['decisionAssessment'] = null, direction: IntelligencePipelineResult['directionAssessment'] = null;
    const stage = (name: IntelligencePipelineStage, status: IntelligencePipelineStatus, sourceInputIds: string[], outputId: string | null, stageWarnings: string[] = [], stageErrors: IntelligencePipelineError[] = []): void => { stages.push({ stage: name, status, startedFromRequestedAt: requestedAt, sourceInputIds, outputId, warnings: [...stageWarnings], errors: [...stageErrors], durationMs: null }); warnings.push(...stageWarnings); errors.push(...stageErrors); };
    const stop = (failedStage: IntelligencePipelineStage, error: unknown): IntelligencePipelineResult => { const issue = safeError(failedStage, error); stage(failedStage, 'ERROR', this.sourceIds(failedStage, input, { snapshot, market, strategy, graph, confidence, readiness, decision }), null, [], [issue]); for (const downstream of ORDER.slice(ORDER.indexOf(failedStage) + 1)) stage(downstream, 'UNAVAILABLE', [], null, [], [{ stage: downstream, code: 'UPSTREAM_UNAVAILABLE', message: `${downstream} could not run because ${failedStage} failed.`, recoverable: true }]); return this.result(input, config, stages, { snapshot, market, strategy, graph, confidence, readiness, decision, direction }, warnings, errors); };
    try { snapshot = await this.#d.gateway.fetchSnapshot(input.providerId, input.marketDataRequest); stage('MARKET_DATA', 'COMPLETED', [input.providerId, input.compiledStrategy.compiledStrategyId], snapshot.id, snapshot.validationWarnings); } catch (error) { return stop('MARKET_DATA', error); }
    let detectorSummary: DetectorRunSummary;
    try { detectorSummary = await this.#d.runner.execute(snapshot, input.detectorIds); const detectorErrors = detectorSummary.detectorFailures.map((failure) => ({ stage: 'DETECTORS' as const, code: failure.errorCode, message: failure.message, recoverable: true })); stage('DETECTORS', detectorErrors.length ? 'PARTIAL' : 'COMPLETED', [snapshot.id], detectorSummary.runId, detectorSummary.detectorResults.flatMap((item) => item.warnings), detectorErrors); } catch (error) { return stop('DETECTORS', error); }
    try { market = this.#d.contextBuilder.build(snapshot, detectorSummary); stage('MARKET_CONTEXT', detectorSummary.failedCount ? 'PARTIAL' : 'COMPLETED', [snapshot.id, detectorSummary.runId], market.contextId, market.warnings); } catch (error) { return stop('MARKET_CONTEXT', error); }
    try { strategy = this.#d.compositionRunner.execute(input.compiledStrategy, market); stage('STRATEGY_COMPOSITION', strategy.executionSummary.totalErrors ? 'PARTIAL' : 'COMPLETED', [input.compiledStrategy.compiledStrategyId, market.contextId], strategy.contextId, strategy.warnings); } catch (error) { return stop('STRATEGY_COMPOSITION', error); }
    try { graph = this.#d.evidenceGraphBuilder.build(input.compiledStrategy, market, strategy); stage('EVIDENCE_GRAPH', 'COMPLETED', [input.compiledStrategy.compiledStrategyId, market.contextId, strategy.contextId], graph.graphId, graph.warnings); } catch (error) { return stop('EVIDENCE_GRAPH', error); }
    try { confidence = this.#d.confidenceEngine.assess(input.compiledStrategy, strategy, graph); if (confidence.status === 'ERROR') throw new Error(confidence.warnings.join(' ') || 'Confidence assessment failed.'); stage('CONFIDENCE', confidence.status === 'PARTIAL' ? 'PARTIAL' : confidence.status === 'UNAVAILABLE' ? 'UNAVAILABLE' : 'COMPLETED', [input.compiledStrategy.compiledStrategyId, strategy.contextId, graph.graphId], confidence.assessmentId, confidence.warnings); } catch (error) { return stop('CONFIDENCE', error); }
    try { readiness = this.#d.readinessEngine.assess(input.compiledStrategy, strategy, graph, confidence, config.readinessPolicy); if (readiness.status === 'ERROR') throw new Error(readiness.warnings.join(' ') || 'Readiness assessment failed.'); stage('READINESS', readiness.status === 'UNAVAILABLE' ? 'UNAVAILABLE' : readiness.status === 'BLOCKED' ? 'BLOCKED' : 'COMPLETED', [input.compiledStrategy.compiledStrategyId, strategy.contextId, graph.graphId, confidence.assessmentId], readiness.assessmentId, readiness.warnings); } catch (error) { return stop('READINESS', error); }
    try { decision = this.#d.decisionEngine.assess(input.compiledStrategy, strategy, graph, confidence, readiness, config.decisionPolicy); if (decision.outcome === 'ERROR') throw new Error(decision.warnings.join(' ') || 'Decision assessment failed.'); stage('DECISION', decision.outcome === 'UNAVAILABLE' ? 'UNAVAILABLE' : decision.outcome === 'BLOCKED' ? 'BLOCKED' : 'COMPLETED', [input.compiledStrategy.compiledStrategyId, strategy.contextId, graph.graphId, confidence.assessmentId, readiness.assessmentId], decision.assessmentId, decision.warnings); } catch (error) { return stop('DECISION', error); }
    try { direction = this.#d.directionEngine.assess(input.compiledStrategy, strategy, graph, confidence, readiness, decision, config.directionPolicy); if (direction.outcome === 'ERROR') throw new Error(direction.warnings.join(' ') || 'Direction assessment failed.'); stage('DIRECTION', direction.outcome === 'UNAVAILABLE' ? 'UNAVAILABLE' : direction.outcome === 'CONFLICTED' ? 'PARTIAL' : 'COMPLETED', [input.compiledStrategy.compiledStrategyId, strategy.contextId, graph.graphId, confidence.assessmentId, readiness.assessmentId, decision.assessmentId], direction.assessmentId, direction.warnings); } catch (error) { return stop('DIRECTION', error); }
    return this.result(input, config, stages, { snapshot, market, strategy, graph, confidence, readiness, decision, direction }, warnings, errors);
  }

  private sourceIds(stage: IntelligencePipelineStage, input: IntelligencePipelineInput, outputs: Record<string, { id?: string; contextId?: string; graphId?: string; assessmentId?: string } | null>): string[] { return [input.compiledStrategy.compiledStrategyId, ...Object.values(outputs).flatMap((value) => value ? [value.id ?? value.contextId ?? value.graphId ?? value.assessmentId ?? ''].filter(Boolean) : [])]; }
  private result(input: IntelligencePipelineInput, config: IntelligencePipelineConfig, stages: IntelligencePipelineStageResult[], outputs: { snapshot: IntelligencePipelineResult['marketDataSnapshot']; market: IntelligencePipelineResult['marketContext']; strategy: IntelligencePipelineResult['strategyContext']; graph: IntelligencePipelineResult['evidenceGraph']; confidence: IntelligencePipelineResult['confidenceAssessment']; readiness: IntelligencePipelineResult['readinessAssessment']; decision: IntelligencePipelineResult['decisionAssessment']; direction: IntelligencePipelineResult['directionAssessment'] }, warnings: string[], errors: IntelligencePipelineError[]): IntelligencePipelineResult {
    const configurationFingerprint = stableFingerprint({ providerId: input.providerId, detectorIds: input.detectorIds, compiledStrategyId: input.compiledStrategy.compiledStrategyId, readinessPolicy: config.readinessPolicy, decisionPolicy: config.decisionPolicy, directionPolicy: config.directionPolicy });
    const counts = (status: IntelligencePipelineStatus) => stages.filter((item) => item.status === status).length;
    const status: IntelligencePipelineStatus = stages.some((item) => item.status === 'ERROR') ? 'ERROR' : stages.some((item) => item.status === 'UNAVAILABLE') ? 'UNAVAILABLE' : stages.some((item) => item.status === 'BLOCKED') ? 'BLOCKED' : stages.some((item) => item.status === 'PARTIAL') ? 'PARTIAL' : 'COMPLETED';
    return deepFreeze({ pipelineResultId: `intelligence-pipeline:${stableFingerprint({ compiledStrategyId: input.compiledStrategy.compiledStrategyId, requestedAt: input.marketDataRequest.requestedAt, symbol: input.marketDataRequest.instrument, assetClass: input.assetClass, configurationFingerprint, stageOutputs: stages.map((item) => [item.stage, item.outputId, item.status]) })}`, version: '1.0.0', requestedAt: input.marketDataRequest.requestedAt, symbol: input.marketDataRequest.instrument, assetClass: input.assetClass, strategyId: input.compiledStrategy.id, strategyVersion: input.compiledStrategy.version, compiledStrategyId: input.compiledStrategy.compiledStrategyId, configurationFingerprint, status, stages, marketDataSnapshot: outputs.snapshot, marketContext: outputs.market, strategyContext: outputs.strategy, evidenceGraph: outputs.graph, confidenceAssessment: outputs.confidence, readinessAssessment: outputs.readiness, decisionAssessment: outputs.decision, directionAssessment: outputs.direction, warnings: [...new Set(warnings)], errors, summary: { completedStages: counts('COMPLETED'), partialStages: counts('PARTIAL'), blockedStages: counts('BLOCKED'), unavailableStages: counts('UNAVAILABLE'), errorStages: counts('ERROR'), detectorCount: outputs.market?.detectorResults.length ?? 0, matchedRules: outputs.strategy?.totalMatched ?? 0, failedRules: outputs.strategy?.totalFailed ?? 0, meaning: 'INFORMATIONAL_DECISION_SUPPORT_NOT_TRADE_EXECUTION' } });
  }
}
